### ISSUE TITLE
How to run tests based on groups with the runner class?

### ISSUE THREAD

**Issue by shaynl** [saikrishna321/AppiumTestDistribution#105]
The following code run all tests from the added test classes:

`@Test public void testRunner() throws Exception {
        ParallelThread parallelThread = new ParallelThread();
        List<String> tests = new ArrayList<String>();
        tests.add("HomeTests");
        tests.add("RegLoginTests");
        parallelThread.runner("com.appium.tests.chosen",tests);
    }`

On each test I set groups like:  @Test (groups = {"Sanity","IOS","Registered"})
For example: How to run only tests that contain the Sanity group?

**Comment by saikrishna321** [comment]
@shaynl i'm working on it.. Will push by EOD.

**Comment by shaynl** [comment]
@saikrishna321 thanks so much for adding this.
on the same topic, will also "alwaysRun" will work when running on distribution mode?
I didn't test it yet but I have some tests that must be run on all devices like passing the intro screen and login.

**Comment by saikrishna321** [comment]
@shaynl there won't be any changes the way Parallel and Distribute works. startAppiumServer(getClass().getSimpleName()); method will be moved into AppiumParallelTest class and you will no longer need to call this in your @BeforeClass

You need to run the tests as INCLUDE_GROUPS="smoke" EXCLUDE_GROUPS="ignore" mvn clean -Dtest=Runner test 

Reason to have groups passed from commandline is, if you have the tests in CI pipeline you might want to run only the smoke groups as build pipeline and the regression post smoke going green.

Thoughts??

**Comment by shaynl** [comment]
@saikrishna321 sounds good solution. will it work with more than one group? like: INCLUDE_GROUPS="smoke,sanity".

about what I asked above:
 in TestNG there is an option to set for tests @Test (alwaysRun = true) - will this work with Distribute mode and run those tests on all devices?

**Comment by saikrishna321** [comment]
> INCLUDE_GROUPS="smoke,sanity"

yah it will work with multiple groups.

If you want all tests in all devices, then u need to set the RUNNER=parallel, Distribute works at class level not method level.

**Comment by saikrishna321** [comment]
@shaynl you need to run tests as below 
```
INCLUDE_GROUPS="smoke,regression" EXCLUDE_GROUPS="ignore" mvn clean -Dtest=Runner test
```
Make sure yours UserBaseTest looks like this(https://github.com/saikrishna321/AppiumTestDistribution/blob/a6602adf9ed15198412f7d070c5aa962ae122fd0/src/test/java/com/test/site/UserBaseTest.java)

Add this as your dependency to see the feature implementation.

```
	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>a6602adf9e</version>
	</dependency>
```

Please revert if it works.

**Comment by saikrishna321** [comment]
@shaynl ping

**Comment by shaynl** [comment]
@saikrishna321 thanks! I'll test it soon and report...

**Comment by shaynl** [comment]
@saikrishna321 It didn't work :(  
this is the error I get:
> Adding Android devices
{28aa002d=true, 1xb3x4301xxcx0d45007919c07fx7f0xf270e4fx=true}
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.886 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 2.474 sec  <<< FAILURE!
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.appium.executor.MyTestExecutor.constructXmlSuiteForParallel(MyTestExecutor.java:210)
	at com.appium.executor.MyTestExecutor.runMethodParallelAppium(MyTestExecutor.java:163)
	at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:134)
	at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:66)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:56)
	at com.appium.tests.Runner.testRunner(Runner.java:20)

also can't run anything also from IDE

**Comment by saikrishna321** [comment]
@shaynl will look at this, master is broken on this

**Comment by saikrishna321** [comment]
@shaynl  can you try with this version 93e1a9d1f9

**Comment by shaynl** [comment]
@saikrishna321  it fail again. It say that no device connected...

**Comment by saikrishna321** [comment]
I tried with the same version and works for me. Can you pls post the entire stack trace ..

**Comment by shaynl** [comment]
> ShayN:Automation3 shayn$ INCLUDE_GROUPS="Intro,Home,Game" mvn clean -Dtest=Runner test
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.pagepattern.appium:ChosenAutomation3:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 132, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ChosenAutomation3 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ChosenAutomation3 ---
[INFO] Deleting /Users/shayn/Automation3/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ChosenAutomation3 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/shayn/Automation3/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ ChosenAutomation3 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ChosenAutomation3 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 16 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ ChosenAutomation3 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 98 source files to /Users/shayn/Automation3/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ Automation3 ---
[INFO] Surefire report directory: /Users/shayn/Automation3/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
                            _  _        _ 
 _ __    __ _  _ __   __ _ | || |  ___ | |
| '_ \  / _` || '__| / _` || || | / _ \| |
| |_) || (_| || |   | (_| || || ||  __/| |
| .__/  \__,_||_|    \__,_||_||_| \___||_|
|_|                                       

creating directory: Logs
 _   _          ____                _                     ____                                   _              _ 
| \ | |  ___   |  _ \   ___ __   __(_)  ___   ___  ___   / ___|  ___   _ __   _ __    ___   ___ | |_   ___   __| |
|  \| | / _ \  | | | | / _ \\ \ / /| | / __| / _ \/ __| | |     / _ \ | '_ \ | '_ \  / _ \ / __|| __| / _ \ / _` |
| |\  || (_) | | |_| ||  __/ \ V / | || (__ |  __/\__ \ | |___ | (_) || | | || | | ||  __/| (__ | |_ |  __/| (_| |
|_| \_| \___/  |____/  \___|  \_/  |_| \___| \___||___/  \____| \___/ |_| |_||_| |_| \___| \___| \__| \___| \__,_|
                                                                                                                  


Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.497 s
[INFO] Finished at: 2016-09-20T12:13:31+03:00
[INFO] Final Memory: 26M/284M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project Automation3: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/shayn/Automation3 && /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/bin/java -jar /Users/shayn/Automation3/target/surefire/surefirebooter4521995367906624173.jar /Users/shayn/Automation3/target/surefire/surefire2291650009426731566tmp /Users/shayn/Automation3/target/surefire/surefire_03386954519088959459tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by saikrishna321** [comment]
@shaynl it says no devices connected

**Comment by shaynl** [comment]
@saikrishna321 This is the bug. 1 android device is connected and can be found when running adb devices. It also work fine with the other version I use: 3baa0dc

**Comment by saikrishna321** [comment]
@shaynl there was a bug when one android and one iOS device was connected. which was fixed 
https://github.com/saikrishna321/AppiumTestDistribution/commit/93e1a9d1f93e4abdef5eed60255b84b4cc64b657

Let me update the sample project, try with that

**Comment by saikrishna321** [comment]
@shaynl i have updated the sample project(https://github.com/saikrishna321/PageObjectPatternAppium)

Run Command: INCLUDE_GROUPS="smoke,regression" mvn clean -Dtest=Runner test

**Comment by shaynl** [comment]
@saikrishna321 yes it's working with the sample project. How I can make it work also with my project?

**Comment by saikrishna321** [comment]
pls look at the BeforeClass and AfterClass methods in the UserBaseTest....
