### ISSUE TITLE
Cucumber feature file supported yet ? 

### ISSUE THREAD

**Issue by Shashikant86** [saikrishna321/AppiumTestDistribution#107]
Hi @saikrishna321 Good job mate, you have created an awesome tool. Just wondering if it still supports Cucumber feature files? Currently Cucumber runner doesn't seems to be doing anything ..

Line 139[ here] parallel thread .java (https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/ParallelThread.java) is commented 

Have you tries it with Cucumber Features ?

**Comment by saikrishna321** [comment]
@Shashikant86 thanks mate 👍  

Yeah the framework works with cucumber feature in parallel. Currently the master is broken as there was an issue https://github.com/saikrishna321/AppiumTestDistribution/issues/90, i have fixed the testng runner now, will need to do it for cucumber as well. 

Please take a look at the sample test project, which has capabilities to run cucumber tests in parallel 

https://github.com/saikrishna321/PageObjectPatternAppium

**Comment by Shashikant86** [comment]
@saikrishna321 I have tried that project with my own ios app. It seems to be working with TestNG setup but with FRAMEWORK=cucumber I am getting following error 

               Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.708 sec <<< FAILURE! - in                  com.appium.steps.RunnerCukes
                   testCukesRunner on testCukesRunner(com.appium.steps.RunnerCukes)      (com.appium.steps.RunnerCukes)  Time elapsed: 0.48 sec  <<< FAILURE!
                 java.lang.NullPointerException: null
	            at      com.appium.executor.MyTestExecutor.deleteOutputDirectory(MyTestExecutor.java:319)
	           at com.appium.executor.MyTestExecutor.parallelTests(MyTestExecutor.java:124)
	            at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:143)
	           at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:66)
	          at com.appium.manager.ParallelThread.runner(ParallelThread.java:62)
	           at com.appium.steps.RunnerCukes.testCukesRunner(RunnerCukes.java:9)

My RunnerCukes.java looks like this and I have only one scenario to launch app written multiple time 

               package com.appium.steps;

                import com.appium.manager.ParallelThread;
                 import org.junit.Test;

                public class RunnerCukes {
                   @Test public void testCukesRunner() throws Exception {
                        ParallelThread parallelThread = new ParallelThread();
                     parallelThread.runner("");
                   }
               }
Do I need to pass something to runner? I have tried with following versions of AppiumTestDistribution 2dcc0b9476 which is current demo app.  23d8a2f(4.0.2), b7f9a5c(5.0.0), fab2838(5.0.1) 

Doesn't work for Cucumber framework same error all the time. Do you recommend any specific version should I try ?

**Comment by saikrishna321** [comment]
@Shashikant86 can you tell me how r u running the tests ? from commandline, if yes the command.

Let me also try

**Comment by Shashikant86** [comment]
@saikrishna321 I am running from command line with maven as you suggested 

              mvn clean -Dtest=RunnerCukes test
but planning to move to Gradle once got it working

**Comment by saikrishna321** [comment]
@Shashikant86 can you please <pluginManagement> tag in your pom.xml. Try with the below pom.xml it works.

```

**Comment by Shashikant86** [comment]
@saikrishna321 Working now :)  Just wondering What has changed from existing POM in the demo project ? 
It would be great if you can update POM in the demo project  :) Thanks a lot

**Comment by Shashikant86** [comment]
@saikrishna321 I haven't wrote java before in my life .. so might be dumb question.. How would you run this tests without maven from plain command line. Just wondering where are the binaries :)
