### ISSUE TITLE
extentReport with parent child test which can expand and collapse 

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#11]
Hi Sai, Can you please make changes in framework to give extentReport better look.

This is the current look 

![screen shot 2016-02-14 at 10 26 38 pm](https://cloud.githubusercontent.com/assets/12589206/13039910/23d70c0a-d36b-11e5-9692-678457a20a1f.png)

Can you please replace it with below look, here you can expand and collapse retry test in class which looks good compare to above.

![screen shot 2016-02-14 at 10 27 57 pm](https://cloud.githubusercontent.com/assets/12589206/13039912/2712042e-d36b-11e5-9415-1470289a5103.png)

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara can  please send a pull request let me take a look at this

**Comment by VinitSandesara** [comment]
Hi Sai, I didn't make any modification in your existing framework but what i have done is created sample project PFB attached if you run it you will see it generates extentReport with parent child test. If you can please take this as an enhancement and add it in your framework.

[extent_reports.zip](https://github.com/saikrishna321/AppiumTestDistribution/files/131500/extent_reports.zip)

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Hi Sai, Any update on this ?

Thanks
Vinit

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/commit/430668c635d882b1ba1cfe88057ece490cd23d54
