### ISSUE TITLE
Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified 	at java.lang.ProcessBuilder.start(Unknown Source)

### ISSUE THREAD

**Issue by ssrikantasahoo** [saikrishna321/AppiumTestDistribution#110]
![image](https://cloud.githubusercontent.com/assets/10594917/18659026/8c7a43d8-7f25-11e6-9a3d-86b25d516f14.png)
After i set PATH in eclipse cant start adb

**Comment by saikrishna321** [comment]
you need to ANDROID_HOME as well

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/issues/3
