### ISSUE TITLE
Ability to capture screenshots in the midst of a test

### ISSUE THREAD

**Issue by kskrishnan** [saikrishna321/AppiumTestDistribution#113]
I would like to add a feature, where in we need a method possibly in 'AppiumParallelTest' that takes the screenshot and writes the same to the Extent Report. Currently, the 'captureScreenShot' does not write to ExtentReport, it would be great to have this feature.

This would enable more interactive test execution where in one can take screenshots from a test method. Alternatively it is best to get a method that can be used in the Page class as well - perhaps a static method in a ScreenshotManager or even ExtentManager class ?

**Comment by saikrishna321** [comment]
@kskrishnan do you want this to be attached to the report as well for debugging purpose

**Comment by kskrishnan** [comment]
Hi @saikrishna321 , Yes that is the intention. The screenshots could be showed inline in the ExtentReports.html.

**Comment by saikrishna321** [comment]
@kskrishnan i'm working on video capturing for each tests, wouldn't that be more help rather than the screens for debugging

**Comment by kskrishnan** [comment]
Hi @saikrishna321 - Video recording is very good, but in order to give the choice, I believe it would be good to create a function that can just take interim screenshots. Its more for debugging purposes (I mean debugging the test code), and could be turned off in favor of video recording for the production version. 

I believe we could just strip the code from AppiumParallelTest.java > public void endLogTestResults(ITestResult result) > under if (result.getStatus() == ITestResult.FAILURE) and create a new method which could be re-used for both capturing screenshots for failure and on need basis. Of course, we might need to have additional param to differentiate the file name.

Let me know if you have a different view?

**Comment by saikrishna321** [comment]
@kskrishnan will expose a method captureScreenshot("FileName") which will capture the screenshot at that point 

This works ?

**Comment by kskrishnan** [comment]
@saikrishna321 - I don't think we need to pass the filename as a parameter. The method could automatically define the filename, perhaps add the platform, class, method & date-timestamp to the filename by default.

**Comment by saikrishna321** [comment]
@kskrishnan this is part of master now.Closing
