### ISSUE TITLE
Disabled android properties in config.properties, also will start android test session once android device connected

### ISSUE THREAD

**Issue by ansonliao** [saikrishna321/AppiumTestDistribution#114]
Hi Sai,
I found a problem on single mobile platform enabled but connected two android and iOS devices during test run.

I removed/commented `ANDROID_APP_PATH`, `APP_PACKAGE`, `APP_ACTIVITY` properties from `config.properties`,
and then connected one Android device, and one iOS device,
and then run the test.

and the test will start Android test session to run the test but fail, as no Android test properties found from `config.properites`.

Please help to check.

**Comment by saikrishna321** [comment]
@ansonliao do you see any kind of errors on this ?

**Comment by ansonliao** [comment]
@saikrishna321 
As disabled `ANDROID_APP_PATH`, `APP_PACKAGE`, `APP_ACTIVITY`, when android test session stated to initial appium Capabilities will be threw error such as the app file was not found message.

**Comment by saikrishna321** [comment]
closing, fixed on master
