### ISSUE TITLE
Appium v1.4.16 dose not recognize "--webkit-debug-proxy-port"

### ISSUE THREAD

**Issue by jawlitkp** [saikrishna321/AppiumTestDistribution#115]
Hello,

You have mentioned in your precondition document to use Appium v1.4.16 but it is not recognizing "--webkit-debug-proxy-port" server argument.

Please suggest

**Comment by saikrishna321** [comment]
@jawlitkp  i have tested with 1.4.16 and it works. It starts the webkit proxy .. Can you please tell me the error u see ?

**Comment by jawlitkp** [comment]
Here is method which is starting appium service in your code,i have tried to execute seperatly to see whats going on.

Also i don't see main.js file in Appium version 1.4.16 so i am using appium.js

	public void startAppium(){
 
		ServerArgument webKitProxy = new ServerArgument() {
			@Override public String getArgument() {
				return "--webkit-debug-proxy-port";
			}
		};

		System.out.println("**********************************************************************\n");
		System.out.println("Starting Appium Server to handle IOS");
		System.out.println("**********************************************************************\n");
//		AppiumServiceBuilder builder =  new AppiumServiceBuilder().withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
		AppiumServiceBuilder builder =  new AppiumServiceBuilder().withAppiumJS(new File("/usr/local/lib/node_modules/appium/bin/appium.js"))

				.withArgument(GeneralServerFlag.LOG_LEVEL, "info").withLogFile(new File(System.getProperty("user.dir")+"/test1.txt"))
				.withArgument(webKitProxy, "27755")
				.withArgument(GeneralServerFlag.LOG_LEVEL, "debug")
				.withArgument(GeneralServerFlag.TEMP_DIRECTORY,System.getProperty("user.dir")+"/tmp_1")
				.withArgument(GeneralServerFlag.SESSION_OVERRIDE)
				.usingPort(4723);
		appiumDriverLocalService = builder.build();
		appiumDriverLocalService.start();
        System.out.println("started");

	}


When i run this i am getting below error but same method works fine for 1.5.3 

usage: appium.js [-h] [-v] [--shell]
                 [--localizable-strings-dir LOCALIZABLESTRINGSDIR] [--app APP]
                 [--ipa IPA] [-U UDID] [-a ADDRESS] [-p PORT]
                 [-ca CALLBACKADDRESS] [-cp CALLBACKPORT] [-bp BOOTSTRAPPORT]
                 [-k] [-r BACKENDRETRIES] [--session-override] [--full-reset]
                 [--no-reset] [-l] [-lt LAUNCHTIMEOUT] [-g LOG]
                 [--log-level {info,info:debug,info:info,info:warn,info:error,warn,warn:debug,warn:info,waran:pwpairunm,.wjasr:n :eerrrroorr:, eUrnrroerc,ogenrirzoerd: daerbguugm,eenrtrso:r :-i-nwfeob,keirtr-odre:bwuagr-np,reorxryo-rp:oerrtr o2r7,7d5e5b.u
g,debug:debug,debug:info,debug:warn,debug:error}]
                 [--log-timestamp] [--local-timezone] [--log-no-colors]
                 [-G WEBHOOK] [--native-instruments-lib]
                 [--app-pkg ANDROIDPACKAGE] [--app-activity ANDROIDACTIVITY]
                 [--app-wait-package ANDROIDWAITPACKAGE]
                 [--app-wait-activity ANDROIDWAITACTIVITY]
                 [--android-coverage ANDROIDCOVERAGE] [--avd AVD]
                 [--avd-args AVDARGS]
                 [--device-ready-timeout ANDROIDDEVICEREADYTIMEOUT] [--safari]
                 [--device-name DEVICENAME] [--platform-name PLATFORMNAME]
                 [--platform-version PLATFORMVERSION]
                 [--automation-name AUTOMATIONNAME]
                 [--browser-name BROWSERNAME] [--default-device]
                 [--force-iphone] [--force-ipad] [--language LANGUAGE]
                 [--locale LOCALE] [--calendar-format CALENDARFORMAT]
                 [--orientation ORIENTATION]
                 [--tracetemplate AUTOMATIONTRACETEMPLATEPATH]
                 [--instruments INSTRUMENTSPATH] [--show-sim-log]
                 [--show-ios-log] [--nodeconfig NODECONFIG] [-ra ROBOTADDRESS]
                 [-rp ROBOTPORT] [--selendroid-port SELENDROIDPORT]
                 [--chromedriver-port CHROMEDRIVERPORT]
                 [--chromedriver-executable CHROMEDRIVEREXECUTABLE]
                 [--use-keystore] [--keystore-path KEYSTOREPATH]
                 [--keystore-password KEYSTOREPASSWORD] [--key-alias KEYALIAS]
                 [--key-password KEYPASSWORD] [--show-config]
                 [--no-perms-check] [--command-timeout DEFAULTCOMMANDTIMEOUT]
                 [--keep-keychains] [--strict-caps] [--isolate-sim-device]
                 [--tmp TMPDIR] [--trace-dir TRACEDIR]
                 [--intent-action INTENTACTION]
                 [--intent-category INTENTCATEGORY]
                 [--intent-flags INTENTFLAGS]
                 [--intent-args OPTIONALINTENTARGUMENTS]
                 [--dont-stop-app-on-reset] [--debug-log-spacing]
                 [--suppress-adb-kill-server] [--async-trace]

**Comment by jawlitkp** [comment]
Appium 1.5.3 has slowness issue so i don't want to rollout in my company ,i have to work with 1.4.16 for iOS parallel execution

**Comment by saikrishna321** [comment]
with 1.4.16 ios-web-kit proxy was not implemented on the server side, that's the reason ur seeing this.

This framework was WIP for web view iOS coz of this reason. with appium 1.5 it works on parallel web view

**Comment by jawlitkp** [comment]
Thanks Sai.make sense.

btw are you seeing slowness while executing iOS web view test using 1.5 ? in my case i am seeing significant slowness .and as soon as i downgrade to 1.4.16 problem disappears.

Any help would be appreciated.

**Comment by saikrishna321** [comment]
my app is Native, so can't comment on the web view performance
