### ISSUE TITLE
How do I run tests on iOS Simulator?

### ISSUE THREAD

**Issue by kskrishnan** [saikrishna321/AppiumTestDistribution#116]
I started a iOS simulator and set RUNNER=parallel in config.properties. Even then the tests are not launching on iOS Simulator. Should I provide some flag to get the framework to start iOS Simulator?

I know multiple iOS simulators are not supported, but tests are not running even on one simulator. Kindly revert back if I am missing anything?

**Comment by saikrishna321** [comment]
this framework supports only running test on real devices not on simulators,untill appium server supports fbsimctl

**Comment by kskrishnan** [comment]
Sai, I noticed that Appium by default supports iOS simulator. I am able to run tests on iOS Simulators using plain Appium outside of this framework. Is there anything (fbsimctl) that this framework specifically needs for this? I would assume you need this to check the status of the simulator, etc. (similar to adb), but can you confirm if my assumption is right?

Also, I am planning to write a thin layer in my test suite to run tests outside this framework using vannilla Appium. I have another TestBase class (similar to UserTestBase) but that is used for running standalone. It works when I change the baseclass of tests to TestBase instead of UserTestBase. I want to have a mechanism whereby I could switch between this framework and plain appium. Is this possible, if so, can you give me some tips?
