### ISSUE TITLE
Which appium version is compatible with AppiumTestDistribution?

### ISSUE THREAD

**Issue by aryak93** [saikrishna321/AppiumTestDistribution#117]
My appium server version is 1.5.3 and I am trying to run tests on both Android and iOS devices. For android (both emulator and device) everything runs fine. But for iOS, I am only able to run tests on the simulator and not on an actual device. 

Is there anything I'm missing? I read on an Appium forum that with the latest version of appium, there is some problem for running tests on iOS devices. Please confirm and let me know whether.

Thanks

**Comment by saikrishna321** [comment]
@aryak93 running parallel on iOS device is possible provided your OS level is < 10.0
