### ISSUE TITLE
Parallel testing support for iOS 

### ISSUE THREAD

**Issue by jimmy9gag** [saikrishna321/AppiumTestDistribution#12]
hey, thanks for the cool framework.

i just noticed that in AppiumParallelTest class, when the property for "APP_TYPE" is native, it sets a capabilities to android. 

Are there any ways to parellely distribute iOS testings also? or do i have to manually set an ios setup like one in your sample?

thanks!

**Comment by saikrishna321** [comment]
@jimmy9gag Thanks for trying out the AppiumTestDistribution :)  i'm working on getting Parallel Run for iOS devices. Will keep you posted once i have a stable test framework.

**Comment by jimmy9gag** [comment]
Sure! Once again, thanks for the great framework!

will be waiting for the updates!

**Comment by VinitSandesara** [comment]
I am also eagerly waiting on this. Hope it comes out soon to us.

Thanks
Vinit

**Comment by saikrishna321** [comment]
@jimmy9gag Some updates, we were able to  run Parallel iOS test on real devices without any issues, right now the tests are running in distributed way. Looking to see how it can be handle to run tests concurrently.

You can find the code at (branch:parallel_ios) :+1: 

Thanks to @SrinivasanTarget(https://github.com/SrinivasanTarget) for helping me debug the tests.

**Comment by VinitSandesara** [comment]
Sai, Is this new update available in  AppiumTestDistribution ? i am not able to find parallel_ios in this branch.

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara its still not merged with master, its on another branch 
https://github.com/saikrishna321/AppiumTestDistribution/tree/parallel_ios

**Comment by VinitSandesara** [comment]
Thanks Sai.

**Comment by jimmy9gag** [comment]
@saikrishna321 AWESOME! i'll check it out today! 

great work!

**Comment by divyanshugarg** [comment]
@saikrishna
When you are talking about parallel test on iOS real devices, then these
devices are connected to same Mac machine or different.
As per I know, on single Mac machine, even we connect multiple devices but
we can execute test only one of them at a time due to limitation of
instrumentation.
Correct my understanding, if i am wrong somewhere or aware of latest change.

**Comment by saikrishna321** [comment]
@divyanshugarg - One or more iOS devices are connected to the same mac machine and it works across devices. Tested on 3 devices and it works fine. 

As  of Xcode 6.3.2, multiple instruments sessions can be started from a single host

**Comment by VinitSandesara** [comment]
https://github.com/divyanshugarg FYI runmode using distribute way it is working as expected, Sai is working on to make it happen for parallel as well. Let's hope he release it out soon to us.

Thanks
Vinit

**Comment by divyanshugarg** [comment]
@saikrishna - Thanks for the update. To achieve the same, I just need to
start Appium server on different ports with different UDID or anything else
also require (may be at xocde/instruments side)?

**Comment by saikrishna321** [comment]
@divyanshugarg 

appium --session-override -p 62488 -bp 56556 --tmp /tmp/ios6s/
appium --session-override -p 62775 -bp 55942 --tmp /tmp/ios5s/

you need to specify a different tmp path ...

**Comment by saikrishna321** [comment]
@VinitSandesara @jimmy9gag i have merged iOS parallel to master .. can u give it a try with your test

**Comment by jimmy9gag** [comment]
@saikrishna321 ahh, thanks for the update. I currently paused in using Appium for iOS due to the low performances in pages with complex UI architecture, so we moved on to using the native-automator, XCUITest. We'll prob pick up Appium back when its around 1.6 version (if they implement the xcui-driver). I'll still check it out for my personal projects and give you feedbacks when i get some time!! 

thanks!!
