### ISSUE TITLE
Upgrade extentreports version to 3.0 latest

### ISSUE THREAD

**Issue by karthikbhatnagar** [saikrishna321/AppiumTestDistribution#121]
hi Sai
Please update the extentreports version to latest 3.0.  it was released 2 days ago on the website.
Note:  i have used to test with it and a few things:
1. the group id has changed
   com.aventstack
2. each reporter is separate and we can choose to add
3. the new shortcuts feature is very nice
4. No need to end tests
5. better category and exception views

cc @anshooarora

**Comment by saikrishna321** [comment]
@karthikbhatnagar is there any difference in v2 and v3 implementation?

**Comment by karthikbhatnagar** [comment]
@saikrishna321 - sorry for the late reply, yes, it has several changes but they are 80% setup related i believe.  i checked https://github.com/anshooarora/extentreports-java/issues/652, pls let me know if any help is needed.

**Comment by saikrishna321** [comment]
@karthikbhatnagar i got it working.. will be making the changes soon to the master, i don't see a way to attache videologs to the report in v3.

**Comment by karthikbhatnagar** [comment]
Sai
i think most people require snapshots so until video support is added it shouldn't be a big miss. what do you think?
are lots of ppl using video?

**Comment by saikrishna321** [comment]
@karthikbhatnagar i have implemented and having minor issues, will merge to master in a day ..

**Comment by Vishnu1067** [comment]
Can we make dynamic screenshots using timestamp? I cannot use getter setter
for storing device id to make dynamic ss... pls suggest me

**Comment by saikrishna321** [comment]
@Vishnu1067 can you please open a new issue and provide more details what is that your looking for ... This thread is just to track the extent report v3

**Comment by Vishnu1067** [comment]
Hello Sai, I did some mistake assigning thread. Now it is working fine.
Thank you

**Comment by saikrishna321** [comment]
@karthikbhatnagar master now has the Extent v3 support. Use the below dependency version and give it a try ... 

```
	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>a98e7c425a</version>
	</dependency>
```

the methods have been moved within the dependency, make sure you make these changes 

```
    @BeforeClass(alwaysRun = true) public void beforeClass() throws Exception {
        //Moving the method inside the dependency in the next release
        //startAppiumServer(getClass().getSimpleName());
    }

    @AfterClass(alwaysRun = true) public void afterClass()
        throws InterruptedException, IOException {
        //Moving the method inside the dependency in the next release
        //killAppiumServer();
    }
```

Give it a try n let me know if it works

**Comment by saikrishna321** [comment]
@karthikbhatnagar ping

**Comment by karthikbhatnagar** [comment]
Thanks Sai
Sorry I was in holiday. I checked and it runs smoothly. The new report looks so good
Thanks for your efforts
