### ISSUE TITLE
How can I run mobile web app test parallel using this framework

### ISSUE THREAD

**Issue by gaurabhi1986** [saikrishna321/AppiumTestDistribution#122]
Hi,

I need to execute my mobile web app test on multiple devices.

Can you please help me for below queries: 
- How can I use this framework to execute my mobile web test parallel ?
- How can I run my test on remotely hosted devices ?

Thanks,
Abhishek Gaur

**Comment by saikrishna321** [comment]
@gaurabhi1986 you need have your config.properties as below

```
RUNNER=distribute
APPIUM_JS_PATH=/usr/local/lib/node_modules/appium/build/lib/main.js
BROWSER_TYPE=chrome
APP_TYPE=web
FRAMEWORK=testng
```
