### ISSUE TITLE
App not launching with Appium 1.6 

### ISSUE THREAD

**Issue by shaynl** [saikrishna321/AppiumTestDistribution#124]
@saikrishna321  I can't run my test with the latest Appium ver 1.6, xcode8, IOS10
I tried it without AppiumTestDistribution and it worked well but when run it with AppiumTestDistribution the app not launching after WebDriverAgent is loading.
I'm using your latest code c6ff6ac. please advice.

**Comment by shaynl** [comment]
got this fixed when I removed my app bundle ID from DesiredCapabilities so it will be like this:
iOSCapabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "");
very strange...

**Comment by saikrishna321** [comment]
if it's real device then BundleID is mandatory flag ....

**Comment by shaynl** [comment]
yes it's real device but with your tool it's work well only if BundleID is empty.
If I'll enter my app BundleID it will remove the app from the device if it's exist, then reinstall it but will not launch it when the test should start.

**Comment by saikrishna321** [comment]
can you pls post logs when u pass the BundleID

**Comment by shaynl** [comment]
sorry, when I checked the log again I noticed that the BundleID was wrong. It strange that it did work without your tool... 
anyway all is good now. thanks :)

**Comment by saikrishna321** [comment]
can you pass the BundleID empty and then send the logs ... interested to see how it picks

**Comment by shaynl** [comment]
here is the log with bundleID empty: https://gist.github.com/shaynl/8766c63b03b095ebb31bff67dc2d5607

**Comment by saikrishna321** [comment]
what's the logs with BundleID, so that I can see what's the error

**Comment by shaynl** [comment]
with BundleID: https://gist.github.com/shaynl/5e53566fefba3fba396ed7e3862a64e2

**Comment by saikrishna321** [comment]
@shaynl i dont see any error on the server logs ..
