### ISSUE TITLE
Not detecting iOS Simulators running

### ISSUE THREAD

**Issue by MemoRuan** [saikrishna321/AppiumTestDistribution#125]
Hi Sai, @saikrishna321

I was not able to run a test on iOS Simulator, the execution throws this comments:
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
 parallel
creating directory: Logs
No Device Connected
 NoDevicesConnected

Looks The framework is not detecting the iOS Simulator.

I was able to execute a parallel test on 2 Android devices, also a quick test on a real Apple device.

Is there a way to detect iOS Simulator for test execution?

**Comment by saikrishna321** [comment]
@MemoRuan until appium supports handling parallel sim, this framework won't
