### ISSUE TITLE
Launching App on every @test method

### ISSUE THREAD

**Issue by raveendaranugu** [saikrishna321/AppiumTestDistribution#126]
Hi @saikrishna321 ,
Currently while running the scripts the app is getting launched on every @test method. (what if we have 50-100 testcases ) . Can we able to run the scripts without closing and opening the app for every @test methd.

**Comment by saikrishna321** [comment]
@raveendaranugu we are doing this coz we should have a clean state application for the next test, so that u would not end up with flaky test/ test dependency. 

It just quit's the app and recreate a new instance for the next test
