### ISSUE TITLE
How do we get new frames?

### ISSUE THREAD

**Issue by eugenjeno** [saikrishna321/AppiumTestDistribution#136]
is there a specific way to get other frames?

**Comment by saikrishna321** [comment]
is there any specific device frame your looking for ??

**Comment by eugenjeno** [comment]
hi, for the moment while I'm trying out the tool, I'm looking for Samsung S4 and Samsung S5 mini frames
thx

**Comment by saikrishna321** [comment]
@eugenjeno i pick them from http://facebook.design/devices and resize them as per the device screenshots captured
