### ISSUE TITLE
Result by category does not consider the failed test case

### ISSUE THREAD

**Issue by dkjha52** [saikrishna321/AppiumTestDistribution#137]
See the attached screen shot. Total no of passed test cases is 5 and one fail. But Category shows the passed test cases is 6.
![screen shot category result](https://cloud.githubusercontent.com/assets/5102438/20827482/35d5909e-b898-11e6-9010-72c278e13b90.png

**Comment by saikrishna321** [comment]
@dkjha52 what is the AppiumTestDistribution version your using ?

**Comment by dkjha52** [comment]
I am using latest one (downloaded master zip) including the latest version of ExtentReports.

**Comment by saikrishna321** [comment]
So you build from master and building into your project ?

**Comment by dkjha52** [comment]
Yes. I build from master and using in the project.

**Comment by saikrishna321** [comment]
can you run mvn clean -Dtest=Runner test from master project and check, i'm unable to reproduce it

**Comment by dkjha52** [comment]
I executed mvn clean -Dtest=Runner test from master project and getting the same result. Total no of passed test cases is 5 and one fail. But Category shows the passed test cases is 6

**Comment by saikrishna321** [comment]
@dkjha52 i'm not able to reproduce check the screen shot 

<img width="705" alt="screen shot 2016-12-05 at 6 14 29 pm" src="https://cloud.githubusercontent.com/assets/4045041/20885436/d5893436-bb01-11e6-9f50-726e18eeba02.png">

**Comment by dkjha52** [comment]
Now I am using the same testcases. I took the fresh code and still getting the same. The only difference I can see in pom file. I am skipping the line 145-298 from the pom file you mentioned in the distribution. Due to that am i getting this issue?

**Comment by saikrishna321** [comment]
@dkjha52 connect two devices and give it try .. i got the above results from master tests

**Comment by dkjha52** [comment]
I tried with two devices and getting the same. See the attached screen shot. I will try again and will update you.
![categoryscreenshot](https://cloud.githubusercontent.com/assets/5102438/20925536/9c40fb1e-bbdd-11e6-876c-35c3700087fa.png)

**Comment by saikrishna321** [comment]
@dkjha52 you need to provide a sample project, i'm unable to reproduce from master

**Comment by dkjha52** [comment]
Please find the attached sample project zip.
[AppiumDistribution.zip](https://github.com/saikrishna321/AppiumTestDistribution/files/636132/AppiumDistribution.zip)

**Comment by saikrishna321** [comment]
<img width="1376" alt="screen shot 2016-12-07 at 6 10 30 pm" src="https://cloud.githubusercontent.com/assets/4045041/20968074/9e6f95a6-bc93-11e6-8cb4-a6a4fafcbd17.png">

this issue is with extent-report 3.0.1 works fine with 3.0.0.

Please raise issue on extent-report repo
