### ISSUE TITLE
Maven build reports success even when Cucumber feature files failed

### ISSUE THREAD

**Issue by brtu** [saikrishna321/AppiumTestDistribution#138]
I am using the Cucumber test runner with Maven build system.  When I run the command  "mvn clean -Dtest=RunnerCukes test", the feature file test fails, but the maven build still succeeds.  This is causing trouble with my CI system because it reports all jobs as a success (even if they have failing tests).  I thought I saw a fix for this that was committed before, does this work for TestNG but not Cucumber?

**Comment by saikrishna321** [comment]
@brtu i came across this issue on ma CI pipeline as well, fixed it for TestNG guess it should work for cucumber as well . Will tests n update.

**Comment by saikrishna321** [comment]
@brtu i went through the code, this needs to be fixed. Will do that

**Comment by saikrishna321** [comment]
@brtu try with below version 

```
	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>add5b9143e</version>
	</dependency>
```

you runner should be 

https://github.com/saikrishna321/AppiumTestDistribution/blob/add5b9143ea3e0b91ef7563684032296d930367b/src/test/java/com/test/cucumber/cukesrunner/RunnerCukes.java#L14-L15

**Comment by brtu** [comment]
@saikrishna321 I tried with add5b9143e and this issue seems to be fixed.  Awesome job!
