### ISSUE TITLE
how to run parallel test with testng on ios physical devices

### ISSUE THREAD

**Issue by zhuchuji** [saikrishna321/AppiumTestDistribution#140]
Hi, Could you explain how to run parallel test on ios physical devices?
I work with appium and want to run parallel test on ios devices. But It always happen that when the second device start, the first started one shutdown or the first one doesn't work anymore. 
I try to create new appium session with different port, and run parallel test with testng. There are two frequently happened situations:
1. When the second device starts, the first device will shutdown, and the error is: instrument crash on startup
2. When the first device starts and works, the second device starts but does not act any more, finally it shows error: the instrument never checked in.
I want to know how you make it to run parallel tests on multiple ios physical devices.
Below is my working environment:
appium: 1.5.3
xcode: 7.3.1
devices: iphone6(ios 9.2) iphone6s(ios 9.3)

**Comment by saikrishna321** [comment]
@zhuchuji this library helps you run tests in parallel for iOS, you need to create different tmp folder for each instance of instruments.trace and also make sure your server session are thread safe

**Comment by zhuchuji** [comment]
@saikrishna321 hi, below is how I start the appium server session:
	@BeforeClass
	@Parameters({ "tempDir" })
	public void setup(final String tempDir) {
		this.service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
				.withAppiumJS(new File("/Applications/appium.app/Contents/Resources/node_modules/appium/build/lib/main.js"))
				.withArgument(GeneralServerFlag.TEMP_DIRECTORY, tempDir)
				.withArgument(GeneralServerFlag.SESSION_OVERRIDE)
				.usingAnyFreePort()
				.withArgument(GeneralServerFlag.LOG_LEVEL, "info"));
		this.service.start();
	}

And below is how I start create the driver(AppiumIOSDriver is the class to encapsulate the driver):
	@BeforeMethod(alwaysRun=true)
	@Parameters({"udid", "deviceName", "platformVersion" })
	public void beforeMethod(final String udid, final String deviceName, final String platformVersion) {
		this.driver = new AppiumIOSDriver(service.getUrl().toExternalForm(), udid,
				deviceName, platformVersion);
	}

You can see I have create different tmp folders for each instance of appium service. But I don't know how to make the server session thread safe.

**Comment by zhuchuji** [comment]
@saikrishna321 hi. It finally could run parallel tests on ios devices. But devices still will crash after run a few test cases. The error is: abnormal instruments termination

**Comment by saikrishna321** [comment]
@zhuchuji not sure why instruments is terminating, is there any reasons your trying to implement it your way? as this frameworks helps you run tests in parallel across ios devices..

**Comment by zhuchuji** [comment]
@saikrishna321 I also want to find out what's wrong with appium service, instruments or testng. But not a clue for present.

**Comment by saikrishna321** [comment]
@zhuchuji  https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumManager.java#L79

**Comment by zhuchuji** [comment]
@saikrishna321 I compare it with my code, and find out there are only one difference: you have set webkitProxy argument. But I search it on appium.io to find out it's for automation test on safari

**Comment by saikrishna321** [comment]
@zhuchuji yah its for web proxy ... Did you try running with this framework ?

**Comment by zhuchuji** [comment]
@saikrishna321 sorry, I didn't run it, but I downloaded the source code to find out there's any point I miss in my codes...
