### ISSUE TITLE
iOS basic configuration

### ISSUE THREAD

**Issue by Vishnu1067** [saikrishna321/AppiumTestDistribution#141]
Hello Guys,

Sorry for this question. I would like to purchase MacBook and want to know configuration for that. Is there any specific requirements for running automation ? Because in windows, emulators will work only for intel processor. Since MacBook price is too expensive, I would buy the correct one which suites for testing purpose as well.

Thanks in advance.

**Comment by saikrishna321** [comment]
@Vishnu1067 google search should help you on this.
