### ISSUE TITLE
Cucumber runner - No ExtentReport.html is generated for tests

### ISSUE THREAD

**Issue by brtu** [saikrishna321/AppiumTestDistribution#142]
I am using AppiumTestDistribution on commit add5b9143e and the Cucumber test runner.  When I run my Cucumber tests, no ExtentReport file is generated at the end.  I think the problem may be due to the previous commit, 5d1ed9602e (?).

**Comment by saikrishna321** [comment]
@brtu i just ran with the latest and i get to see the ExtentReports.html, refer the screenshot

<img width="1374" alt="screen shot 2016-12-07 at 8 58 13 pm" src="https://cloud.githubusercontent.com/assets/4045041/20997024/e3d9e892-bd12-11e6-9e59-13833e10179c.png">

**Comment by brtu** [comment]
@saikrishna321 Hm... I will recheck and report back.

**Comment by brtu** [comment]
@saikrishna321 My mistake, I see it now.  I think the filename changed.  Sorry for the false bug report
