### ISSUE TITLE
Error running tests: Connection refused

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#146]
Hi @saikrishna321 
Attached is full [log](https://gist.github.com/RatkoD/0d54324948fe3279db28045be3dbac22) from running the tests.

I'm truing to run tests on Appium 1.6.3 on latest MacOS and iOS 10+. I have installed all the dependencies. Here is my [POM.xml](https://gist.github.com/RatkoD/9c84a9e7f4cced9d3ddaaaa8a1ea8ddd).

**Comment by saikrishna321** [comment]
@RatkoD i have never tested the framework working with ios 10. 

You need to provide the deviceconsole path not xcpretty path 

https://gist.github.com/RatkoD/0d54324948fe3279db28045be3dbac22#file-fullatdlog-L126

**Comment by RatkoD** [comment]
Changed the path to /usr/local/lib/node_modules/deviceconsole and it's completely same :(

**Comment by RatkoD** [comment]
I get the same with iOS 9.3.5 device.

**Comment by RatkoD** [comment]
I get the same error with PageObjectPatternAppium demo project. But the framework works for Android devices...

**Comment by RatkoD** [comment]
But both don't work when started from IntelliJ

`
Adding iOS devices
Adding Android devices
{4d0040148bb83015=true}
[TestNG] Running:
  /Users/ratkododevski/Library/Caches/IdeaIC2016.3/temp-testng-customsuite.xml

org.testng.TestNGException: 
Parameter 'device' is required by @Configuration on method startAppiumServer but has not been marked @Optional or defined
in /Users/ratkododevski/Library/Caches/IdeaIC2016.3/temp-testng-customsuite.xml
`

**Comment by saikrishna321** [comment]
@RatkoD it should be /usr/local/lib/node_modules/deviceconsole/deviceconsole

Are you able to run the tests on 9.3.5 outside the framework ?

**Comment by RatkoD** [comment]
I get the same result with /usr/local/lib/node_modules/deviceconsole/deviceconsole

**Comment by saikrishna321** [comment]
@RatkoD are you able to run the tests outside the parallel framework ?

**Comment by saikrishna321** [comment]
@RatkoD its more appium side issue, you need to raise it on appium repo.
