### ISSUE TITLE
After execution of one test, instrument crashes with exit code 0

### ISSUE THREAD

**Issue by pchowdek** [saikrishna321/AppiumTestDistribution#148]
appium version : 1.5.3
node.js version 6.9.2
npm version 3.10.9

command used : INCLUDE_GROUPS="sanity" mvn clean -Dtest=Runner test

After execution of first test, suddenly the instruments crash and exit with error code 0, 
attaching the console log with the issue.

[Issue_AppiumParallel.docx](https://github.com/saikrishna321/AppiumTestDistribution/files/663739/Issue_AppiumParallel.docx)

**Comment by saikrishna321** [comment]
@pchowdek make sure you don't have ANDROID_APP_PATH as your running only the iOS.

Pls share your config.properties

**Comment by pchowdek** [comment]
@saikrishna321 
I have commented out the android App path.. but still the null pointer is thrown for android

please find the config.properties below.

#ANDROID_APP_PATH=/Users/saikrisv/git/PageObjectPatternAppium/build/wordpress.zip
#APP_PACKAGE=org.wordpress.android
#APP_ACTIVITY=org.wordpress.android.ui.WPLaunchActivity
#RUNNER=distribute
#APPIUM_JS_PATH=/usr/local/lib/node_modules/appium/build/lib/main.js
#BROWSER_TYPE=chrome
#APP_TYPE=NA
#FRAMEWORK=testng
#MONGODB_SERVER=10.211.55.8
#MONGODB_PORT=27017
#CI_BASE_URI=http://Your_Jenkins_URL/path_to_your_project_till_root

IOS_APP_PATH=/Users/JioRohith/Documents/TejiOS/jioappautomationframework/JioAutomationTestng/src/test/resources/JioCloud_preprod.ipa
#ANDROID_APP_PATH=/Users/kalpesh/Documents/Gitproject/jioappautomationframework/JioAutomationTestng/src/test/resources/tejAndroid.apk
APP_PACKAGE=jio.cloud.drive
APP_ACTIVITY=com.rjil.cloud.tej.client.app.AppStartActivity
#APP_PACKAGE=com.jio.cloud.tej
BUNDLE_ID=com.jio.cloud.tej
#BUNDLE_ID=com.rjil.tej.dev
RUNNER=parallel
APPIUM_JS_PATH=/usr/local/lib/node_modules/appium/build/lib/main.js
APP_TYPE=NA
FRAMEWORK=testng

**Comment by saikrishna321** [comment]
@pchowdek can you try with the below version 

```	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>fd455e6b1f</version>
	</dependency>
```

its more an xcode issues, i run on multiple ios devices and it works fine.

**Comment by saikrishna321** [comment]
closing as inactive
