### ISSUE TITLE
Adding new test class to the XML & to the runner doesn't work  

### ISSUE THREAD

**Issue by test666qa** [saikrishna321/AppiumTestDistribution#151]
How to add my own tests to the distribution ? , Iv'e tried every single way !! 
It will escape the whole tests if test classes added to the package 
Can someone help me please !!

**Comment by test666qa** [comment]
Hi sai , 
Thanks for the fast respond , Im following your instruction
Iv'e Tried  : 
1) Importing my tests to the package com.tests.site where is the Runner Class 
    Running : " mvn clean -Dtest=Runner test "
2) Changing the tests names listed on the testng.xml manually to the new tests !! 

*The weird thing is when Im not changing the class name "HomePageTest.." the test is runnable &
  work perfect , but when I'm using a new class name like "MyTest" the test is not executed even , it's
  been ignored by testng .

**Comment by saikrishna321** [comment]
@test666qa  ping

**Comment by test666qa** [comment]
For some reason , it's not running all the added tests , Inserting my code : 

Runner : 
`ParallelThread parallelThread = new ParallelThread();
        List<String> tests = new ArrayList<String>();
        tests.add("Install_Test");
        tests.add("ScanTest");
        tests.add("DetectTest");
        tests.add("ReportBugTest");
        boolean hasFailures = parallelThread.runner("com.test.allandroid",tests);
        Assert.assertFalse(hasFailures, "Testcases have failed in parallel execution");`

Actual (Generated XML ): 
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="4" verbose="2" name="TestNG Forum" parallel="tests">
  <listeners>
    <listener class-name="com.appium.manager.AppiumParallelTest"/>
    <listener class-name="com.appium.utils.RetryListener"/>
  </listeners>
  <test name="TestNG Test0" preserve-order="false">
    <parameter name="device" value="SH4ANWM00307"/>
    <classes>
      <class name="com.test.allandroid.ReportBugTest"/>
      <class name="com.test.allandroid.Install_Test"/>
      <class name="com.test.allandroid.DetectTest"/>
    </classes>
  </test> 
  <test name="TestNG Test1" preserve-order="false">
    <parameter name="device" value="ENU7N16109007407"/>
    <classes>
      <class name="com.test.allandroid.ReportBugTest"/>
      <class name="com.test.allandroid.Install_Test"/>
      <class name="com.test.allandroid.DetectTest"/>
    </classes>
  </test> 
  <test name="TestNG Test2" preserve-order="false">
    <parameter name="device" value="HT4BBJT02344"/>
    <classes>
      <class name="com.test.allandroid.ReportBugTest"/>
      <class name="com.test.allandroid.Install_Test"/>
      <class name="com.test.allandroid.DetectTest"/>
    </classes>
  </test> 
  <test name="TestNG Test3" preserve-order="false">
    <parameter name="device" value="0184e701d488e860"/>
    <classes>
      <class name="com.test.allandroid.ReportBugTest"/>
      <class name="com.test.allandroid.Install_Test"/>
      <class name="com.test.allandroid.DetectTest"/>
    </classes>
  </test> 
</suite> 
`

I don't know why the second test class is not included , maybe I'm missing some building process !!

**Comment by test666qa** [comment]
@saikrishna321 
It's working like charm , my mistake (It didn't added it because the package name on the class wasn't correct )

Sorry !!
