### ISSUE TITLE
Support XCUITest and UIAutomation at once

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#152]
Is it possible to make the framework to support both test platforms? We need to do some of the tests on iOS 10+ devices and the same tests on on some older devices.

**Comment by saikrishna321** [comment]
@RatkoD you can just send the caps for iOS and it should work.

**Comment by RatkoD** [comment]
The things is that I have connected the different devices on the same node.

**Comment by saikrishna321** [comment]
@RatkoD does that work now ?

**Comment by brtu** [comment]
We have iOS 10+ and iOS 7/8/9 devices connected to the same node and working with AppiumTestDistribution.  iOS 10+ requires Xcode 8 while iOS 7-9 uses Xcode 9.  You need to switch between the Xcode versions using xcode-select and then launch the tests.

**Comment by saikrishna321** [comment]
@brtu thats a must have feature as part of framework, glad to accept PR on this. How are you providing the deviceId's ?

**Comment by brtu** [comment]
@saikrishna321 

In our CI system we pass in the device ids through the maven command as an environment variable of comma separated IDs, i.e. mvn -Dtest=runner test -Dudid=deviceId1,deviceId2,deviceId3

In our Runner class we read and parse the device id param and pass it as a parameter into the ParallelThread class, which then sets a list field of valid device ids in the Android deviceConf and iosDevice configuration classes.
(https://github.com/brtu/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/ParallelThread.java#L56)

When we retrieve the list of connected devices using the configuration classes, we only record device ids that were part of the parameter into the device list, (https://github.com/brtu/AppiumTestDistribution/blob/master/src/main/java/com/appium/ios/IOSDeviceConfiguration.java#L67)

Yes, I will clean it up and create a pull request for this feature and see if you guys like it. 👍

**Comment by saikrishna321** [comment]
@brtu 

>i.e. mvn -Dtest=runner test -Dudid=deviceId1,deviceId2,deviceId3

We should be able to fetch the deviceId's from config file, when there are changes in the device list we need make changes to CI back to back. Thoughts?

> Yes, I will clean it up and create a pull request for this feature and see if you guys like it.

For sure we are looking to have such a feature as part of this framework, which helps running not only IOS tests across iOS10/9 device, but also android.( CI-usecase: 2 slave running on mac mini and 10 devices connected to the host machine, we need to send set of 5 devices to run on slave-1 and other set to slave-2 with different test set) 

>When we retrieve the list of connected devices using the configuration classes, we only record device ids that were part of the parameter into the device list, 

So this check needs to be done on android as well. 

@hariharanwebmail @anandbagmar @SrinivasanTarget Thoughts ?

**Comment by brtu** [comment]
@saikrishna321 

> We should be able to fetch the deviceId's from config file, when there are changes in the device list we need make changes to CI back to back. Thoughts?
I think it is easier to pass in via command line parameter because sometimes I need to change the device list depending on what tests need to be run, and editing the config.properties file for different device lists during runtime may be "bad practice".

> So this check needs to be done on android as well.
Yes, I do this check for both iOS and Android.

**Comment by saikrishna321** [comment]
Perfect, looking forward for a PR on this

**Comment by anandbagmar** [comment]
Having an ability to provide information via environment variables, or command line properties when running the tests is very powerful. You do not want to keep updating config files with test runtime / execution time data. Keep Test execution config separate from Test execution data - will help in the long run.

Now - if certain information is missing - there are 2 ways of responding - either fall back to some 'decent' defaults, or 'throw meaningful exceptions' about the missing data. I prefer the latter approach as there is more explicit understanding and control of what is expected to happen.

**Comment by saikrishna321** [comment]
@brtu any updates on the PR ?

**Comment by brtu** [comment]
@saikrishna321 Sorry was pretty busy with work this past week.  I have a PR ready for review @ https://github.com/saikrishna321/AppiumTestDistribution/pull/158

I added the ability to pass in a list of device udids in the test runner.  The user can get this list from the environment variables or hardcode it or parse it from a properties file, whichever they prefer.  Also fixed some other small miscellaneous issues like removing a static keyword, spelling mistakes, extra spaces, etc.

**Comment by saikrishna321** [comment]
@brtu thanks for that.. I have some feedbacks on the PR. Pls review the PR https://github.com/saikrishna321/AppiumTestDistribution/pull/158

**Comment by saikrishna321** [comment]
@anandbagmar @priyankshah217 its on master now 

```
command to start runner
mvn clean -Dtest=RunnerCukes test -Dudid=udid1,udid2,udid3

Example test runner

public class RunnerCukes {
    @Test 
    public void testCukesRunner() throws Exception {
        String udidParam = System.getProperty("udid");
        String[] parts = udidParam.split(",");
    	List<String> deviceList = Arrays.asList(parts);
    	ParallelThread cucumberParallelThread = new ParallelThread(deviceList);
        boolean hasFailures = cucumberParallelThread.runner("output");
        Assert.assertFalse(hasFailures, "Testcases have failed in parallel execution");
    }
}
```
