### ISSUE TITLE
Cannot run tests from IntelliJ IDE while tests run from cli

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#153]
When I try to run a test from IntelliJ i get error, while the same tests run successfully when started from terminal. The error I get is [here](https://gist.github.com/RatkoD/f298ae3795343131e69e82462f26e487).

**Comment by saikrishna321** [comment]
@RatkoD you need to trigger the Runner class

**Comment by RatkoD** [comment]
You want to say that I need to run entire runner and cannot run just one test?

**Comment by saikrishna321** [comment]
@RatkoD if you want to run a single test for debugging just extend it to your BaseTest which will have appium instance creation.

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/PageObjectPatternAppium/blob/master/src/test/java/com/appium/config/Utils.java
