### ISSUE TITLE
Tags name needs to be added in cucumber extent report

### ISSUE THREAD

**Issue by priyankshah217** [saikrishna321/AppiumTestDistribution#154]
As per our requirement, we need to include tags name as a part of cucumber extent report. Will you please consider this as an enhancement in subsequent release?

**Comment by saikrishna321** [comment]
@priyankshah217 can you try with the below 

```
	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>56f98e6ac1</version>
	</dependency>
```

**Comment by priyankshah217** [comment]
@saikrishna321 , I am able to see tags in cucumber report, so closing this issue.
