### ISSUE TITLE
Tests on iOS sometimes stop working for no apparent reason

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#159]
I have one iOS device connected and I get this error:

> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> Running com.appium.tests.runners.RunnerHeroLogin
> Configuring TestNG with: TestNG652Configurator
>                             _  _        _ 
>  _ __    __ _  _ __   __ _ | || |  ___ | |
> | '_ \  / _` || '__| / _` || || | / _ \| |
> | |_) || (_| || |   | (_| || || ||  __/| |
> | .__/  \__,_||_|    \__,_||_||_| \___||_|
> |_|                                       
> 
> creating directory: Logs
> No Device Connected
> a55460712308b368e035ad4b61d065460f8966eb
> 
> /usr/local/lib/node_modules/appium/build/lib
> iOSWebKitProxyLauncher File already has access to execute
> IOS a55460712308b368e035ad4b61d065460f8966eb Directory is created!
> IOS 48e0ad307bb7bac9cb0a5a0eeb027d19ceac005d Directory is created!
> ***************************************************
> 
> Total Number of devices detected::2
> 
> ***************************************************
> 
> starting running tests in threads
> Adding iOS devices
> No Device Connected
> {a55460712308b368e035ad4b61d065460f8966eb=true}
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.299 sec <<< FAILURE! - in com.appium.tests.runners.RunnerHeroLogin
> testApp(com.appium.tests.runners.RunnerHeroLogin)  Time elapsed: 3.696 sec  <<< FAILURE!
> java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
> 	at java.util.ArrayList.get(ArrayList.java:429)
> 	at com.appium.executor.MyTestExecutor.constructXmlSuiteForParallel(MyTestExecutor.java:174)
> 	at com.appium.executor.MyTestExecutor.runMethodParallelAppium(MyTestExecutor.java:128)
> 	at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:135)
> 	at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:60)
> 	at com.appium.manager.ParallelThread.runner(ParallelThread.java:52)
> 	at com.appium.tests.runners.RunnerHeroLogin.testApp(RunnerHeroLogin.java:15)

If I connect Android device, the tests are running with the same config. This happens quite often, just an hour ago, I was able to run tests on iOS and Android, not at the same time, but now I've tried to run tests on both devices, and first got this error, then disconnected the Android, still the same, disconnected the iOS and connected the Android and it started working.

**Comment by RatkoD** [comment]
While I was submitting this issue, the framework healed it self. Now detected only one ios device and started working.

**Comment by saikrishna321** [comment]
I see idevice is picking cached devices, but I remember we changed to system profiler to pick the devices. let me check abt this on Monday

**Comment by saikrishna321** [comment]
@RatkoD changed the implementation to pick device using system profiler. Please open new issue if it exists
