### ISSUE TITLE
Getting some unknown error and execution gets stuck on it, doesn't move further (Branch :parallel_ios)

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#16]
Hi Sai, I am using your framework (branch:parallel_os) with sample iOS apps "UICatalog.app" but even with this sample apps i am getting same error that i get with our company apps. can you please help 

![screen shot 2016-02-18 at 9 02 17 pm](https://cloud.githubusercontent.com/assets/12589206/13165428/2b7e420a-d683-11e5-8bbf-115a9068d675.png)

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Sai, PFB attached project in which i have used sample iOS apps UICatalog.app, if you run this in eclipse you will notice above mentioned error once you are on @Beforemethod 2nd time. 

[AppiumTestDistribution-parallel_ios.zip](https://github.com/saikrishna321/AppiumTestDistribution/files/137431/AppiumTestDistribution-parallel_ios.zip)

Thanks.
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara can you please try with the latest version and test it ..
