### ISSUE TITLE
Appium server instance gets spawned for each tag in feature file

### ISSUE THREAD

**Issue by brtu** [saikrishna321/AppiumTestDistribution#160]
Hi Sai,

I think there is a bug with a recent commit, https://github.com/saikrishna321/AppiumTestDistribution/commit/393b01779a93f72fac8bfbeb6ac905b51966f118

At https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/cucumber/listener/ExtentCucumberFormatter.java#L173

there is an appium server that is getting spawned for each tag within a feature file.

My feature file has multiple tags like @smoke @regression @fullsmoke etc.  This part is getting all of the feature's tags and spawning an appium server for each one.  What was the reasoning behind doing that?

**Comment by saikrishna321** [comment]
appium server starting for every tag is a defect .... we are just starting server node for every feature file, similar to testNG before Class

**Comment by brtu** [comment]
Made a bug fix here in the latest PR:

https://github.com/saikrishna321/AppiumTestDistribution/pull/158

**Comment by saikrishna321** [comment]
@brtu i have merged the changes, with extent-version 3.0.1 there is defect https://github.com/anshooarora/extentreports-java/issues/757

So i will revert to v 3.0.0 till this fixes and this also blocks the  tag been added to report

**Comment by brtu** [comment]
@saikrishna321 Ah.. I see.  I did not notice that bug in 3.0.1

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/pull/157
