### ISSUE TITLE
Android UiAutomator2 not working for devices in parallel

### ISSUE THREAD

**Issue by brtu** [saikrishna321/AppiumTestDistribution#162]
Using the new UiAutomator2 included in Appium 1.6.3, I am unable to run tests on Android devices in parallel.  I am able to run tests one at a time, but not with two devices at once.  UiAutomator2 installs a server on the device and communicates with it.  I think the client/server ports are getting confused somewhere.

**Comment by brtu** [comment]
Bug is actually with Appium here:

https://github.com/appium/appium/issues/7745

Specifying a systemport capability allows it to work.

**Comment by saikrishna321** [comment]
@brtu this needs to be added to the FAQ
