### ISSUE TITLE
Cucumber - passing in desired capabilities bug

### ISSUE THREAD

**Issue by brtu** [saikrishna321/AppiumTestDistribution#163]
There's a bug with the PR I made with passing in desired caps with Cucumber.  I thought before that you could specify the caps in the @before method of the steps file, but that method actually gets executed after the Appium server instance is already created.  There needs to be another entry point where the user can specify the caps and pass it into the AppiumTestDistribution library.

**Comment by saikrishna321** [comment]
@brtu i have this fixed on master, can you give it a try... you can send desired caps from json file
create a folder caps -> android.json

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/blob/master/caps/capabilities.json

can pass capabilities from json file.
