### ISSUE TITLE
Class Cast Exception

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#168]
With the latest release i get the following error, only on iOS devices:
```
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.MobileElement
```

**Comment by saikrishna321** [comment]
@RatkoD can you try outside the framework. Looks like java-client issue

**Comment by saikrishna321** [comment]
https://discuss.appium.io/t/ios-android-driver-casting-on-a-shared-test-code-base/1095

**Comment by RatkoD** [comment]
Hey @saikrishna321, can you help me a bit more? I don't quite get what I need to do.
