### ISSUE TITLE
Wrong print of comparison results

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#169]
Since a while, every time when I do comparison of text I get the wrong print of the expected and actual result. For example, in my test I expect "Not found" and I get "Username is not found" but in the log i have the opposite result
```
org.junit.ComparisonFailure: expected:<[Username is n]ot found.> but was:<[N]ot found.>
```

Here is my test:
```
	@Test(priority = 55, description = "Login attempt with email tha is not in the database")
	@Author(name = "Ratko")
	public void loginWithUserNotInDBFail() throws InterruptedException {
		emailPage = new EmailPage(driver);
		credentials = new UserCredentials("nobody@nowhere.com", "P@ssw0rd", "223305");

		getToEmailScreenIfNot();
		emailPage.clearPrepopulated();
		emailPage.enterEmailAndHideKeyboard(credentials.getUserName());
		emailPage.nextButton();
		emailPage.waitForEmailPageToLoad();
		Assert.assertEquals(emailPage.verifyUserNotFound(), "Not found.");
	}
```
Here is a [pic](https://i.imgur.com/2NgXq4L.png) from the report.

Also, there are som strange []

**Comment by saikrishna321** [comment]
@RatkoD not sure how come you have junit assertions, this framework supports TestNG 

Assert.assertEquals(actual:"sai", expected:"sai k");

Results:

java.lang.AssertionError: expected [sai k] but found [sai]
Expected :sai k
Actual   :sai

Check with TestNG assertions. It works fine

**Comment by RatkoD** [comment]
Thanks @saikrishna321 !
