### ISSUE TITLE
The desired capabilities must include either an app, appPackage or browserName

### ISSUE THREAD

**Issue by test666qa** [saikrishna321/AppiumTestDistribution#171]
In some test scenarios I'm trying to open the device ( Android ) settings , sending capabilities without an APP (capability) !! & it's return an error : 
"The desired capabilities must include either an app, appPackage or browserName" 
My capabilities : 

public synchronized DesiredCapabilities androidcapabilities() {
        System.out.println("Setting Android Desired Capabilities:");
        DesiredCapabilities androidCapabilities = new DesiredCapabilities();
        androidCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android");
        androidCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "5.X");
        androidCapabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY,  "com.android.settings.Settings");
        androidCapabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE,"com.android.settings");
    
        androidCapabilities.setCapability(MobileCapabilityType.NO_RESET,"true");
        androidCapabilities.setCapability("browserName", "");
        androidCapabilities.setCapability(MobileCapabilityType.UDID, device_udid);
        return androidCapabilities;
    }
}
How can i deal with it , any solutions ? 
Thanks ,

**Comment by saikrishna321** [comment]
@test666qa this is something to deal with appium and should b raised under appium repo. With the latest appium server you should not get this error. Pls try with the latest version and also make sure you provide the server logs that would help.
