### ISSUE TITLE
TestNG XML file throws parsing exception when being read

### ISSUE THREAD

**Issue by brtu** [saikrishna321/AppiumTestDistribution#172]
https://github.com/cbeust/testng/issues/1385

TestNG changed its DTD and it is now present in a redirect which Xerces can't read.  They suggest using a different DTD resolver or using an ISuiteListener to get the values from the XML file.

**Comment by saikrishna321** [comment]
@brtu you got it working ?

**Comment by brtu** [comment]
@saikrishna321 The guys over at TestNG fixed the URL redirect so I think this is no longer a problem.  Closing this issue.
