### ISSUE TITLE
Can I use AppiumTestDistribution with SeleniumGrid

### ISSUE THREAD

**Issue by xingxing888** [saikrishna321/AppiumTestDistribution#173]
Hello! I love AppiumTestDistribution a lot and think it's a great idea. Thank you for your work! It's perfectly fine with local multiple simulators. However, in my project I want to run the test against multiple emulators both locally and remotely. I wonder how should I do that. Thank you!

**Comment by saikrishna321** [comment]
@xingxing888 
>  I love AppiumTestDistribution a lot and think it's a great idea 
Thanks, glad that this framework is helping you. Remotely  we cannot run the tests with this framework.

**Comment by sunyujiang** [comment]
Hi, it's really thanks for your work! one request about the caps/android.json and IOSs' format, could you help provide this file format? thanks a lot, my mail is sun-yujiang@163.com

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/PageObjectPatternAppium/blob/master/caps/android.json
