### ISSUE TITLE
unable to run test on windows

### ISSUE THREAD

**Issue by aloksingh15** [saikrishna321/AppiumTestDistribution#176]
Hi, 
I followed all the instructions given to use your framework for appium test. I have just changed the package name.
I am unable to run test.
[errorlog.txt](https://github.com/saikrishna321/AppiumTestDistribution/files/918827/errorlog.txt)

**Comment by saikrishna321** [comment]
@aloksingh15 Feature directory is not present.Make sure you the features inside resources folder

**Comment by saikrishna321** [comment]
closing as Inactive
