### ISSUE TITLE
Does AppiumTestDistribution support running test on multiple iOS devices running on older platform versions, that require UiAutomation?

### ISSUE THREAD

**Issue by alexander-poulikakos** [saikrishna321/AppiumTestDistribution#179]
How can I use this framework to run tests on iOS devices with older platform versions, that requires UiAutomation to be used (NOT XCUITest)?

**Comment by saikrishna321** [comment]
@alexander-poulikakos this framework supports running tests across ios devices. It really does not matter if its XCUI or UIAutomation, it depends on the caps you send

**Comment by alexander-poulikakos** [comment]
According to [this](https://github.com/appium/appium/issues/7373) Appium kills all instruments processes, which is only solved in xcuitest.

How are you dealing with the "Kill instruments" that appium sends occasionally (when something goes wrong)?

**Comment by saikrishna321** [comment]
@alexander-poulikakos we are not dealing anything explicitly.
