### ISSUE TITLE
Failed to execute test in iOS devices with version 10.x.x

### ISSUE THREAD

**Issue by benz-philip** [saikrishna321/AppiumTestDistribution#189]
Tested by using latest refactor build, Found that, the test executes in iOS device with os version 9.x. But failed to start run/install app in iOS device with version 10.x. 

Gets the below error while triggering cucumber test.
![screen shot 2017-05-17 at 9 29 43 am](https://cloud.githubusercontent.com/assets/18724283/26139702/a2cf2d40-3ae3-11e7-9741-cba3bdc11591.png)
![screen shot 2017-05-17 at 9 30 02 am](https://cloud.githubusercontent.com/assets/18724283/26139707/a7c01f3a-3ae3-11e7-9626-b814b3778069.png)

**Comment by saikrishna321** [comment]
@benz-philip can you pls try with the latest master commit version
