### ISSUE TITLE
Need to add listener in testing.xml programmatically, like com.test.ios classes are getting added in testing.xml

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#19]
Hi Sai, we need to handle multiple failure and for that we have implemented listener extending IInvokedMethodListener interface and implementing afterInvocation method.

so when we run the project thru maven it creates the testng.xml programmatically but it doesn’t add the listener in it

so if it doesn’t add the listener in testng.xml how implemented listner will invoked.

**Comment by saikrishna321** [comment]
3c2d219 

You can add all yours listeners in the config.properties as below 

```
LISTENERS=com.test,com.test1
```

Your testng.xml will look as below

```
<suite thread-count="3" verbose="2" name="TestNG Forum" parallel="tests">
  <listeners>
    <listener class-name="com.test"/>
    <listener class-name="com.test1"/>
  </listeners>
  <test name="TestNG Test0" preserve-order="false">
    <classes>
      <class name="com.test.site.HomePageTest3"/>
      <class name="com.test.site.HomePageTest2"/>
      <class name="com.test.site.HomePageTest1"/>
      <class name="com.test.site.HomePageTest6"/>
      <class name="com.test.site.HomePageTest5"/>
      <class name="com.test.site.HomePageTest4"/>
    </classes>
  </test> <!-- TestNG Test0 -->
  <test name="TestNG Test1" preserve-order="false">
    <classes>
      <class name="com.test.site.HomePageTest3"/>
      <class name="com.test.site.HomePageTest2"/>
      <class name="com.test.site.HomePageTest1"/>
      <class name="com.test.site.HomePageTest6"/>
      <class name="com.test.site.HomePageTest5"/>
      <class name="com.test.site.HomePageTest4"/>
    </classes>
  </test> <!-- TestNG Test1 -->
  <test name="TestNG Test2" preserve-order="false">
    <classes>
      <class name="com.test.site.HomePageTest3"/>
      <class name="com.test.site.HomePageTest2"/>
      <class name="com.test.site.HomePageTest1"/>
      <class name="com.test.site.HomePageTest6"/>
      <class name="com.test.site.HomePageTest5"/>
      <class name="com.test.site.HomePageTest4"/>
    </classes>
  </test> <!-- TestNG Test2 -->
</suite> <!-- TestNG Forum -->
```

**Comment by VinitSandesara** [comment]
Thanks much Sai, i will give it a try and will close after that.

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Yes Sai, it is working as expected i have confirmed the changes, Again thank you so much for your help on this. Closing the issue as it is resolved now.

Thanks
Vinit

**Comment by Subrahmanyam83** [comment]
Hi.. Which config.properties are we talking about here. Could somebody please let me know. I am creating listeners like this, but listeners are not shown in the testng.xml:

//Create an instance on TestNG
        TestNG myTestNG = new TestNG();

        /*Adding Listeners*/
        TestListenerAdapter tla = new TestListenerAdapter();
        List<Class> listenerClasses = new ArrayList<Class>()
        listenerClasses.add(Utilities.Class.BaseSpec.class);
        myTestNG.setUseDefaultListeners(true);
        myTestNG.addListener(tla);

Please let me know how to add "Utilities.Class.BaseSpec" as a listener.

**Comment by saikrishna321** [comment]
You don't have to add it to XML file .... The framework takes care when you have LISTENERS=com.listener.test

Are your using AppiumTestDistribution to run tests ?

**Comment by Subrahmanyam83** [comment]
No.. I am using Geb using gradle. Where exactly does this configuration
needs to be given :
LISTENERS=com.listener.test

**Comment by sachinahuja90** [comment]
Hi Vinit,

Could you please share the exact code to add Listeners in TestNG.xml programmatically.

I am using Selenium and want to create testNG.xml as run time which would include Listeners.

<?xml version="1.0" encoding="UTF-8" ?>	
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">	
 	<suite name="Suite">	
	<listeners>
		<listener class-name="TestListener"/>
	</listeners> 
 
		<test name="Regression Test Suite">	
			<groups>	
				<run>	
   					 <include name="Group1" />	
					 <include name="Group2" />	
        		</run>	
       		</groups>	
               <packages>
                   	<package name="testcases.*"/>
               </packages>
	</test>	
  </suite>
