### ISSUE TITLE
How can I run the testng test in this project in debug mode?

### ISSUE THREAD

**Issue by hemano** [saikrishna321/AppiumTestDistribution#195]
Can you share the testng suit xml ?

**Comment by saikrishna321** [comment]
can u pls be more specific I'm not getting it right sorry..

**Comment by hemano** [comment]
Apologies for being not clear..

I was trying to get the below testng suit to execute a specific test in debug mode. It works for me now, hence can mark it resolved.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="1" verbose="2" name="TestNG Forum" parallel="classes">
    <listeners>
        <listener class-name="com.appium.manager.AppiumParallelTestListener"/>
        <listener class-name="com.appium.utils.RetryListener"/>
    </listeners>
    <test name="TestNG Test">
        <parameter name="device" value="FAAZCY04U491"/>
        <groups>
            
            
            
        </groups>
        <classes>
            <class name="com.appium.tests.smokeTest"/>
        </classes>
    </test> 
</suite>
