### ISSUE TITLE
Is it possible to execute same test in parallel, on different devices with different app versions?

### ISSUE THREAD

**Issue by hemano** [saikrishna321/AppiumTestDistribution#196]
Is it possible to execute same test in parallel on different devices with different app versions?

I tried below android config, but find that it picks the app specified in first set only.

[
  {
    "platformName": "android",
    "platformVersion": "7.0",
    "app": "./build/xyz.apk",
    "appPackage":"com.asdf.od.app",
    "appActivity": "com.asdf.od.app.activity.SplashScreenActivity",
    "deviceName": "android",
    "noSign":true,
    "udid": "FAAZCY04U491"
  },

  {
    "platformName": "android",
    "platformVersion": "7.0",
    "app": "./build/qweq.apk",
    "appPackage":"com.asdf.od.app",
    "appActivity": "com.asdf.od.app.activity.SplashScreenActivity",
    "deviceName": "android",
    "noSign":true,
    "udid": "18158056"
  }
]

**Comment by saikrishna321** [comment]
@hemano we can run the same application in parallel on multiple devices, but not multiple applications in parallel. If you want to run multiple applications in parallel then you should allocate the devices to the test runner. 

For Ex: 
Application-1 runs on Device1 Device2 Device 3 
Application-2 runs on Device4 Device5

This is possible

**Comment by hemano** [comment]
@saikrishna321 Thanks Sai. Closing the issue..
