### ISSUE TITLE
Parallel Testing support for CI

### ISSUE THREAD

**Issue by jimmy9gag** [saikrishna321/AppiumTestDistribution#20]
Hey @saikrishna321, I'm currently looking into your framework and trying to find a way to integrate the parallel testing for Android with the CI to increase the efficiently in delivery pipeline of the product. Or i'm even thinking of running a local server in the office to make this happen. 

Before i start going through the framework, i just wanted to check if you have any ideas or implementations already that i may have missed.

**Comment by jimmy9gag** [comment]
I am thinking of simply adding one line in the config.properties file to write the IP address of the host server, and one more line for a flag to turn on and off the REMOTE_TESTING_MODE. And just before the AppiumParallelTest is initialized (before it calls 'adb' to get the device IDs), open a simple web socket server that waits for a trigger. And then after the test run is finished in the CI or the remote server, allow the remote server to send the html report file back to the client.

would this be a reasonable implementation, what do you think?

thanks,
Kim

**Comment by saikrishna321** [comment]
@jimmy9gag i don't really see any changes required when running your tests on CI pipeline as all the android devices will be hooked to the slave and the slave will trigger the test across the devices.

I didn't get your second comment about web socket server ? Can you pls elaborate on that

**Comment by jimmy9gag** [comment]
@saikrishna321 Oh, sorry for being unclear. The ultimate goal that i want to do is to make the test run on both local and remote servers. But after reading what you said, I guess i don't have to change anything!

Can you please elaborate more on how to setup the "hooked to the slave and the slave will trigger the test"? The slave would be the macbook i use currently, so my question is how would i run "mvn -Dtest=Runner test" from the CI to trigger my macbook?

sorry if this is confusing.... thanks again for the reply :+1:

**Comment by jimmy9gag** [comment]
So for example, xCode has a xCode server that could be integrated with the repositories. So whenever a teammate makes some changes to the iOS app and makes a commit to the master branch, it triggers a tests in the xCode Server. So what I'm trying to do is same with Android.

I know there are few discussions in the appium discussion about Appium Remote Server. Just run the appium server, and put the remote server IP address for capablities and create a Remote Web Driver (ex: driver = new RemoteWebDriver(new Uri("http://123.20.38.134:4723/wd/hub"), capabilities)) 

I'm thinking if this is possible for this parallel library as well!

Sorry for the long comments :(

**Comment by jimmy9gag** [comment]
got it working! 👍

**Comment by saikrishna321** [comment]
@jimmy9gag do give some info on how you got this worked or a PR would help :)
