### ISSUE TITLE
Support iOS Safari test  

### ISSUE THREAD

**Issue by saikrishna321** [saikrishna321/AppiumTestDistribution#203]

**Comment by hemano** [comment]
@saikrishna321 Can I help in implementing it?

**Comment by saikrishna321** [comment]
@hemano Happy for it 👍 Please go ahead... there is code for ios safari real device testing but haven't tested it completly.

**Comment by hemano** [comment]
Ok, I'll search for it.

**Comment by hemano** [comment]
@saikrishna321 Currently, I'm able to execute iOS Safari browser tests on a Simulator.

If I understand correctly, you wouldn't want the user to change capabilities.json file to execute browsers tests.
Instead, should I make use of BROWSER_TYPE AND APP_TYPE properties of config.properties as follows? And create the DesiredCapability object reading these properties values?
```
BROWSER_TYPE=safari
APP_TYPE=web 

```
I'll go ahead according to the feedback.

Once the simulator Safari tests work fine then we can think about real devices.
Following discussion and blog can help us achieve it.
https://discuss.appium.io/t/mobile-web-automation-on-ios-real-device-safari/4900/40
https://bernardlago.blogspot.in/2016/02/running-automated-tests-against-mobile.html

**Comment by saikrishna321** [comment]
@hemano we no more use _BROWSER_TYPE=safari APP_TYPE=web_ from config.properties, we pick it from capabilities.json. 

FYI, as i mentioned above the code was implemented but not tested... I got time to test the code on my CI and real device Safari tests work well on multiple devices. 

Safari simulators won't work on parallel as its a Apple bug.

**Comment by hemano** [comment]
Thanks for the update. So can we close this issue? If not then can I look into the gap keeping us closing this issue? Or would you like me to update the ReadMe for this?

**Comment by saikrishna321** [comment]
Yah we can close this... Sure you can update the readme

**Comment by hemano** [comment]
@saikrishna321 
Could you please review it and add it to your wiki pages?

https://github.com/hemano/AppiumTestDistribution/wiki/Configurations-for-iOS-Safari-browser-test-run
