### ISSUE TITLE
If a test passes in the retry, even the failed test is reported.

### ISSUE THREAD

**Issue by shridharkalagi** [saikrishna321/AppiumTestDistribution#204]
If a test fails in the first run and passes in the second run, both the first (failure) and second runs (pass) are logged in the report. 
However, if the test passes in the retry, failure shouldn't be logged. 

Saw this issue while running tests on Android Chrome with MAX_RETRY_COUNT =1

**Comment by SrinivasanTarget** [comment]
Great Start @shridharkalagi
