### ISSUE TITLE
Run test across simulator and devices in parallel

### ISSUE THREAD

**Issue by saikrishna321** [saikrishna321/AppiumTestDistribution#216]
with xcode-9 beta we can run parallel simulators and the framework should also be possible to run tests across iOS Simulators and Real Devices at the same time. 

- [X] Accept array of application .app and .ipa
- [X] Trigger tests across simulators and devices in parallel

**Comment by saikrishna321** [comment]
```
[
  {
    "android": {
      "platformName": "android",
      "noSign": true,
      "deviceName": "android",
      "app": "/Users/saikrisv/Documents/VodQaAdvancedAppium/VodQA.apk"
    }
  },
  {
    "iOS": {
      "platformName": "iOS",
      "app": {
        "device": "./VodQAReactNative.ips",
        "simulator": "./VodQAReactNative.zip"
      },
      "wdaLaunchTimeout": "80000",
      "wdaConnectionTimeout": "80000",
      "preventWDAAttachments": true,
      "clearSystemFiles": true,
      "shouldUseSingletonTestManager": false,
      "simpleIsVisibleCheck": true,
      "maxTypingFrequency": 10,
      "isHeadless": false,
      "fullReset": false
    }
  },
  {
    "simulators": [
      {
        "deviceName": "iPhone 6",
        "OS": "11.0"
      },
      {
        "deviceName": "iPhone 6s",
        "OS": "11.0"
      }
    ]
  }
]
```

**Comment by saikrishna321** [comment]
@SrinivasanTarget yet to test the same

**Comment by hemano** [comment]
Is the condition, appium 1.6.6.beta latest with xcode-9 beta  necessary for iOS simulator executions?

**Comment by SrinivasanTarget** [comment]
> Is the condition, appium 1.6.6.beta latest with xcode-9 beta necessary for iOS simulator executions?

@hemano Yes it is necessary to execute a test in multiple sim's parallely

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/pull/217
