### ISSUE TITLE
Less time consumption while developing Test Cases

### ISSUE THREAD

**Issue by rahul-bhiwagade** [saikrishna321/AppiumTestDistribution#218]
While I am in the process of developing test case, each time framework starts appium server for the devices connected then start running tests.

At the time of developing you need to run multiple times and above process is very time consuming. 
Is there easy way around ???

**Comment by saikrishna321** [comment]
@rahul-bhiwagade you need to have Util.java(https://github.com/saikrishna321/PageObjectPatternAppium/blob/master/src/test/java/com/appium/config/Utils.java) and extend your Test under dev.

In next release we will have support to handle single appium server to handle multiple drivers. This will help solve more time on server start for each device
