### ISSUE TITLE
All test methods under class in report doesn't look good, need something like when you click on test method it expand and collapse 

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#22]
Hi Sai, Can you please make the modification in your framework for the extentReport, rightnow in report when you click on Class name it shows all the Test method in one go (including pass, fail, appium log, failure reason, and screenshot).

In below Screenshot you can see Class which ran on device which has been assigned under the device category as expected and looks good

![screen shot 2016-03-12 at 10 15 55 pm](https://cloud.githubusercontent.com/assets/12589206/13726924/0ba37604-e8a2-11e5-8a34-4ba3fb92fa77.png)

In below screenshot you can see when you click on class name it shows all the test methods including all the details which doesn't looks good, instead if you can make it like a way when you click on Class name it gives all the Test method and when you click on Test method it expand with result like Logs, screenshot, StackTrace etc. 

![alltest](https://cloud.githubusercontent.com/assets/12589206/13726925/0fb324c4-e8a2-11e5-90a1-1e004b9d7654.png)

If it can be change as below which looks neat and clean to the end user.

![screen shot 2016-03-12 at 10 33 23 pm](https://cloud.githubusercontent.com/assets/12589206/13726930/7a478a78-e8a2-11e5-8d8d-e51ca45f9bd2.png)

![screen shot 2016-03-12 at 10 39 10 pm](https://cloud.githubusercontent.com/assets/12589206/13726943/51e8bad8-e8a3-11e5-8f4d-2de89bb47990.png)

Thanks
Vinit

**Comment by saikrishna321** [comment]
Looks good :-) Pull request is most welcome for this :-)

**Comment by saikrishna321** [comment]
@VinitSandesara i have implemented this  please take a look 430668c635d882b1ba1cfe88057ece490cd23d54

![screen shot 2016-03-16 at 1 07 53 pm](https://cloud.githubusercontent.com/assets/4045041/13805738/1096fc84-eb7d-11e5-8d11-d5cb99c69a08.png)

<img width="1435" alt="screen shot 2016-03-16 at 5 58 23 am" src="https://cloud.githubusercontent.com/assets/4045041/13805741/142a6e1c-eb7d-11e5-804d-1000554eaced.png">

**Comment by VinitSandesara** [comment]
Hi Sai, First of all Thank you so much for your valuable time to make this enhancement in framework, i have tested it and it is working like a charm however i have noticed with Retry it is not grouping in same test method, PFB screenshot in which you can see there are 2 methods among one pass and one failed, failed one has Retry on it "InvalidSearchKeyword" which is not grouping in "InvalidSearchKeyword"

![screen shot 2016-03-16 at 3 28 31 pm](https://cloud.githubusercontent.com/assets/12589206/13827893/dedbc7e6-eb8c-11e5-93b8-7ff67aaffa95.png)

Thanks
Vinit
