### ISSUE TITLE
Question: Distributed Tests across multiple mac machines.

### ISSUE THREAD

**Issue by reach2jeyan** [saikrishna321/AppiumTestDistribution#225]
I am having a fully fledged suite for automated tests written using ruby with Appium for mobile automation.

I am running these suites in one simulator in one machine and it takes up a lot of time, around 1 hour to run 56 test cases(We have system test cases where multiple checks like database/Api/functional are integrated). We have more additional test cases adding to our way.

We are trying to implement faster feedback for the developers and testing team here and will want to distribute the tests across 3 machines.

Does iOS support it? Do you have a link or a material to support me in designing this? I had seen the parallel testing frameworks online, but I don't think, I would want 1 test cases to run on multiple devices requirement.

**Comment by saikrishna321** [comment]
@reach2jeyan why on multiple mac machines? Why not on same machine?

**Comment by reach2jeyan** [comment]
@saikrishna321 I am using Appium with xcode 8.2. It had been mentioned across that either of them do not support more than one simulator per session. 

By running on same machines, do you mean creating multiple users on the same machine? I am sorry, I have very little idea on the same. I would be glad if you could guide

**Comment by saikrishna321** [comment]
@reach2jeyan update your xcode version to 9 which has been release and it supports parallel simulator in the same macHost and you dont need multiple accounts. This framework supports that 

https://www.youtube.com/watch?v=sf0YARF5ppQ

**Comment by reach2jeyan** [comment]
Thanks! By Parallel tests, do you mean running same tests on different simulators at same time? or different tests running on multiple simulator at the same time?

**Comment by saikrishna321** [comment]
Both, when you set the Runner=parallel it runs same test case in all devices, when you set the Runner=distribute then it runs different test on different devices.....

**Comment by reach2jeyan** [comment]
@saikrishna321 Thanks! I am using Ruby+cucumber for my tests and I do not have a runner class and the config file that you have mentioned in your framework. 

Do you have a plugin that supports ruby tests? or does this work if the `config` file is written as a `.yml` file in my tests?

**Comment by saikrishna321** [comment]
@reach2jeyan no this framework supports only java ... 

>Do you have a plugin that supports ruby tests?

Nope

**Comment by reach2jeyan** [comment]
@saikrishna321 Okay! Thank you....
