### ISSUE TITLE
Question : Continues script execution 

### ISSUE THREAD

**Issue by Kanchu8** [saikrishna321/AppiumTestDistribution#239]
Hi Sai,

In Runner if we add 2 test script for parallel execution like .......

  tests.add("HomePageTest2");
  tests.add("HomePageTest1");

then is it excuse one after another or new session will get created for second script..?

I want my scripts to run one after another in parallel execution..but after first test case app get closed and new session started for second script?

**Comment by saikrishna321** [comment]
@Kanchu8 After every test we create a new session, to have clean state on new test case ...
