### ISSUE TITLE
Parent child relationship is NOT getting maintained when there is a Retry with Test method

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#24]
Hi Sai, This issue is similar to "https://github.com/saikrishna321/AppiumTestDistribution/issues/22" (Thank you so much for the enhancement you have made for this issue) but instead of reopening closed issue i have created new one, 

i have noticed with Retry it is not grouping in same test method, PFB screenshot in which you can see there are 2 methods among one pass and one failed, failed one has Retry on it "InvalidSearchKeyword" which is not grouping in "InvalidSearchKeyword"

![screen shot 2016-03-16 at 3 28 31 pm](https://cloud.githubusercontent.com/assets/12589206/13827893/dedbc7e6-eb8c-11e5-93b8-7ff67aaffa95.png)

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara its of different state skip/ fail and at the same time, number of retry count should hold number of child objects ..... so we cant put skip and fail into the same child node.
