### ISSUE TITLE
Support for klov server

### ISSUE THREAD

**Issue by karthikbhatnagar** [saikrishna321/AppiumTestDistribution#254]
Hi Sai

Are you planning to add support for klov server?

ExtentX is depreciated by the owner and klov will replace or already has.  I am using it for past few days and able to confirm its very stable and much faster..

**Comment by SrinivasanTarget** [comment]
@karthikbhatnagar Would you like to raise a PR?

**Comment by karthikbhatnagar** [comment]
for those who are lookingfor the server:

project url  https://github.com/anshooarora/klov
demo  http://klov.herokuapp.com

i will send in a pr soon

**Comment by karthikbhatnagar** [comment]
@anshooarora please chime in if required.

**Comment by saikrishna321** [comment]
@karthikbhatnagar any updates ? if not  i will start working on this

**Comment by saikrishna321** [comment]
@karthikbhatnagar implementation is part of klov branch 

give it a try 

```
	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>klov-SNAPSHOT</version>
	</dependency>
```

**Comment by karthikbhatnagar** [comment]
Thanks Sai..  sorry, I have been so busy lately.  I tested and it looks good.

**Comment by karthikbhatnagar** [comment]
BTW. I saw this

https://github.com/saikrishna321/AppiumTestDistribution/issues/210

Are you removing Extent support?

**Comment by karthikbhatnagar** [comment]
Hi Sai
Please comment
We are using klov and  extent reports for mobile, web and other testin projects. Removing support will impact us.

**Comment by karthikbhatnagar** [comment]
BTW I am closing this as this branch adds support for klov.

**Comment by saikrishna321** [comment]
> We are using klov and extent reports for mobile, web and other testin projects. Removing support will impact us.

No, that stream of work has gone on hold... no bandwidth

**Comment by karthikbhatnagar** [comment]
Thanks.

**Comment by karthikbhatnagar** [comment]
I have used other tools but klov makes the most sense and is easy to follow for everyone in our team. So you can create a plug-in for users who want to continue using Extentreports.

**Comment by saikrishna321** [comment]
> So you can create a plug-in for users who want to continue using Extentreports.

Sorry, didn't get this
