### ISSUE TITLE
Test passes in report when all steps are skipped

### ISSUE THREAD

**Issue by carolhmj** [saikrishna321/AppiumTestDistribution#257]
This happens when something fails before the test starts (errors with ADB or during Hooks). I am using the Cucumber framework with TestNG on version 7.0.1.
[I made the test example fail on Hooks to exemplify it.](https://imgur.com/6Ufu8XQ)

**Comment by saikrishna321** [comment]
will take a look .... what's the version ur using ??

**Comment by 99heitor** [comment]
@saikrishna321 it's version 7.0.1 but in my tests it also happens on the latest build

**Comment by saikrishna321** [comment]
@carolhmj @99heitor this happens when u run as cucumber alone ?

**Comment by carolhmj** [comment]
This happens when running with TestNG framework too.

**Comment by saikrishna321** [comment]
@carolhmj i can reproduce the issue.... will work on it ..

**Comment by saikrishna321** [comment]
<img width="1399" alt="screen shot 2017-11-24 at 7 29 26 am" src="https://user-images.githubusercontent.com/4045041/33199530-9b82c3bc-d0e8-11e7-8062-4d4dc8575d90.png">

<img width="1399" alt="screen shot 2017-11-24 at 7 24 23 am" src="https://user-images.githubusercontent.com/4045041/33199535-9f7e7434-d0e8-11e7-9296-461c7864d0a4.png">

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/pull/259

**Comment by saikrishna321** [comment]
@carolhmj merged to master, current fix is for testNG .. Pls try with below version

```
<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>b912084539</version>
	</dependency>
```

**Comment by saikrishna321** [comment]
@carolhmj ping
