### ISSUE TITLE
How can I run with groups using testng runner?

### ISSUE THREAD

**Issue by EzequielCamezzana92** [saikrishna321/AppiumTestDistribution#274]
I have a Runner creating a new paralleThread(), so I assign a package into the parallelThread instance. but I can filter this package by groups.
So I tried to use a testng.xml whit this config:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="100" verbose="2" name="TestNG Forum" parallel="methods">
    <test name="Regression1">
        <groups>
            <run>
                <include name="android"/>
            </run>
        </groups>
        <classes>
            <class name="grindr.tests.Runner">
            </class>
        </classes>
    </test>
</suite>
```
But obviusly this group apply to the class runner and into the runner i do not have any test with this tag. so there is any way to set into the parallel thread the cases after filter with the groups.

**Comment by saikrishna321** [comment]
@EzequielCamezzana92 Pls run the command by setting them in environment variables  
`INCLUDE_GROUPS="smoke" EXCLUDE_GROUPS="bugs" mvn clean -Dtest=Runner test `
