### ISSUE TITLE
configuration failure 

### ISSUE THREAD

**Issue by parul001** [saikrishna321/AppiumTestDistribution#287]
`	AppiumDriverLocalService service = AppiumDriverLocalService.buildService ( new AppiumServiceBuilder ( )
				.usingDriverExecutable ( new File ("C:\\Program Files\\nodejs\\node.exe") )
				.withAppiumJS ( new File (
				"C:/Users/parulb/AppData/Local/Programs/appium-desktop/resources/app/node_modules/appium/lib/main.js") )
				.usingPort ( 4723 )
				.withArgument ( GeneralServerFlag.LOG_LEVEL ,
				"debug" ) ) ;
				service.start();	`
# below is my console output*
C:\Users\parulb\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\lib\main.js:4
import { init as logsinkInit } from './logsink';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
## below are my configurations##
1.Appium :1.7
2.nodejs version: 9.5
3. windows 7

**Comment by saikrishna321** [comment]
If you execute the below command in your command line whats your output

`
C:/Users/parulb/AppData/Local/Programs/appium-desktop/resources/app/node_modules/appium/lib/main.js
`

**Comment by sarathsp23** [comment]
@parul001 I had the same error while trying to execute, I then changed the path to be 
C:/Users/<userName>/AppData/Roaming/npm/node_modules/appium/build/lib/main.js

**Comment by parul001** [comment]
@saikrishna321  when i execute the following command which is C:/Users/parulb/AppData/Local/Programs/appium-desktop/resources/app/node_modules/appium/lib/main.js  on command line  a  window dialog box opens with 1 error  and giving Microsoft JScript Compliation error . shown below:
![untitled](https://user-images.githubusercontent.com/20571722/36582425-70bf1fd0-1897-11e8-9997-ab592058e30e.png)

**Comment by messianic** [comment]
@parul001 I think you are trying to launch appium using the js file, the nodejs executable path needs to be prefixed before this and it still wont work as wrong js file is referred. The correct one is under: 
node_modules\appium\build\lib\main.js
rather than just:  node_modules\appium\lib\main.js

**Comment by parul001** [comment]
thanks
