### ISSUE TITLE
Refactor the method name for getting Device Udid

### ISSUE THREAD

**Issue by mrpgupta** [saikrishna321/AppiumTestDistribution#289]
its bit confusing when we use following for getting Ud id for device:

"AppiumDeviceManager.**getDevice().getDevice()**.getUdid()"

**Comment by SrinivasanTarget** [comment]
send us the exact link here

**Comment by mrpgupta** [comment]
link [here](https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumDriverManager.java#L170)

**Comment by SrinivasanTarget** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/pull/291

**Comment by saikrishna321** [comment]
as part of 8.0.0
