### ISSUE TITLE
iOS tests are failing as it is unable to get the OS version

### ISSUE THREAD

**Issue by shridharkalagi** [saikrishna321/AppiumTestDistribution#295]
iOS tests are failing as it is unable to get the OS version [here](https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/utils/DesiredCapabilityBuilder.java#L125)  

version of the device [here](https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/utils/DesiredCapabilityBuilder.java#L109) is "ProductVersion: 10.3.3" and its unable to convert it to float value. This value can be null as if ideviceinfo is not giving any results

**Comment by SrinivasanTarget** [comment]
I don't think so we need this condition check going forward as server is
capable to handle it anyways. We should bluntly set both by def and Appium
base driver will handle it internally.

**Comment by shridharkalagi** [comment]
@SrinivasanTarget However, we are setting the capabilities here. How will server handle this check?

**Comment by SrinivasanTarget** [comment]
Based on iOS version, Appium base driver initialise iOS Driver or
XCUIDriver. It's smart enough but if we have a smart solution, we can go
head and adopt it for handling WDA port based on iOS version still.

**Comment by shridharkalagi** [comment]
Ok and this issue is fixed in this [commit](https://github.com/SrinivasanTarget/DeviceManager/commit/24144005f576634accff2cff797d485f6b748ca6).
