### ISSUE TITLE
Tests run on the booted sims even if its not mentioned in the caps file

### ISSUE THREAD

**Issue by shridharkalagi** [saikrishna321/AppiumTestDistribution#302]
I want to run tests on the below 2 sims. However, tests are being run on the other booted sims as well.
 
"simulators": [
        {
          "deviceName": "iPhone 7",
          "OS": "11.2"
        },
        {
          "deviceName": "iPhone SE",
          "OS": "11.2"
        }
      ]

**Comment by saikrishna321** [comment]
@shridharkalagi thats the expected behaviour ...
