### ISSUE TITLE
While using updated Appium 1.8.0-beta3, getting error for  'webkitDebugProxyPort'  must be of type number

### ISSUE THREAD

**Issue by mrpgupta** [saikrishna321/AppiumTestDistribution#303]
Error : [XCUITest] InvalidArgumentError: 'webkitDebugProxyPort' **must be of type number**

[link](https://github.com/saikrishna321/AppiumTestDistribution/blob/cfc635903a93bc91467a66db91994d8bd2255be2/src/main/java/com/appium/utils/DesiredCapabilityBuilder.java#L121)

**Comment by saikrishna321** [comment]
@mrpgupta webkitproxy has been broken on the latest ... will get it fixed and release a version today.

@SrinivasanTarget you want to take this

**Comment by SrinivasanTarget** [comment]
@saikrishna321 There is a gap here when i'm fixing it. Let me close this today night. This needs a change in RemoteAppiumManager end too.
