### ISSUE TITLE
specify the bundleid in capabilities.json file and then test on pre-installed application can't work.

### ISSUE THREAD

**Issue by WenRui13** [saikrishna321/AppiumTestDistribution#309]
my capabilities.json:
```json
{
  "android": {
    "platformName": "android",
    "noSign": true,
    "deviceName": "android",
    "uiautomator2ServerInstallTimeout":60000,
    "app": "https://github.com/shridharkalagi/AppiumSample/raw/master/VodQA.apk"
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "device":"/Users/liuyang19/Music/iTunes/iTunes Media/Mobile Applications/7FRESH生鲜 1.1.2.ipa"
    },
    "bundleId": "com.xstore.sevenFresh",
    "deviceName": "iphone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": false,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "locationServicesEnabled": true,
    "locationServicesAuthorized": true,
    "autoAcceptAlerts": true,
    "maxTypingFrequency": 10,
    "isHeadless": false,
    "fullReset": false
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1"
    }
  ],
  "excludeLocalDevices": false
}
```
my config file:

> RUNNER=parallel
APPIUM_JS_PATH=/usr/local/lib/node_modules/appium/build/lib/main.js
#BROWSER_TYPE=chrome
APP_TYPE=NA
BUNDLE_ID=com.xstore.sevenFresh
FRAMEWORK=testng
#CAPS=./caps/capabilities.json
DEVICE_PLATFORM=device
APP_PACKAGE=com.xstore.sevenFresh

by review your source code ,if test on real device , the "app" capability and its subnode "devcie" is required. so this capblitiy is conflict with the bundleid capability.  and the result is that the tested app always be reinstall, how to solve it? thanks.

**Comment by saikrishna321** [comment]
try with below caps structure it should work

```
"iOS": {
    "platformName": "iOS",
    "bundleId": "com.xstore.sevenFresh",
    "deviceName": "iphone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": false,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "locationServicesEnabled": true,
    "locationServicesAuthorized": true,
    "autoAcceptAlerts": true,
    "maxTypingFrequency": 10,
    "isHeadless": false,
    "fullReset": false
  }
```

**Comment by WenRui13** [comment]
@saikrishna321 thanks,  I try it as above ,but the "app" capability is required. the log is bellow:

> Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@64b8f8f4
org.json.JSONException: JSONObject["app"] not found.
        at org.json.JSONObject.get(JSONObject.java:520)
        at org.json.JSONObject.getJSONObject(JSONObject.java:732)
        at com.appium.utils.CapabilityManager.isSimulatorAppPresentInCapsJson(CapabilityManager.java:74)
        at com.appium.manager.LocalAppiumManager.getDevices(LocalAppiumManager.java:93)
        at com.appium.utils.HostMachineDeviceManager.getDevices(HostMachineDeviceManager.java:98)
        at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:41)
        at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:25)
        at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:33)
        at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:41)
        at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:55)
        at com.appium.manager.ParallelThread.<init>(ParallelThread.java:49)

**Comment by saikrishna321** [comment]
Will fix this, we shall release v 8.0.1 soon as we have issues around ios-webkit-proxy for iOS

**Comment by WenRui13** [comment]
Nice, thanks a lot !

**Comment by saikrishna321** [comment]
@WenRui13 can you try with below version 

```
<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>fix-309-SNAPSHOT</version>
</dependency>
```

**Comment by WenRui13** [comment]
nice ,works fine  on your fix-309 branch.

**Comment by cesar-montoya** [comment]
hi, is this still an issue? I am able to replicate it on 10.0.1
