### ISSUE TITLE
"'Platform' is not recognized as an internal or external command , operable program or batch file. " error message is displayed on execution.

### ISSUE THREAD

**Issue by ThamaraiSelvi** [saikrishna321/AppiumTestDistribution#319]
D:\Android\PageObjectPatternAppium-single-server-session>mvn validate && Platfor
m="android" mvn clean -Dtest=RunnerCukes test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building PagePatternAppium 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- cucumber-jvm-parallel-plugin:4.2.0:generateRunners (generateRunners)
@ PagePatternAppium ---
[INFO] Adding D:\Android\PageObjectPatternAppium-single-server-session\src\test\
java to test-compile source root
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.669 s
[INFO] Finished at: 2018-05-07T16:17:47+05:30
[INFO] Final Memory: 10M/155M
[INFO] ------------------------------------------------------------------------
'Platform' is not recognized as an internal or external command,
operable program or batch file.

D:\Android\PageObjectPatternAppium-single-server-session>
![image](https://user-images.githubusercontent.com/5635111/39698419-614f5358-5212-11e8-8b86-06d47d787701.png)

**Comment by saikrishna321** [comment]
@SudhiHathwar how did u solve this on windows ?

**Comment by SudhiHathwar** [comment]
I think the syntax have changed now, we should provide mvn clean test -Dtest=RunnerCukes test -DPlatform=android

And should add the property in maven surefire plugin.

 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.14.1</version>
                <configuration>
                    <properties>
                        <Platform>${Platform}</Platform>
                    </properties>
                </configuration>
            </plugin>

**Comment by ThamaraiSelvi** [comment]
@SudhiHathwar Thanks for the reply. 

The above command with surefire configuration worked for me.

@saikrishna321 @SudhiHathwar 
But facing below issues.
1. Feature tests are not executed.
2. **cucumber-jvm-parallel-plugin:4.2.0:generateRunners** plugin is not generated in below log.

=====================================================
D:\AndroidBusiness>mvn clean test -Dtest=RunnerCukes test -DPlatform=android
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AndroidBusiness 1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ AndroidBusiness ---
[INFO] Deleting D:\AndroidBusiness\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ AndroidBus
iness ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\AndroidBusiness\src\main\resources

[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ AndroidBusiness
 ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ An
droidBusiness ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] Copying 22 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ Android
Business ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 57 source files to D:\AndroidBusiness\target\test-classes
[WARNING] /D:/AndroidBusiness/src/test/java/CommonActions/CampaignActions.java:
D:\AndroidBusiness\src\test\java\CommonActions\CampaignActions.java uses or over
rides a deprecated API.
[WARNING] /D:/AndroidBusiness/src/test/java/CommonActions/CampaignActions.java:
Recompile with -Xlint:deprecation for details.
[WARNING] /D:/AndroidBusiness/src/test/java/CommonActions/Utility.java: Some inp
ut files use unchecked or unsafe operations.
[WARNING] /D:/AndroidBusiness/src/test/java/CommonActions/Utility.java: Recompil
e with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ AndroidBusiness --
-
[INFO] Surefire report directory: D:\AndroidBusiness\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running StepDefinition.RunnerCukes
Configuring TestNG with: TestNG652Configurator
Adding all android devices: emulator-5556
Adding all android devices: emulator-5554
Adding Android devices
{emulator-5556=true, emulator-5554=true}
                            _  _        _
 _ __    __ _  _ __   __ _ | || |  ___ | |
| '_ \  / _` || '__| / _` || || | / _ \| |
| |_) || (_| || |   | (_| || || ||  __/| |
| .__/  \__,_||_|    \__,_||_||_| \___||_|
|_|

creating directory: Logs
creating directory: ADBLogs
Android emulator-5556 Directory is created!
Android emulator-5554 Directory is created!
***************************************************

Total Number of devices detected::2

***************************************************

starting running tests in threads
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.092 sec - in S
tepDefinition.RunnerCukes

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ AndroidBus
iness ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\AndroidBusiness\src\main\resources

[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ AndroidBusiness
 ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ An
droidBusiness ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] Copying 22 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ Android
Business ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ AndroidBusiness --
-
[INFO] Skipping execution of surefire because it has already been run for this c
onfiguration
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.676 s
[INFO] Finished at: 2018-05-07T18:16:21+05:30
[INFO] Final Memory: 27M/296M
[INFO] ------------------------------------------------------------------------

===================================================================

pom.xml
----------

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>TestSuite</groupId>
	<artifactId>AndroidBusiness</artifactId>
	<version>1.1-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>AndroidBusiness</name>
	<url>http://maven.apache.org</url>

	

	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>
		<dependency>
			<groupId>com.github.saikrishna321</groupId>
			<artifactId>AppiumTestDistribution</artifactId>
			<version>7.0.0</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>LATEST</version>
		</dependency>


		<dependency>
			<groupId>com.vimalselvam</groupId>
			<artifactId>cucumber-extentsreport</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>4.1.2</version>
		</dependency>
	</dependencies>
	
	<build>

		<pluginManagement>
			<plugins>

				

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>2.6</version>
					<executions>
						<execution>
							<goals>
								<goal>test-jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.1</version>
					<configuration>
						<source>1.8</source>
						<target>1.8</target>
					</configuration>
				</plugin>

				

				<plugin>
					<groupId>com.github.temyers</groupId>
					<artifactId>cucumber-jvm-parallel-plugin</artifactId>
					<version>4.2.0</version>
					<executions>
						<execution>
							<id>generateRunners</id>
							<phase>validate</phase>
							<goals>
								<goal>generateRunners</goal>
							</goals>
							<configuration>
								
								<glue>StepDefinition</glue>
								
								<outputDirectory>src/test/java/output</outputDirectory>
								
								<featuresDirectory>src/test/resources/features</featuresDirectory>
								
								<cucumberOutputDir>target/cucumber-parallel</cucumberOutputDir>
								
								
								
								
								
								<tags>"@MobileVeriifcation", "@RegularLeadList"</tags>
								
								<namingScheme>simple</namingScheme>
								
								<namingPattern>Parallel{c}IT</namingPattern>
								<parallelScheme>SCENARIO</parallelScheme>
								<packageName>output</packageName>
								<useTestNG>true</useTestNG>
								<plugins>
									<plugin>
										<name>com.cucumber.listener.ExtentCucumberFormatter</name>
									</plugin>
								</plugins>

							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.18.1</version>
					<configuration>
						<properties>
							<Platform>${Platform}</Platform>
						</properties>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
=====================================================

Note: If I remove compiler plugin, my project prompts error. So I'm having it.

**Comment by saikrishna321** [comment]
@ThamaraiSelvi did this work ? as i see u have closed?
