### ISSUE TITLE
Getting an error while switching context from Native to WebView

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#32]
Hi Sai, Recently we got new feature added in existing apps which has some webView, while switching context from Native to Webview i am seeing below highlighted error in red, can you please help here, we have deadline to complete implementing this feature by this week Wen. 

![screen shot 2016-03-21 at 3 19 11 pm](https://cloud.githubusercontent.com/assets/12589206/13932984/de0d4138-ef78-11e5-931e-4050e8cedbba.png)

Also PFB attached Appium log 

[1fb95ac900359617add8ffbb41dfdba33668e2a9__storeFinderTest.txt](https://github.com/saikrishna321/AppiumTestDistribution/files/183048/1fb95ac900359617add8ffbb41dfdba33668e2a9__storeFinderTest.txt)

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara this is something to do on the appium end and not anything on parallel execution stuff
