### ISSUE TITLE
Tests not running when simulator is open and caps for simulator is not present

### ISSUE THREAD

**Issue by shridharkalagi** [saikrishna321/AppiumTestDistribution#322]
`Device` is allocated for simulator as well even if 'simulators` object is not present in the capability file

**Comment by saikrishna321** [comment]
what is the solution your suggesting ?

**Comment by SrinivasanTarget** [comment]
@shridharkalagi we shouldn't depend on simulator object in caps file instead you should depend on the ipa/app/apk/zip file extensions...

**Comment by saikrishna321** [comment]
@shridharkalagi we should look for file extension and then based on that remove the corresponding device properties from the list.

Initial Device count: 5 includes  simulators and devices and if only IPA file is present then you need to remove the simulator objects.

@SrinivasanTarget Thoughts ?
