### ISSUE TITLE
How can we contribute to this project's wiki?

### ISSUE THREAD

**Issue by VPazzini** [saikrishna321/AppiumTestDistribution#332]
@saikrishna321 
Is there a way to make pull requests to this project's wiki?

**Comment by saikrishna321** [comment]
You can edit the wiki now ... Pls ping here once your done

**Comment by VPazzini** [comment]
Do you want to take a look before I edit anything? I added some steps, pages and added missing configs to run it with Cucumber.
[https://github.com/VPazzini/AppiumTestDistribution-wiki]

**Comment by saikrishna321** [comment]
@VPazzini looks good to me :) you can update the wiki

**Comment by VPazzini** [comment]
@saikrishna321 all done!
