### ISSUE TITLE
Could you please update project "PageObjectPatternAppium"

### ISSUE THREAD

**Issue by ssrikantasahoo** [saikrishna321/AppiumTestDistribution#339]
Could you please update project "PageObjectPatternAppium" for 8.0.0

**Comment by saikrishna321** [comment]
@ssrikantasahoo  https://github.com/saikrishna321/AppiumTestDistribution/issues/320

i have no bandwidth to fix the tests. PR welcome 😄

**Comment by saikrishna321** [comment]
@shridharkalagi any updates  ?

**Comment by ssrikantasahoo** [comment]
@saikrishna321 thank you. waiting foryour update.

**Comment by shridharkalagi** [comment]
@ssrikantasahoo  single-server-session branch is updated on that repo.

**Comment by saikrishna321** [comment]
@shridharkalagi are all tests passing ?

**Comment by saikrishna321** [comment]
i think we need to update tests ?

**Comment by shridharkalagi** [comment]
Tests are running. Only capabilities had to be updated. I will double check again and merge it to master.

**Comment by saikrishna321** [comment]
Kool ..Have u tested for both android n iOS ? when i asked tests all the tests in the branch ? not just the one with Parallel group

**Comment by ssrikantasahoo** [comment]
Hi @shridharkalagi could you please tell how we can run in iOS realdevice.

"iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/WordPress.zip"
    },

as app path for simulator define.

**Comment by saikrishna321** [comment]
```
"iOS": {
"platformName": "iOS",
"app": {
"device": "./build/WordPress.ipa",
"simulator": "./build/WordPress.zip"
}

```

**Comment by saikrishna321** [comment]
@ssrikantasahoo 'PageObjectPatternAppium' is updated to master
