### ISSUE TITLE
CAN'T Use AndroidDriver in this code

### ISSUE THREAD

**Issue by eyalpartner** [saikrishna321/AppiumTestDistribution#369]
My tests using Keycode event that only exist in AndroidDriver, Here you are using AppiumDriver that doesn't supports keycode events, What can you do in this matter ?

**Comment by saikrishna321** [comment]
@eyalpartner you need to TypeCast to AndroidDriver 

((AndroidDriver) driver)

**Comment by shridharkalagi** [comment]
Here is an example
`((AndroidDriver) AppiumDriverManager.getDriver()).longPressKey(new KeyEvent(AndroidKey.SPACE));`
