### ISSUE TITLE
iOS hybrid apps web element doesn't trigger once switched from Native to Webview using webkit proxy server

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#37]
Hi Sai, It's been last 2 days i have been trying to find out the root cause of why am i not able to click, send keys etc of web element once switched from Native to web view and i noticed that something that you need to modify in your framework for hybrid iOS apps web part to work.

When i commented out iOS Webkit proxy part from framework and manually started iOS wekitkit proxy server using below command i been able to access web element (if it is click event it clicked on web element).

ios_webkit_debug_proxy -c 1fb95ac900359617add8ffbb41dfdba33668e2a9:27753

Note: Before closing the issue please give it try because i tried all possibilities and after commented iOS webkit proxy part from your FW,  web element started working 

Thanks
Vinit

**Comment by saikrishna321** [comment]
Can u pls post the server logs ?

**Comment by saikrishna321** [comment]
Can u pls post the server logs ?

**Comment by VinitSandesara** [comment]
Sai, There are multiple issues i have found with this iOS webkit proxy server with any port assigned, Please find them all below with logs and screenshot.

(1) Issue 1 : 

- Execution is getting stuck and taking forever until it manually killed on "  driver.context(contextName);" once it found web view and going to switch the context from native to web view

Appium server log :  
[Issue1.txt](https://github.com/saikrishna321/AppiumTestDistribution/files/192238/Issue1.txt)

Screenshot :
![issue1](https://cloud.githubusercontent.com/assets/12589206/14085468/a4f526c8-f4e5-11e5-9bd6-88e80ea03edc.png)

(2) Issue 2  

- Execution is getting stuck and taking forever until it manually killed on "  Set<String> contextNames = driver.getContextHandles();"  while collecting all context for the page.

Appium server log :  
[Issue2.txt](https://github.com/saikrishna321/AppiumTestDistribution/files/192240/Issue2.txt)

Screenshot :
![issue2](https://cloud.githubusercontent.com/assets/12589206/14085583/4d199942-f4e6-11e5-9a54-e530ce0c068c.png)

(3) issue 3

- Execution is getting stuck and taking forever until it manually killed on "web element to perform action on (like click, send keys etc).", once context switched from native to web view, next line of code to perform web action (if it is click even it doesn't click on the web element).

Screenshot : 
![issue 3](https://cloud.githubusercontent.com/assets/12589206/14085584/533e973c-f4e6-11e5-9631-eb8e58417847.png)

Thanks
Vinit

**Comment by SrinivasanTarget** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/pull/38

**Comment by VinitSandesara** [comment]
@SrinivasanTarget , @saikrishna321 , This change is still not working, PFB complete debug logs

[1fb95ac900359617add8ffbb41dfdba33668e2a9__cartPageTest.txt](https://github.com/saikrishna321/AppiumTestDistribution/files/200637/1fb95ac900359617add8ffbb41dfdba33668e2a9__cartPageTest.txt)

by looking a the above debug logs you must be thinking that page for which i am trying to switch the context is not webview but let me tell you page is webview only, PFB logs with same scenario but in rough package which is switching the context to webview from native.

[sampleTest.txt](https://github.com/saikrishna321/AppiumTestDistribution/files/200640/sampleTest.txt)

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Sai, i tried with the version "4.0.1" but getting same error.

PFB server debug logs in gist

https://gist.github.com/anonymous/bb6e1192bca46bf60c956d25baf2a481

PFB server debug logs in gist of one of my sample test which is working as expected, switching the context to webview from native.

https://gist.github.com/anonymous/303aa27d20576e7ce75391a517c4f58d

Thanks
Vinit

**Comment by saikrishna321** [comment]
Please check if ios_webkit_proxy gets triggered when running yours tests

**Comment by VinitSandesara** [comment]
Yes Sai it was not getting triggered so i built appium from source and it worked but some webkit issue is still there for which i have raised an issue against it to fix.
 
https://github.com/appium/appium/issues/6334

Thanks
Vinit
