### ISSUE TITLE
SwipeTillTextExists infinite loop if text is not found

### ISSUE THREAD

**Issue by zuzeac** [saikrishna321/AppiumTestDistribution#383]
Hello,
I was trying to find a solution to swipe until certain text exist in the page and I found your implementation from here:
PageObjectPatternAppium/src/test/java/com/appium/config/CommonAppiumTest.java
public void swipeLeftUntilTextExists(String expected) {
        do {
            swipeLeft();
        } while (!driver.getPageSource().contains(expected));
    }

Unfortunately if the text/element is not found the method will continue swiping, will enter in an infinite loop.
I cannot find a solution to stop the method from swiping if the text is not found.

Do you have any idea how I might stop the swipe?

Best regards

**Comment by saikrishna321** [comment]
Just add an increment value break the loop after a certain count
