### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by AlphaQ1996** [saikrishna321/AppiumTestDistribution#385]
@saikrishna321 
Hey first let me apologize for putting this message in issues but i could not find any other way.
So  i just graduated and started my first job which is a automation test engineer. I am learning appium but am completely confused with a lot of elements of it. I am currently pursuing a course in udemy but its not much help.Any advice would be appreciated.
sincerely,
Nathan Moniz

P.S. My email is nathanmoniz@gmail.com

**Comment by saikrishna321** [comment]
@AlphaQ1996 Please use discuss.appium.io to ask all your questions and community will for sure help you.
