### ISSUE TITLE
Appium Server not responding

### ISSUE THREAD

**Issue by Muvidevlopers** [saikrishna321/AppiumTestDistribution#403]
Issue Details -
The Application is only opening but as per our Resource ID written in script for identifying element, the element is not being located and we are getting the following error log.

Environment
Appium version (or git revision) that exhibits the issue: 1.9.2-beta.2
Desktop OS/version used to run Appium: 10.13.6
Node.js version (unless using Appium.app|exe): 10.7.0
Mobile platform/version under test: iOS 12.0
Real device or emulator/simulator: Real Device and Simulator
Appium CLI or Appium.app|exe: Appium.app

[debug] [XCUITest] WebDriverAgent successfully started after 11155ms
[debug] [BaseDriver] Event ‘wdaSessionAttempted’ logged at 1540908894831 (19:44:54 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Matched ‘/session’ to command name ‘createSession’
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:52148/session] with body: {“desiredCapabilities”:{“bundleId”:“",“arguments”:[],“environment”:{},“shouldWaitForQuiescence”:true,“shouldUseTestManagerForVisibilityDetection”:true,“maxTypingFrequency”:10,“shouldUseSingletonTestManager”:false}}
[Xcode] t = 0.97s Open ******
[Xcode]
[Xcode] t = 0.97s Launch ******
[Xcode]
[Xcode] t = 1.13s Wait for ****** to idle
[Xcode]
[Xcode] t = 61.15s App event loop idle notification not received, will attempt to continue.
[Xcode]
[Xcode] t = 61.16s App animations complete notification not received, will attempt to continue.
[Xcode]
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT). Retrying…
[debug] [BaseDriver] Event ‘wdaSessionAttempted’ logged at 1540908975852 (19:46:15 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Matched ‘/session’ to command name ‘createSession’
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:52148/session] with body: {“desiredCapabilities”:{“bundleId”:"**”,“arguments”:[],“environment”:{},“shouldWaitForQuiescence”:true,“shouldUseTestManagerForVisibilityDetection”:true,“maxTypingFrequency”:10,“shouldUseSingletonTestManager”:false}}
[Xcode] 2018-10-30 19:47:01.103919+0530 WebDriverAgentRunner-Runner[1899:251246] Enqueue Failure: Failure fetching attributes for Device system-wide element: Error Domain=com.apple.XCTestErrorDomain Code=1000 “Timeout waiting for fulfillment of promise for ‘Fetching attributes for Device system-wide element’.” UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for ‘Fetching attributes for Device system-wide element’.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode]
[Xcode] 2018-10-30 19:47:01.104473+0530 WebDriverAgentRunner-Runner[1899:251246] Enqueue Failure: Failure to determine system application: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode]
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT). Retrying…
[debug] [BaseDriver] Event ‘wdaSessionAttempted’ logged at 1540909056897 (19:47:36 GMT+0530 (India Standard Time))

**Comment by saikrishna321** [comment]
#404
