### ISSUE TITLE
Unexpected Error from Appium server

### ISSUE THREAD

**Issue by Muvidevlopers** [saikrishna321/AppiumTestDistribution#404]
Issue Details - 
The Application is only opening but as per our ID written in script, the element is not being located and we are getting the following error log.

Environment
Appium version (or git revision) that exhibits the issue: 1.9.2-beta.2
Desktop OS/version used to run Appium: 10.13.6
Node.js version (unless using Appium.app|exe): 10.7.0
Mobile platform/version under test: iOS 12.0
Real device or emulator/simulator: Real Device and Simulator
Appium CLI or Appium.app|exe: Appium.app

Error Log - 
[Xcode]
[Xcode] 2018-10-30 19:50:16.262904+0530 WebDriverAgentRunner-Runner[1899:251246] Enqueue Failure: Failure fetching attributes for (null): Error Domain=com.apple.XCTestErrorDomain Code=1000 “Timeout waiting for fulfillment of promise for ‘Fetching attributes for (null)’.” UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for ‘Fetching attributes for (null)’.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode]
[Xcode] 2018-10-30 19:50:16.265961+0530 WebDriverAgentRunner-Runner[1899:251246] Enqueue Failure: Failure getting list of active applications: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode]
[Xcode] t = 322.45s Unable to monitor event loop
[Xcode]
[Xcode] t = 322.47s Unable to monitor animations
[Xcode]
[Xcode] t = 322.48s Open com.release.*****
[Xcode]
[Xcode] t = 322.48s Launch com.release.*****
[Xcode]
[Xcode] t = 322.48s Terminate com.release.:1904
[Xcode]
[Xcode] t = 323.72s Wait for com.release. to idle
[Xcode]
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT). Retrying…
[debug] [BaseDriver] Event ‘wdaSessionAttempted’ logged at 1540909218924 (19:50:18 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Matched ‘/session’ to command name ‘createSession’
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:52148/session] with body: {“desiredCapabilities”:{“bundleId”:"com.release.",“arguments”:[],“environment”:{},“shouldWaitForQuiescence”:true,“shouldUseTestManagerForVisibilityDetection”:true,“maxTypingFrequency”:10,“shouldUseSingletonTestManager”:false}}
^[[A[Xcode] t = 383.76s App event loop idle notification not received, will attempt to continue.
[Xcode]
[Xcode] t = 383.77s App animations complete notification not received, will attempt to continue.
[Xcode]
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT). Retrying…
[debug] [BaseDriver] Event ‘wdaSessionAttempted’ logged at 1540909299933 (19:51:39 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Matched ‘/session’ to command name ‘createSession’
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:52148/session] with body: {“desiredCapabilities”:{“bundleId”:"com.release.,“arguments”:[],“environment”:{},“shouldWaitForQuiescence”:true,“shouldUseTestManagerForVisibilityDetection”:true,“maxTypingFrequency”:10,“shouldUseSingletonTestManager”:false}}
^[[B[Xcode] 2018-10-30 19:52:23.626194+0530 WebDriverAgentRunner-Runner[1899:251246] Enqueue Failure: Failure fetching attributes for Device system-wide element: Error Domain=com.apple.XCTestErrorDomain Code=1000 “Timeout waiting for fulfillment of promise for ‘Fetching attributes for Device system-wide element’.” UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for ‘Fetching attributes for Device system-wide element’.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-10-30 19:52:23.628671+0530 WebDriverAgentRunner-Runner[1899:251246] Enqueue Failure: Failure to determine system application: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode]
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT). Retrying…
[debug] [BaseDriver] Event ‘wdaSessionAttempted’ logged at 1540909380945 (19:53:00 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Matched ‘/session’ to command name ‘createSession’
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:52148/session] with body: {“desiredCapabilities”:{“bundleId”:“com.release.*****”,“arguments”:[],“environment”:{},“shouldWaitForQuiescence”:true,“shouldUseTestManagerForVisibilityDetection”:true,“maxTypingFrequency”:10,“shouldUseSingletonTestManager”:false}}
[Xcode] 2018-10-30 19:53:28.646466+0530 WebDriverAgentRunner-Runner[1899:251246] Enqueue Failure: Failure fetching attributes for (null): Error Domain=com.apple.XCTestErrorDomain Code=1000 “Timeout waiting for fulfillment of promise for ‘Fetching attributes for (null)’.” UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for ‘Fetching attributes for (null)’.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-10-30 19:53:28.649003+0530 WebDriverAgentRunner-Runner[1899:251246] Enqueue Failure: Failure getting list of active applications: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1

**Comment by Muvidevlopers** [comment]
@saikrishna321 @SrinivasanTarget could you please look into this and help us to resolve.

**Comment by saikrishna321** [comment]
@Muvidevlopers This issue is related to Appium please ask for help in discuss.appium.io. Issue not related to ATD
