### ISSUE TITLE
iOS apps which left open in device due to some reason does NOT relaunch once killed on next execution

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#45]
Hi Sai, iOS apps which left open in device due to some reason doesn't relaunch once killed on next execution, can you please check and make the modification in script so it first check if the apps is open before relaunching killed it first.

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara can you please post logs and the BaseTest

**Comment by VinitSandesara** [comment]
Nevermind Sai, it is working now.

Thanks
Vinit
