### ISSUE TITLE
Enhancement : Can you please implement "ExtentX" in framework to track an extentReport from ExtentX dashboard

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#46]
Hi Sai, There is good feature from Anshoo "ExtentX" if we an utilize that in framework, thru this we can track each extentReport from ExtentX dashboard, it's cool feature to consider.

PFB link of ExtentX demo which is there in http://extentreports.relevantcodes.com/

Demo: http://extentx.herokuapp.com/

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Sai, Can you please give your thought on this 

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara http://extentreports.relevantcodes.com/extentx/ please follow the setup
