### ISSUE TITLE
Need testcase step logs for manual qa to identify an issue and before reporting it as an issue manually test it in application, also need some modification in report

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#5]
Hi Sai, Can you please add below points in your framework

(1) It would be great along with "AppiumServerLogs" and "AdbLogs" if there would be "testCaseStepsLogs" (using log4j logs) for manual QA to identify the issue looking at the testcase steps and before reporting it as an issue they can give it a try using steps log manually in application
           Example : 
                    Enter username
	  	   Enter password
		   click on sign in button
		  wait for welcome page to load

(2) In Extend report what i have noticed is when test case failed it doesn't display the name of failed test case, like in below screenshot LoginTest failed all 4 test but there is no name of testcase (hightailed in red)

![screen shot 2016-01-15 at 12 07 58 pm](https://cloud.githubusercontent.com/assets/12589206/12361200/59b78fa8-bb82-11e5-974e-e5fdfd7f23af.png)

(3) In below screenshot there are total 4 test in LoginTest but it doesn't says how many test cases "LoginTest" has among how many passed and how many failed (hightailed in red)

![screen shot 2016-01-15 at 12 11 38 pm](https://cloud.githubusercontent.com/assets/12589206/12361250/aae2f7f0-bb82-11e5-941a-a2db80038f1c.png)

Thanks
VInit

**Comment by saikrishna321** [comment]
@VinitSandesara w.r.t to Log4J you can still implement it from your test run, so that u can specify the test description.

i have made the changes to the report which shows the @Test method name for both pass and failure, 

<img width="757" alt="screen shot 2016-01-16 at 1 08 33 pm" src="https://cloud.githubusercontent.com/assets/4045041/12371206/264116b4-bc52-11e5-8a6c-2013f9a01cdb.png">


for your 3rd point, you need to raise an issue on extent report repo.

**Comment by saikrishna321** [comment]
@VinitSandesara i have worked on the Adding Logs to the report, take a look at the screen below does this look good .. 

<img width="1008" alt="screen shot 2016-01-16 at 2 42 14 pm" src="https://cloud.githubusercontent.com/assets/4045041/12371629/0d9fe4a2-bc5f-11e5-929f-f467996bdeef.png">


```
writeLogsToReport("Login Test");
writeLogsToReport("Enter UserName and Password");
writeLogsToReport("Login Successfull");
```

**Comment by VinitSandesara** [comment]
Yes Sai, it looks good, Thank you very much for adding these enhancements and release it very soon. For 3rd point mentioned in my question i will soon raise an issue  on extent report repo.

Thanks
Vinit

**Comment by saikrishna321** [comment]
No I don't that would work well, may b for u to differentiate u need to prefix the logging with your method name or className. ..

**Comment by saikrishna321** [comment]
@VinitSandesara all that u can do is prefix the class/method name to the logger. You would see the logs in sequence. This is should help.

**Comment by VinitSandesara** [comment]
Thanks Sai, Can you please provide some example so i can try or can you please add in your sample test "https://github.com/saikrishna321/PageObjectPatternAppium". Really need this as my manager really liked this concept that you have provided.

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara sample code snippet 

```
@Test
    public void testMethodOne_1(Method m) throws Exception  {
	    
		System.out.println("ThreadName: " + Thread.currentThread().getName() + Thread.currentThread().getStackTrace()[1].getClassName());
		Thread.sleep(3000);
		writeLogsToReport("Login Test",m);
		getDriver().findElement(By.id("com.android2.calculator3:id/cling_dismiss")).click();
		getDriver().findElement(By.id("com.android2.calculator3:id/digit2")).click();
		writeLogsToReport("Enter UserName and Password",m);
		writeLogsToReport("Login Successfull",m);
		getDriver().findElement(By.id("com.android2.calculator3:id/plus")).click();
		getDriver().findElement(By.id("com.android2.calculator3:id/digit9")).click();
		getDriver().findElement(By.id("com.android2.calculator3:id/equal")).click();
		getDriver().findElement(By.id("com.android2.calculator3:id/plus")).click();
		getDriver().findElement(By.id("com.android2.calculator3:id/digit9")).click();
		getDriver().findElement(By.id("com.android2.calculator3:id/equal")).click();
		//getDriver().close();
    }
```

![d9d93b76-bc88-11e5-829f-fae0799d36f4](https://cloud.githubusercontent.com/assets/4045041/12409215/04b4608a-be8e-11e5-8f94-ea934d1b5f29.png)


This will be a part of the next release

**Comment by VinitSandesara** [comment]
Thank you so much Sai, appreciated for your help on this one, So curious to know when will be the next release ? if possible can you please release out this enhancement sooner ? 

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Hi Sai, Can you please give ETA for this release ? eagerly waiting for this release.

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara i have pre-release 3.0.4 version ... You can log the output to the report by 

```
ExtentTestManager.logOutPut("User is logged in succesfully");
```

Which ever class you're using the above code snippet, the report will hold the respective  ClassName and MethodName

**Comment by VinitSandesara** [comment]
Hi Sai, This still doesn't looks good, all the test suite test cases are at one common place from where it can be access, lets say i have 20 Test Suite which are having total 400 test cases and i wanna search for 250 test case logs for which i have to start from Top to bottom or i can search by that test case name but how about instead of this if we can generate and attach "Step Logs(using log4j" with each test (like "Appium log" and "Adb Log" attached in report) so it can easily be use. I have modified generated ExtentReport and added some line in Red if the report can be generate like this.

![screen shot 2016-01-24 at 4 31 10 pm](https://cloud.githubusercontent.com/assets/12589206/12539463/aa943eb6-c2b8-11e5-8d5d-d1f39f27b61a.png)


Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara  

The best you can do is

```
Reporter.log("Test Logger Same Under the test");
ExtentTestManager.getTest().log(LogStatus.INFO, "Test Logger Same Under the test");
```

This will log the steps above the specific method .

![screen shot 2016-01-25 at 1 32 23 pm](https://cloud.githubusercontent.com/assets/4045041/12545372/981ff34c-c367-11e5-961d-b4d8fd23f807.png)

**Comment by VinitSandesara** [comment]
Hi Sai, Yes this is working as expected the soltuion you have provided however in my requirement it does't looks good, as per my requirement i need to generate step logs (using log4j) and attach them in each test case. Can you please provide the solution on this ?

How can i generate Step logs of every test cases i have in my test suite and attach them in report like you have done for "Appium logs" and "Adb logs"

Thanks
Vinit
