### ISSUE TITLE
[Suggestion] Add test step in ExtentReports

### ISSUE THREAD

**Issue by ansonliao** [saikrishna321/AppiumTestDistribution#53]
Dear sir,
Thanks provide such wonderful integration tools and shared it.

In my integration roadmap of Appium, I also use TestNG, ExtentReport, also image tool SikuliX, and YAML to manage the page object (reduce the hard code in test script).

I would like to know, whether you can add test step information into ExtentReports, not just `@BeforeClass`, `@BeforeMethod`, `@AfterMethod`, `@AfterClass` message in appium server start and appium quit.

For example, in test, in `Login` page, click page object `Submit` button, we can also record the test operation information into ExtentReport, such like:
```
Click: Login --> [Submit] button
``` 

and how to store the description of test operation, maybe we can extend `WebElement` and add a field  to store the description, such like:
```
ExtWebElement:
  - WebElement
  - Description
 ```

any advise?

BTW, how I can get the ExtentTest instance in `@Test`?

**Comment by saikrishna321** [comment]
@ansonliao sorry, i completely couldn't get what you asking for. What i understand is that you want to add loggers to the step name as part of the method as below 

![screen shot 2016-04-20 at 3 41 23 pm](https://cloud.githubusercontent.com/assets/4045041/14671203/3f30b8a8-070e-11e6-9c5d-9de93167f9eb.png)

Your test would look like 
```
       getDriver().findElement(By.id("com.android2.calculator3:id/plus")).click();
		captureScreenShot("Sample1Image");
		logger("Just captured Screenshot");
		getDriver().findElement(By.id("com.android2.calculator3:id/digit9")).click();

```

**Comment by saikrishna321** [comment]
@ansonliao ping.. if this looks good. we can close this issue

**Comment by ansonliao** [comment]
@saikrishna321 
Sorry Sai, long time no reply.

I just what to know, how to log some information of test during test, for example the basic usage of ExtentReport from official:

```java
// new instance
ExtentReports extent = new ExtentReports(file-path, replaceExisting);

// starting test
ExtentTest test = extent.startTest("Test Name", "Sample description");

@Test
public void f1() {
    pageObjects.login_button.click();
    test.log(LogStatus.INFO, "Login button click";
    ...
}
```

**Comment by saikrishna321** [comment]
@ansonliao you can do this way, give it try and get back pls

```
ExtentTestManager.getTest().log(LogStatus.FAIL,"Failed");
```

**Comment by ansonliao** [comment]
@saikrishna321 

Log information during testing by code below is works, I inserted the code in Page class, thanks Sai.

```java
ExtentTestManager.getTest().log(LogStatus.FAIL,"Failed");
```

**Comment by ansonliao** [comment]
@saikrishna321 
Please help to close this issue.
