### ISSUE TITLE
testcase retry before deciding it's an application issue

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#6]
Hi Sai, Can you please add "retry" on test method (max 3 times) before considering it's an actual application issue. What i mean to say is lets say LoginTest has test method "loginWithValidUser()" which started executing and some reason it failed (not due to an application issue) lets say network issue so that's not an application issue in this case it should execute same test  "loginWithValidUser()" again, if it pass on 2nd try it should not go for 3rd try but if it fails on 2nd try so 3rd try will be the last one and then it will be consider that even after trying same scenario 3 times it is still failing it means it's an application issue and Dev has to fix it.

Thanks
Vinit

**Comment by saikrishna321** [comment]
@jaydeepc @thotegowda do you this should b a part of the framework ?

**Comment by VinitSandesara** [comment]
Hi Sai, Any updates on this ?

Thanks
Vinit

**Comment by thote** [comment]
Looks like a good to have feature machha.

**Comment by saikrishna321** [comment]
@thote thanks buddy ... @VinitSandesara this will be implemented in the next release

**Comment by VinitSandesara** [comment]
Thanks you so much @thote  and Sai for taking this an an consideration, appreciated guys. Sai what is your plan to release out this new enhancement in new release ? 

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Hi Sai, Can you please give ETA for this release ? eagerly waiting for this release.

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara I have the implementation, please check the below code 

https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/test/java/com/test/site/HomePageTest3.java#L14-L15

Does this look good ?

**Comment by VinitSandesara** [comment]
Hi Sai, I have tried Retry in my test same way you have explained above in your reply but what i have noticed is with Retry ExtentReport is generating with 0 bytes (Blank report), when i try without Retry it is generating as expected. PFB screenshot 

(1) @Test with Retry which generate ExtentReport blank (0 Bytes) hightailed in red

![screen shot 2016-01-24 at 2 14 43 pm](https://cloud.githubusercontent.com/assets/12589206/12538688/9317c536-c2a5-11e5-87c7-b669e86c372c.png)


(2) @Test WITHOUT retry which generate ExtentReport as expected with Bytes highlighted in Red

![screen shot 2016-01-24 at 2 11 45 pm](https://cloud.githubusercontent.com/assets/12589206/12538692/a587b28a-c2a5-11e5-96be-97a5669cd223.png)


Thanks
Vinit

**Comment by VinitSandesara** [comment]
Hi Sai, Thank you so much for implementing this enhancement however what i have noticed is report is not clear (easy to understand) with Retry implementation, can the report with Retry be enhanced (implement) like below for end user like Manual QA, Management can easily understand ? I didn't mean to say to implement same way described in below screenshot but this is well organized way to present the end user.

![screen shot 2016-01-24 at 3 23 19 pm](https://cloud.githubusercontent.com/assets/12589206/12539288/c855e0fc-c2b4-11e5-8eed-9c5574f96d1b.png)

![screen shot 2016-01-24 at 3 23 44 pm](https://cloud.githubusercontent.com/assets/12589206/12539289/ccfda540-c2b4-11e5-8629-0a191931f92c.png)

![screen shot 2016-01-24 at 3 31 49 pm](https://cloud.githubusercontent.com/assets/12589206/12539290/cfceff9e-c2b4-11e5-8623-4118b371f100.png)

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara this looks really good.. But you need to raise this on the extent report end.
