### ISSUE TITLE
[Suggestion] Capture the screenshot for every action.

### ISSUE THREAD

**Issue by ShilpaGopal** [saikrishna321/AppiumTestDistribution#61]
Hi,

It would be helpful to debug If we can capture the screenshot before and after the every action and possibly displaying it in the execution report or we can have the debug report as well.

**Comment by saikrishna321** [comment]
@SrinivasanTarget @ShilpaGopal Don't you think, capturing screenshot for every action will be time consuming, if its in ms fine.. Your thoughts ?

**Comment by SrinivasanTarget** [comment]
Will degrade performance esp. in iOS but still if needed we can have it as a flag.

Also there are screenshots issues already in iOS which has been reported on appium server by few users.

**Comment by saikrishna321** [comment]
```
@Test
    public void sampleTest(){
        List<File> images= new ArrayList<File>();
        images.add(new File("/Users/saikrisv/git/animated-gif-lib-for-java/src/test/resources/Image1.png"));
        images.add(new File("/Users/saikrisv/git/animated-gif-lib-for-java/src/test/resources/Image2.png"));
        try {
            createAnimatedGif(images,new File("/Users/saikrisv/git/animated-gif-lib-for-java/src/test/resources/3.gif"));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

![3](https://cloud.githubusercontent.com/assets/4045041/15203357/5d89a026-1820-11e6-881d-12ff689038bb.gif)

**Comment by priyankshah217** [comment]
@saikrishna321 , capturing screenshots will degrade performance but it will also increase report size also. We can externalize this feature like serenity, to config.properties.

SCREENSHOT_ON_EACH_STEP
SCREENSHOT_ON_FAILURE

whats your view on that?

**Comment by saikrishna321** [comment]
@priyankshah217 SCREENSHOT_ON_EACH_STEP can be externalize, i'm okay with that .. 

But SCREENSHOT_ON_FAILURE should be captured by default, that helps users debug the issue

**Comment by saikrishna321** [comment]
have video logs implented, so closing
