### ISSUE TITLE
[Issue] in version 4.0.2 from maven dependency, class 'AndroidDeviceConfiguration' no method "removeApkFromDevices"

### ISSUE THREAD

**Issue by ansonliao** [saikrishna321/AppiumTestDistribution#62]
Hi Sai,
I updated `AppiumTestDistribution` from `4.0.1` to `4.0.2` in my test project's `POM.xml`, but after downloaded 4.0.2 jar, get error and message is class `AndroidDeviceConfiguration` without method `removeApkFromDevices`.

I checkout `AppiumTestDistribution` source code from `Github` and found that method `removeApkFromDevices` was existed in class `AndroidDeviceConfiguration`.

could you advise what is the problem?

**Comment by saikrishna321** [comment]
@ansonliao removeApkFromDevices is not as a part of 4.0.2, yet to tag a version.. Can you try with the below dependency and check if you can see the method.

```
<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>165d5f0043</version>
</dependency>
```

**Comment by ansonliao** [comment]
@saikrishna321 
thanks Sai's dependency, it is work.
BTW, in my case, I am use TestRail to manage the test result, so I need to upload test result to TestRail to the mapping test case (TestRail SDK provided).
so I would like to extend the class `AppiumParallelTest` and then rewrite method `endLogTestResults` for adding TestRail upload code.

Also need the device UDID/device_name in test result comment of TestRail to identify the result from which real device. 

any good suggestion how I can do approach it?

**Comment by saikrishna321** [comment]
@ansonliao i haven't worked on TestRail , can you please brief out what format the TestRail expect the results or how do you manually do

**Comment by ansonliao** [comment]
@saikrishna321 
for uploaded test result to TestRail, I have my SDK to upload it, and the upload code is simply, for example, for PASS result:

```java
TestRailManager.addTestResultForTestInstance(testRailId,  TestRailResultCode.PASSE, device_udid.replaceAll("\\W", "_") + ": \nTest Passed in Appium");
```

so I need to do is just add TestRail handle code in method `endLogTestResults` in three test result handler code.

I tried to extend class `AppiumParallelTest` but found that some necessary variables in class `AppiumParallelTest` are private.

**Comment by saikrishna321** [comment]
@ansonliao can you please send me a PR on this. As you almost have some implementation 

That would be great..

**Comment by ansonliao** [comment]
@saikrishna321 
I created a class `AppiumParallelTest4AL` which extent class `AppiumParallelTest`, and added my end test log result method `myEndTestResults(ITestResult iTestResult)`, this method code almost is same as the method `endLogTestResults(ITestResult iTestResult)` of class `AppiumParallelTest` but beside TestRail upload code:

```java
    public void endTestResults(ITestResult iTestResult) {
        // get test case ID from Test Rail
        TestRail testRail = iTestResult.getMethod().getConstructorOrMethod().getMethod().getAnnotation(TestRail.class);
long testRailId = testRail.testId();

        if (iTestResult.isSuccess()) {
            ExtentTestManager.getTest()
                    .log(LogStatus.PASS, iTestResult.getMethod().getMethodName(), "Pass");
            if (driver.toString().split("\\(")[0].trim().equals("AndroidDriver:  on LINUX")) {
                log_file_writer.println(logEntries);
                log_file_writer.flush();
                ExtentTestManager.getTest().log(LogStatus.INFO, iTestResult.getMethod().getMethodName(),
                        "ADBLogs:: <a href=" + System.getProperty("user.dir") + "/target/adblogs/"
                                + device_udid.replaceAll("\\W", "_") + "__" + iTestResult.getMethod()
                                .getMethodName() + ".txt" + ">AdbLogs</a>");
                System.out.println(driver.getSessionId() + ": Saving device log - Done.");
            }
     
           // Upload result to TestRail
           TestRailManager.addTestResultForTestInstance(testRailId,
                        TestRailResultCode.PASSED,
                        device_udid.replaceAll("\\W", "_") + ": \nTest Passed in Appium");
        }
```

and going on I would like to add TestRail code in the Failure test result, but I found that I can't use the `AppiumParallelTest`'s private variables such as `androidDevice` in `FAILURE` If conditional.

**Comment by ansonliao** [comment]
@saikrishna321 
Maybe another choice is create a interface to TestRail test result uploading named "TestRailResult", and then class `UserBaseTest` extend class `AppiumParallelTest` and implements interface `TestRailResult`, and the finally, add TestRail test result upload method in `@AfterMethod`.

**Comment by ansonliao** [comment]
@saikrishna321 
Please closed this issue.
About how to integrate the third party report test result, I will open a new issue to discuss.
thanks for your help.
