### ISSUE TITLE
Testing framework issues Null pointer when devices is "offline" from ADB

### ISSUE THREAD

**Issue by Jtramey** [saikrishna321/AppiumTestDistribution#64]

**Comment by Jtramey** [comment]
Found this today, 

Connect a device through adb.
Do not accepts the adb debugging prompt. 
This will put the devices in an "offline" mode for ADB. 

When trying to run tests, it will throw a null pointer. 

```
Running com.appium.tests.Runner
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@7cef4e59
creating directory: Logs
creating directory: ADBLogs
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.963 sec <<< FAILURE!
testRunner(com.appium.tests.Runner)  Time elapsed: 0.741 sec  <<< FAILURE!
java.lang.NullPointerException
	at com.appium.manager.ParallelThread.createSnapshotFolderAndroid(ParallelThread.java:111)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:60)
	at com.appium.tests.Runner.testRunner(Runner.java:12)
```

**Comment by saikrishna321** [comment]
@Jtramey thanks for reporting. Do you have just one device connected and device is offline or multiple devices and one off them is offline ?

**Comment by Jtramey** [comment]
I had 3 devices connected.  2 were online and one was offline.

**Comment by saikrishna321** [comment]
if you look at this line 
https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AndroidDeviceConfiguration.java#L78

Device UDID will be picked only when they are Online, but in your case 2 devices should be pushed to the device pool, but its throwing null thats weird. 

Let me try this when i get access to real devices. Will keep you posted

**Comment by saikrishna321** [comment]
@Jtramey i tried to put the device to offline, but when i don't accept the debug prompt i get device as unauthorized, not offline ..

**Comment by Jtramey** [comment]
Haha I am also trying to figure out how I got a device in the offline
state.  Looking now.

**Comment by saikrishna321** [comment]
@Jtramey were you able to reproduce this? i'm not able to

**Comment by Jtramey** [comment]
Having issues getting a device into the offline state to check this out
again. Ill update you in the gitter if i find out how to do this. Should be
fine to close.

**Comment by saikrishna321** [comment]
@Jtramey Thanks.. closing for now.. please reopen if you could reproduce.

**Comment by saikrishna321** [comment]
@Jtramey
