### ISSUE TITLE
Handling Multiple User credentials when tests in parallel

### ISSUE THREAD

**Issue by vikramvi** [saikrishna321/AppiumTestDistribution#66]
@saikrishna321  can you please clarify parallel execution approach in app like gmail , where I launch browser on each of the devices with same id and do actions like creating mail , deleting etc.

how do you make sure each of the action is thread safe and don't mingle with others

Thanks in advance.

**Comment by saikrishna321** [comment]
@vikramvi TestNG does take care of the parallel thread thingy and i'm bit scared when the tests run with the same user-id. For example (Grocery app)

When your running your tests across 2 devices and Test1 does adding something to item to cart and Test2 is removing item from cart, in this case there are high chances where the tests would fail and would be flaky .. I would look for having different user credentials for number of threads ...

**Comment by vikramvi** [comment]
exactly , only solution is using different id for each of the threads. 
Did you try this approach in your project ? I'm also trying to find a solution for this. 

Thanks,
Vikram

**Comment by SrinivasanTarget** [comment]
We will look into this asap... anyways nice question.

**Comment by saikrishna321** [comment]
@vikramvi haven't tried in ma project but its good to have feature...

**Comment by vikramvi** [comment]
Thanks guys @SrinivasanTarget @saikrishna321  , I thought of one option is using unique user id & pwd for each of the classes. ( provided each class runs on individual thread )

If someone wants to run test cases in single class in parallel model then it's still open question. Please let me know if I could of any help in resolving this query

Regards,
Vikram

**Comment by saikrishna321** [comment]
@vikramvi does this looks good ?

**Comment by vikramvi** [comment]
This is awesome , thanks a ton for quick fix. You should address this issue and solution during seleconf presentation.

**Comment by saikrishna321** [comment]
@vikramvi thanks buddy for reporting this ..... we proposed but couldn't get a slot ..

**Comment by vikramvi** [comment]
Thats sad to hear, may be you can update on discuss.appium.io and can put this into commercial use through https://testobject.com/blog/2016/05/testobject-box-your-smart-in-house-mobile-test-lab.html just IMHO. Can be useful to hundreds of companies

**Comment by saikrishna321** [comment]
@vikramvi sure will do that buddy.. i already have it on discuss.io 
https://discuss.appium.io/t/android-java-client-solution-trigger-test-in-parallel-without-using-grid/7078
