### ISSUE TITLE
Print the @Test description instead of the method name

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#67]
It would look much nicer if in the extent report we are able to see the @Test description instead of the method name or maybe along with the method name. It could allow the users to add more descriptive names for the extent results.

**Comment by saikrishna321** [comment]
@RatkoD you can do it this way 

```
    @BeforeMethod() public void startApp(Method name) throws Exception {
        Test test = name.getAnnotation(Test.class);
        driver = startAppiumServerInParallel(name.getName() + test.description());
        startLogResults(name.getName());
    }
```
