### ISSUE TITLE
Implement ExtentX reporting for the test results

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#68]
Hey @saikrishna321,

I have 4 nodes which are executing tests using the AppiumTestDistribution framework, and the problem is that I get 4 separate reports from the nodes. The idea is to implement ExtentX reporting, because it's really easy to setup ExtentX server with MongoDB and that all 4 nodes are sending the results to the DB and that way we'll have single place for analysing the test results and we'll have test's history and trending graphs.

**Comment by saikrishna321** [comment]
@RatkoD when u say 4 nodes, do u mean 4 instance of appium server or how is your setup ?

**Comment by RatkoD** [comment]
I'm starting the tests from 4 different PCs (2 mac and 2 linux) and I have 5 or 6 devices attached to each PC. The idea is to start the test execution from Jenkins on all 4 nodes and have only one combined report.
One thing that I'm not sure about is what happens with the logs and screenshots? Are they stored in the DB? If yes, that's very nice, if not... it will be a problem. Then the option will be to have ExtentReport for detailed reports for each test run and ExtentX for statistics and trending combined reports.

**Comment by RatkoD** [comment]
As a workaround, I've moved instance.x(); out of the if statement.

public class ExtentManager {
    public static ExtentReports instance;

    public synchronized static ExtentReports getInstance() {
        if (instance == null) {
            System.out.println(System.getProperty("user.dir"));
            instance =
                new ExtentReports(System.getProperty("user.dir") + "/target/ExtentReport.html");
            **instance.x();**
            try {
                if (System.getenv("ExtentX").equalsIgnoreCase("true")) {
                    instance.x();
                }
            } catch (Exception e) {
                System.out.println("Not taking ExtendReporting");
            }
        }
        return instance;
    }
}

This way the results are sent to the local MongoDB which does not solves my problem, but gives me trending results for one node.
My opinion is that this should be configurable in config.properties, something like 
MongoDB_server: ADDRESS_OF_THE_SERVER
MongoDB_Port: PORT_NUMBER

**Comment by saikrishna321** [comment]
@RatkoD PR welcome :)
