### ISSUE TITLE
Implement the passing of the noReset flag when creating the driver

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#69]
Currently, the framework resets the app before every test which make impossible to test some scenarios for features like, intro screen is presented only once at first login, or scenario where email filed value is preserved after logout and on next start. One option is to pass the noReset flag to the driver at creation time so the app is not reseted.

Can this be done?

**Comment by priyankshah217** [comment]
`
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.AndroidMobileCapabilityType;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.service.local.AppiumDriverLocalService;
import io.appium.java_client.service.local.AppiumServiceBuilder;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.*;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

public class LinkedInTest {

    private static AppiumDriverLocalService service;
    private AndroidDriver driver = null;


    public AppiumDriver getDriver() throws MalformedURLException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "6.0.1");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus 5");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Appium");
        if (driver == null) {
            capabilities.setCapability(MobileCapabilityType.APP, new File(ClassLoader.getSystemResource("linkedin.apk")
                    .getFile()).getAbsolutePath());
        } else {
            capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.linkedin.android");
            capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, ".authenticator.LaunchActivity");
        }
        URL serverUrl = new URL("http://localhost:4723/wd/hub");
        AppiumDriver driver = new AndroidDriver(serverUrl, capabilities);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        return driver;
    }

    @BeforeClass
    public static void startAppium() {
        String osName = System.getProperty("os.name").toLowerCase();
        AtomicReference<String> nodePath = new AtomicReference<>(null);
        String appiumPath = null;
        if (osName.contains("mac")) {
            nodePath.set("/usr/local/bin/node");
            appiumPath = "/usr/local/lib/node_modules/appium/build/lib/main.js";
        } else if (osName.contains("linux")) {
            nodePath.set(System.getenv("HOME") + "/.linuxbrew/bin/node");
            appiumPath = System.getenv("HOME") + "/.linuxbrew/lib/node_modules/appium/build/lib/main.js";
        }
        if (appiumPath != null) {
            service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
                    .usingDriverExecutable(new File(nodePath.get()))
                    .usingPort(4723)
                    .withAppiumJS(new File(appiumPath)));
        }
        service.start();
    }


    @BeforeMethod(alwaysRun = true)
    public void setUp() throws MalformedURLException {
        driver = (AndroidDriver) getDriver();
    }

    @Test
    public void testLogin() {
        driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.linkedin.android:id/login_button\")")
                .click();
        driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.linkedin.android:id/login_username_edit\")")
                .sendKeys("LinkedInUser");
        driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.linkedin.android:id/login_password_edit\")")
                .sendKeys("LinkedInPassword");
        driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.linkedin.android:id/login_ok_button\")")
                .click();
        driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.linkedin.android:id/diagree_sync\")")
                .click();
    }

    @Test
    public void testSearch() {
        driver.navigate().back();
        driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.linkedin.android:id/menu_search\")")
                .click();
        driver.findElementByAndroidUIAutomator("new UiSelector().resourceId(\"com.linkedin.android:id/search_v2_edit_text\")")
                .sendKeys("Ab");
    }

    @AfterMethod(alwaysRun = true)
    public void tearDown() throws MalformedURLException {
        driver.quit();
    }

    @AfterClass
    public static void stopAppium() {
        service.stop();
    }
}
`

@RatkoD And @saikrishna321 , i was trying to do this without reset flag. but need to execute driver.quit() which i believe not work with existing framework. will you guys please share your thoughts?

**Comment by RatkoD** [comment]
Hey @priyankshah217,
I've worked on this with a colleague and shared the code with @saikrishna321, I hope that soon it will be available here in the framework. It's minor change, but still needs to be testes for impact on other aspects of the framework.

**Comment by saikrishna321** [comment]
@priyankshah217 driver.quit() does work, if your using v1.5.3 and using session-override.

```
@BeforeMethod()
	public void startApp(Method name) throws Exception {
		DesiredCapabilities dc = new DesiredCapabilities();
		dc.setCapability("noReset", "true");

		//driver = startAppiumServerInParallel(name.getName());
		driver = startAppiumServerInParallel(name.getName(), dc);
		startLogResults(name.getName());
	}

public synchronized AppiumDriver<MobileElement> startAppiumServerInParallel(String methodName, DesiredCapabilities dc)
        throws Exception {
        ExtentTestManager.loadConfig();
        if (prop.getProperty("FRAMEWORK").equalsIgnoreCase("testng")) {
            child = ExtentTestManager.startTest(methodName, description, "ios")
                .assignCategory(category + "_" + device_udid.replaceAll("\\W", "_"));
        }
        Thread.sleep(3000);
        if (prop.getProperty("APP_TYPE").equalsIgnoreCase("web")) {
            driver = new AndroidDriver<>(appiumMan.getAppiumUrl(), androidWeb());
        } else {
            if (System.getProperty("os.name").toLowerCase().contains("mac")) {
                if (iosDevice.checkiOSDevice(device_udid)) {
                    driver = new IOSDriver<>(appiumMan.getAppiumUrl(), iosNative());
                } else if (!iosDevice.checkiOSDevice(device_udid)) {
                    driver = new AndroidDriver<>(appiumMan.getAppiumUrl(), androidNative(dc));
                }
            } else {
                driver = new AndroidDriver<>(appiumMan.getAppiumUrl(), androidNative(dc));
            }
        }

        return driver;
    }
```

So we let the users send the desireCaps as part of startAppiumServerInParallel and its left to the users to handle the driver.quit n stuff

@SrinivasanTarget thoughts ?

**Comment by priyankshah217** [comment]
Yes, I was using latest appium+Java client. So it's a good if you provide
flexibility to set driver object and also to quit object.
Because when I tried with driver.closeApp() it was not able to continue
next time. But I think it's a major change if we incorporate this to
existing framework.

**Comment by saikrishna321** [comment]
@priyankshah217 so if the users starts the server and starts the driver instance in @BeforeClass then they should quit only @AfterClass, this is default behaviour. 
* if a users does driver.closeApp in after method, they should call driver.launchApp @BeforeMethod

shouldn't the user handle this?

But as part of letting the user send they desiredCaps it good to provide

**Comment by shaynl** [comment]
@saikrishna321 
How to set the "noReset" with this fix?

**Comment by saikrishna321** [comment]
@shaynl you can send your capabilities 

https://github.com/saikrishna321/AppiumTestDistribution/blob/5aded86663a96ac152d1b163f7079bd8245bf3b4/src/test/java/com/test/site/UserBaseTest.java#L24

**Comment by shaynl** [comment]
@saikrishna321  Thanks. It's running now with noRest.
In your code tests runs only on Android. I removed ,androidNative() so tests will run also on IOS. driver should be: 
`driver = startAppiumServerInParallel(name.getName());`

**Comment by saikrishna321** [comment]
@shaynl yah it works for both android and iOS with default capabilities.

**Comment by shaynl** [comment]
@saikrishna321 Sorry my bad. driver should be:
`driver = startAppiumServerInParallel(name.getName(),iosNative(),androidNative()); `
to run on both platforms with new capabilities.
