### ISSUE TITLE
Not able to run project from eclipse even after setting ANDROID_HOME variable in runner.java class

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#7]
Hi Sai, Can you please help here, I am trying to make some modification in your sample test for debugging purpose in eclipse but even after setting ANDROID_HOME variable in runner.java class, i am not able to run from eclipse.

In Below screenshot you can see i have added "ANDROID_HOME" variable in runner.java class

![screen shot 2016-01-19 at 1 48 47 pm](https://cloud.githubusercontent.com/assets/12589206/12430221/151fd532-beb4-11e5-85b0-018833abbb71.png)

In below screenshot you can see i am trying to run project from eclipse using runner.java class as testng project

![screen shot 2016-01-19 at 1 49 42 pm](https://cloud.githubusercontent.com/assets/12589206/12430223/18593bda-beb4-11e5-9c43-05556bd1625a.png)

In below screenshot you can see the run logs, i have highlighted error msg.

![screen shot 2016-01-19 at 1 55 43 pm](https://cloud.githubusercontent.com/assets/12589206/12430280/73b959ba-beb4-11e5-956d-1b35a6976e28.png)

Below is the log  from Terminal where i am successfully be able to run this project without any errors

ushofml916k:PageObjectPatternAppium vsandes$ mvn clean -Dtest=Runner test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PagePatternAppium 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ PagePatternAppium ---
[INFO] Deleting /Users/vsandes/Desktop/searsAndroid_Apps/PageObjectPatternAppium/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ PagePatternAppium ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ PagePatternAppium ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ PagePatternAppium ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ PagePatternAppium ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 24 source files to /Users/vsandes/Desktop/searsAndroid_Apps/PageObjectPatternAppium/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ PagePatternAppium ---
[INFO] Surefire report directory: /Users/vsandes/Desktop/searsAndroid_Apps/PageObjectPatternAppium/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@8807e25
creating directory: Logs
DIR created
creating directory: ADBLogs
DIR created
adb service already started
Following device is connected
e9739647 samsung SM-G900P 4.4.2

Total Number of devices detected::1
starting running tests in threads
forEach: true
forEach: true
forEach: true
forEach: true
Running test file: com.appium.tests.AddCommentTest
Into TestNGRunner
[TestNG] Running:
  Command line suite

adb service already started
*************pool-1-thread-1
******Running Test in Distributed Way******1
Starting Appium Server
e9739647
info: Welcome to Appium v1.4.8 (REV c8179bd8352d3c62d98fa58b324491230df9342a)
info: Appium REST http interface listener started on 0.0.0.0:55457
info: Console LogLevel: info
info: File LogLevel: info
info: --> GET /wd/hub/status {}
info: <-- GET /wd/hub/status 200 8.517 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
info: --> GET /wd/hub/status {}
true
io.appium.java_client.service.local.AppiumServiceBuilder@2267791f
info: <-- GET /wd/hub/status 200 3.014 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/vsandes/Desktop/Appium/PageObjectPatternAppium/build/wordpress.apk","appPackage":"org.wordpress.android","appActivity":"org.wordpress.android.ui.WPLaunchActivity","platformVersion":"5.X","appWaitActivity":"org.wordpress.android.ui.accounts.SignInActivity","platformName":"Android","deviceName":"Android"}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: Starting android appium
info: Java version is: 1.8.0_25
info: Retrieving device
info: Found device e9739647
info: Device API level is: 19
info: App is already installed, resetting app
info: Starting App
info: <-- POST /wd/hub/session 303 13959.549 ms - 74 
info: --> GET /wd/hub/session/a9530ce2-63fe-4847-9d9f-642eb4cb123c {}
info: <-- GET /wd/hub/session/a9530ce2-63fe-4847-9d9f-642eb4cb123c 200 3.117 ms - 942 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"/Users/vsandes/Desktop/Appium/PageObjectPatternAppium/build/wordpress.apk","appPackage":"org.wordpress.android","appActivity":"org.wordpress.android.ui.WPLaunchActivity","platformVersion":"5.X","appWaitActivity":"org.wordpress.android.ui.accounts.SignInActivity","platformName":"Android","deviceName":"Android"},"app":"/Users/vsandes/Desktop/Appium/PageObjectPatternAppium/build/wordpress.apk","appPackage":"org.wordpress.android","appActivity":"org.wordpress.android.ui.WPLaunchActivity","appWaitActivity":"org.wordpress.android.ui.accounts.SignInActivity","platformName":"Android","deviceName":"e9739647"},"sessionId":"a9530ce2-63fe-4847-9d9f-642eb4cb123c"}
/Users/vsandes/Desktop/searsAndroid_Apps/PageObjectPatternAppium
Jan 19, 2016 1:24:32 PM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/Users/vsandes/.m2/repository/com/relevantcodes/extentreports/2.40/extentreports-2.40.jar!/com/relevantcodes/extentreports/resources/extent-config.xml

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara  please recheck if you have set the  ANDROID_HOME under Runner.java

**Comment by saikrishna321** [comment]
@VinitSandesara you had mentioned under this issue that it was resolved 
https://github.com/saikrishna321/AppiumTestDistribution/issues/3

**Comment by VinitSandesara** [comment]
Yes Sai, i said it resolved in https://github.com/saikrishna321/AppiumTestDistribution/issues/3 but i didn't run in eclipse that day, i tired on terminal only, Actually when i first tried to run project on terminal using maven command it didn't work so i raised an issue and after you have provided me solution i just tried on terminal and didn't try in eclipse. I should have tried in eclipse that day but i forgot and thought if it works on terminal should also work from eclipse.

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara can u see if the Runner class is set under the Test tab ?

**Comment by VinitSandesara** [comment]
Yes Sai, my runner class is set under the Test tab, you can see it in below screenshot.

![screen shot 2016-01-20 at 9 01 26 am](https://cloud.githubusercontent.com/assets/12589206/12452526/8db04b4e-bf54-11e5-8daf-048c0a15d8f3.png)


Does it allow you to run this sample project from eclipse at your end ? If so why am i not able to run from eclipse and you do even though having same configuration ?

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Hi Sai, I have fixed the issue setting environment variable "PATH" under configuration tab, along with ANDROID_HOME variable PATH variable also needed to set.

![screen shot 2016-01-20 at 10 59 53 am](https://cloud.githubusercontent.com/assets/12589206/12456474/a0040590-bf65-11e5-9528-d246cbee4f15.png)


Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara Awesome..

**Comment by ChethanGKC** [comment]
@saikrishna321 @VinitSandesara : I am also facing the same issue as above.. can you please suggest which path i need to pass is PATH variable....

**Comment by ChethanGKC** [comment]
Adding iOS devices
java.io.IOException: Cannot run program "adb": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.appium.utils.CommandPrompt.runCommand(CommandPrompt.java:21)
	at com.appium.manager.AndroidDeviceConfiguration.startADB(AndroidDeviceConfiguration.java:21)
	at com.appium.manager.AndroidDeviceConfiguration.getDeviceSerial(AndroidDeviceConfiguration.java:89)
	at com.appium.manager.AppiumParallelTest.<clinit>(AppiumParallelTest.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:377)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:290)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:130)
	at org.testng.TestRunner.initMethods(TestRunner.java:424)
	at org.testng.TestRunner.init(TestRunner.java:247)
	at org.testng.TestRunner.init(TestRunner.java:217)
	at org.testng.TestRunner.<init>(TestRunner.java:169)
	at org.testng.remote.support.RemoteTestNG6_9_10$1.newTestRunner(RemoteTestNG6_9_10.java:29)
	at org.testng.remote.support.RemoteTestNG6_9_10$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_9_10.java:65)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:594)
	at org.testng.SuiteRunner.init(SuiteRunner.java:168)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:117)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1319)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1306)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1160)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 33 more
Failed to initialize framework
[TestNG] Running:
  /private/var/folders/jf/5_ygmyfs5b3g9kfh8f31r5yw0000gn/T/testng-eclipse--1115184961/testng-customsuite.xml

**************ClosingAppiumSession****************1
FAILED CONFIGURATION: @BeforeClass startAppiumServer
org.testng.TestNGException: 
Parameter 'device' is required by @Configuration on method startAppiumServer but has not been marked @Optional or defined
in /private/var/folders/jf/5_ygmyfs5b3g9kfh8f31r5yw0000gn/T/testng-eclipse--1115184961/testng-customsuite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:154)

**Comment by saikrishna321** [comment]
@ChethanGKC pls set as show in the image


https://cloud.githubusercontent.com/assets/12589206/12456474/a0040590-bf65-11e5-9528-d246cbee4f15.png

**Comment by ChethanGKC** [comment]
@saikrishna321 i tried with the PATH yesterday but not working. Can you please resend the fully qualified PATH, as the image in the link doesn't show the full PATH.

**Comment by saikrishna321** [comment]
@ChethanGKC it has the full path, can you pls share the screenshot of your PATH

**Comment by ChethanGKC** [comment]
@saikrishna321 
https://cloud.githubusercontent.com/assets/20571390/22250275/52b53194-e26c-11e6-9206-fd548d75ddfc.png

**Comment by ChethanGKC** [comment]
@saikrishna321 - i am not sure with the path specified in the above screenshot after  /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Use...???? after "Users" i am unable to get which path i should set can you please elaborate on this please... i am new to appium grid...

**Comment by ChethanGKC** [comment]
@VinitSandesara can you please let me know which path i need to specify in path variable.

**Comment by saikrishna321** [comment]
@ChethanGKC your supposed to give your ANDROID_HOME and PATH, to get the PATH just do echo $PATH
