### ISSUE TITLE
Can you give control to user to turn on/off text file appiumlogs since it is breaking execution

### ISSUE THREAD

**Issue by YagneshShah** [saikrishna321/AppiumTestDistribution#73]
For Windows 8,
Error: EPERM: operation not permitted, stat 'C:\Users\Qapitol QA\IdeaProjects\flipkartSampleWithoutPageObjectMaven\target\appiumlogs\0123456789ABCDEF__validLoginTest.txt'
    at Error (native)

Can't delete the file manually also even though we have admin access. The only way to delete file is by sign-out from the system and log-in again.

Current file permission are:
-rw-r--r--
## case 1:

while re-executing the same test why not create a separate file with "unique test name + datetime" for logs instead of trying to access same file for overwriting/appending?
## case 2: (my preferred suggestion is to add this feature and give control to user)

 can you give a control to user via config.properties file variable to either turn on/off the logs based on our wish? If we can turn off the "appiumlogs" then at-least test execution would not be block

**Comment by saikrishna321** [comment]
@YagneshShah Error: EPERM: operation not permitted is something to do with your system permissions.

When re-executing the same test, currently the old data will be removed from your target folder and will b replaced to the newest one.

But don't you think when you have retained the previous execution data it gonna take a lot of your space

**Comment by YagneshShah** [comment]
@saikrishna321 
For case 1: 
Old data is not being removed for some reason in windows in-spite of me being an admin.
Yes it might take a lot of space but we can delete the logs manually

For case 2: If writing to new log file each time is not advisable then at-least the control should be provided to turn off/on the logs, since it is blocking the execution currently.
