### ISSUE TITLE
How to enable Extent reporting 

### ISSUE THREAD

**Issue by rajendraalagundi** [saikrishna321/AppiumTestDistribution#8]
HI Sai, 

I was able to run the tests in parallel on two emulators but I donot see any report generated.
How to enable reporting?

Also if I run the tests in distributed mode the tests are running on only one device.Is there any thing I missed.

Thanks,
Rajendra

**Comment by saikrishna321** [comment]
@rajendraalagundi 
you should see the reports under target folder by default.

**Comment by saikrishna321** [comment]
Not active, closing the ticket
