### ISSUE TITLE
Running tests in a loop

### ISSUE THREAD

**Issue by shaynl** [saikrishna321/AppiumTestDistribution#81]
Hi Sai, 
Great job! 
Can I run my tests with this tool in a loop?
for example, If I have 50 tests scripts, It will start running test 1 till test 50 and repeat them over and over again till I stop.
thanks.

**Comment by Jtramey** [comment]
You could just put that mvn command in a shell or batch file and use a
while true loop to run them an infinite amount of times.  Quick and simple!

**Comment by saikrishna321** [comment]
@shaynl you do can as @Jtramey suggested 

```
for (( ; ; ))
do
   echo "Pres CTRL+C to stop..."
   mvn clean -Dtest=Runner test
done
```
