### ISSUE TITLE
Could release screenshot path/appium log/adb log path to parameter in config.properties?

### ISSUE THREAD

**Issue by ansonliao** [saikrishna321/AppiumTestDistribution#82]
Hi @saikrishna321,
In ExtentReport, the screenshot, appium log, adb log, etc. are all use local machine's project path, for example the code below:

```java
logFile = new File(System.getProperty("user.dir") + "/target/adblogs/" + device_udid
                .replaceAll("\\W", "_") + "__" + methodName + ".txt");
```

after ExtentReport generated, the screenshot/adb log/appium log path will be such as `img src=file://Users/test/appium_parallel_project/target/screenshot/.../.../fail.png`

it is no problem for open ExtentReport in local machine, but fail to open report from remote for fetching the screenshot or logs.

for example, I published ExtentReport in Jenkins, when I open the extent report from my local working machine (the report saved in jenkins slave machine), but fail to load the screenshot or logs.

could you set a external properties that we can store it in config.properties which the screenshot/logs prefix uri, for example:

```java
img_prefix_url = "http://192.168.1.10/xxx/xxx/xxx"
```

and after the program fetched the full screenshot/log path is:
`http://192.168.1.10/xxx/xxx/xxx/target/screenshot/xxx/xxx/xxx.png"
and this full path will be logged into extent report.

any good idea?

**Comment by akhilbojedla** [comment]
@ansonliao Could you please elaborate the enhancement so that i can start working on this.

**Comment by ansonliao** [comment]
Hi @akhilbojedla , 
My question is in extentreport, the logs/failure screeshot's URL whether can be defined by personal in a property file (for example config.properties), for example, for TestNG framework, AppiumParallelTest.java, we can find ExtentReport log code such as below.

for adblogs:

```java
ExtentTestManager.getTest().log(LogStatus.INFO, result.getMethod().getMethodName(),
                    "ADBLogs:: <a href=" + System.getProperty("user.dir") + "/target/adblogs/"
                        + device_udid.replaceAll("\\W", "_") + "__" + result.getMethod()
                        .getMethodName() + ".txt" + ">AdbLogs</a>");
```

for screenshot of failure:

```java
ExtentTestManager.getTest()
                        .log(LogStatus.INFO, result.getMethod().getMethodName(),
                            "Snapshot below: " + ExtentTestManager.getTest().addScreenCapture(
                                System.getProperty("user.dir") + "/target/screenshot/android/"
                                    + device_udid.replaceAll("\\W", "_") + "/" + className + "/"
                                    + result.getMethod().getMethodName() + "/"
                                    + screenShotNameWithTimeStamp + deviceModel + "_failed_"
                                    + result.getMethod().getMethodName() + "_framed.png"));
```

as we can find that, the URL start with the system property value `System.getProperty("user.dir") `, so maybe the adblogs URL in extentreport look like: `file://Users/Test/AppiumParallelDemo/target/adblogs/Nexus6/debug/helloworld.txt`

my question is whether can replace the system property value `System.getProperty("user.dir") ` with a variable which set in config.properties.

for example, I backup the test result folder "target" to my private server, and the test target folder after uploaded the base URL maybe look like:
`https://192.168.10.32/xxx1/xxx2/`,
and the target folder full path maybe look like:
`https://192.168.10.32/xxx1/xxx2/target/`

so whether can set property that 
`EXTENTREPORT_BASE_URL=https://192.168.10.32/xxx1/xxx2/`

so that in `AppiumParallelTest.java`, we can use maybe look like below, replace `System.getProperty("user.dir")` with `EXTENTREPORT_BASE_URL`, if property `System.getProperty("user.dir")` is not `null`.

```java
ExtentTestManager.getTest()
                        .log(LogStatus.INFO, result.getMethod().getMethodName(),
                            "Snapshot below: " + ExtentTestManager.getTest().addScreenCapture(
                                EXTENTREPORT_BASE_URL + "/target/screenshot/android/"
                                    + device_udid.replaceAll("\\W", "_") + "/" + className + "/"
                                    + result.getMethod().getMethodName() + "/"
                                    + screenShotNameWithTimeStamp + deviceModel + "_failed_"
                                    + result.getMethod().getMethodName() + "_framed.png"));
```

**Comment by akhilbojedla** [comment]
@ansonliao So basically what you want to do is you want to upload these files to a file server and access it from there. May I know the exact use case that you find this enhancement useful.

**Comment by ansonliao** [comment]
@akhilbojedla 
grade to hear from you that it is basically to implement it, could you advise how to achieve it?

**Comment by ansonliao** [comment]
@akhilbojedla 
User case of Jenkins:
1. Jenkins Master computer (Jenkins Server) named `Computer A`.
2. Publish ExtentReport.html in Jenkins Job of Appium Parallel test project, slave machine of jenkins named `Computer B`.
3. Review test result of ExtentReport, named those computers `Computer C`.

Scenario:
1. 
`Computer C` login Jenkins and check the published extentreport, and will find that the logs/screenshot can't open correctly and maybe got error in can't find the file, because the logs/screenshot URL started with value of `System.getProperty("user.dir")`, this value is the local path of `Computer B`, the slave machine of Jenkins.

2. 
If Jenkins server URI is `https://192.168.20.35`, 
for example, from `Computer C`, can visit Jenkins Appium Parallel test project in `Computer B` by the link: `https://192.168.20.35/ws/AppiumApparallel/`,
so that, we can modify the logs/screenshot URI in published extentreport of Jenkins to `https://192.168.20.35/ws/AppiumApparallel/target/adblogs/xxx/xxx` or `https://192.168.20.35/ws/AppiumApparallel/screenshots/xxx/xxx`

so that, from `Computer C`, published extentreport of Jenkins, the logs/screenshots will be presented correctly.

please advise.

**Comment by akhilbojedla** [comment]
@ansonliao May I know how are you publishing extent report in slave machine?

**Comment by akhilbojedla** [comment]
If you use this [plugin](https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin) in jenkins you can access the report from jenkins job with all the screenshots and logs. If you need anything in additional then we can go with centralised server approach.

**Comment by saikrishna321** [comment]
Even if we use the Jenkins HTML plugin , extent report currently logs the path of the screenshot and logs of the locally machine. . this should be centralised

**Comment by akhilbojedla** [comment]
@saikrishna321 Completely agree... But when we open the report from running jenkins server.. something like http://jenkins-node:8080/jobs/jobname/10/Htmlreport.html.. It does show the report with screenshots and logs... Correct me if im wrong

**Comment by ansonliao** [comment]
@akhilbojedla 
I use HTML publisher plugin in Jenkins for publishing ExtentReport, please check below once I check published extentreport of Jenkins.

failure screenshot with `System.getProperty("user.dir")` value, please note `src =` of screenshot, displayed screenshot fail.
![image](https://cloud.githubusercontent.com/assets/6060224/17163265/1ec04320-53f0-11e6-906c-d780b2d2a845.png)

failure screenshot with valid jenkins URI, please note `src=` of screenshot, display screenshot succeeded.
![image](https://cloud.githubusercontent.com/assets/6060224/17163320/bf923268-53f0-11e6-91f9-6fc0fb2ea687.png)

**Comment by ansonliao** [comment]
@saikrishna321 
Thanks for your work on CI URl, could you also apply CI URI to `ExtentCucumberFormatter.java`?, the cucumber framework.

https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/cucumber/listener/ExtentCucumberFormatter.java

**Comment by anshooarora** [comment]
v3 pre-release is available now, and it has a feature to automatically create relative path for images.  So, with this feature, folders will be created and place all files next to the report and the updated relative paths will be used:

```
Report.html  <-- report file
/Report.0    <-- folder
   1.png
   2.png
```

**Comment by saikrishna321** [comment]
@anshooarora thanks a lot .. will take a look ..

**Comment by ansonliao** [comment]
@saikrishna321 
thanks for your work, as vacation days, I will check the latest version of AppiumTestDistribution soon.

**Comment by shaynl** [comment]
@saikrishna321 can I start use extent reports 3 in my project?

**Comment by saikrishna321** [comment]
nope ... I think they are still on SNAPSHOT

**Comment by shaynl** [comment]
@saikrishna321 The only issue I have now with the reports is when copy the target folder to different location I can't see screenshots and logs. I tried to use the CI_BASE_URI in config file and set it to "." to create a relative path but it didn't work because of the "/target". Is there a way to remove it?

**Comment by saikrishna321** [comment]
@shaynl pls try with this version its fixed 

        <dependency>
            <groupId>com.github.saikrishna321</groupId>
            <artifactId>AppiumTestDistribution</artifactId>
            <version>8d8c700</version>
        </dependency>

**Comment by shaynl** [comment]
@saikrishna321 this version have the issue that say "no device connected" when connecting 1 or 2 Android devices (can tests only on Android at the moment). How to fix that? any other changes I need to do?

**Comment by saikrishna321** [comment]
@shaynl nope.. wierd .. Can u check adb devices

**Comment by shaynl** [comment]
@saikrishna321 yes. This is the first thing I checked. I can see all the connected devices....
what else should I check?

**Comment by karthikbhatnagar** [comment]
@saikrishna321 - can you pls integrate v3 of extentreports? it was released 2 days ago.

**Comment by saikrishna321** [comment]
@karthikbhatnagar can u pls raise  issue for this, easy to track
