### ISSUE TITLE
Ghost devices shown by idevice_id and mobiledevice

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#85]
Very often ghost devices are listed using this tools so this causes failed tests in appium. The suggested solution is to use system_profiler to list connected iPhones/iPads instead of idevice tool  and use that result later on for the tests. Device's UDIDs can be listed with:
system_profiler SPUSBDataType | sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ Serial Number: (.+)/\1/p'

**Comment by RatkoD** [comment]
Hey @saikrishna321, it seems like you fix only works if only one device is connected, if I connect two or more devices, it doesn't work, it concatenates the UDIDs, here is a log from what I get

`creating directory: Logs
No Device Connected
a55460712308b368e035ad4b61d065460f8966eb

a55460712308b368e035ad4b61d065460f8966ebc205d576285a38492cce0f8580c007f0abf37fac

/usr/local/lib/node_modules/appium/build/lib
iOSWebKitProxyLauncher File already has access to execute
IOS a55460712308b368e035ad4b61d065460f8966eb Directory is created!
IOS c205d576285a38492cce0f8580c007f0abf37fac Directory is created!
***************************************************

Total Number of devices detected::2

***************************************************

starting running tests in threads
a55460712308b368e035ad4b61d065460f8966eb

a55460712308b368e035ad4b61d065460f8966ebc205d576285a38492cce0f8580c007f0abf37fac

Adding iOS devices
a55460712308b368e035ad4b61d065460f8966eb

a55460712308b368e035ad4b61d065460f8966ebc205d576285a38492cce0f8580c007f0abf37fac

No Device Connected
{a55460712308b368e035ad4b61d065460f8966ebc205d576285a38492cce0f8580c007f0abf37fac=true}
...
... TestNG 6.9.10 by Cédric Beust (cedric@beust.com)
...
`

and btw I saw in your code that there is one backslash extra at the end of the line:
system_profiler SPUSBDataType | sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ Serial Number: (.+)/\**\**1/p'

**Comment by saikrishna321** [comment]
@RatkoD good catch .. i don't have devices right now with me.. would be able to send a PR with the fix

If not i may need 2 days time to fix this

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/pull/88
