### ISSUE TITLE
getTreeForXML command leads memory leak in app and resulting in app crash if the page has huge objects

### ISSUE THREAD

**Issue by Pushpank** [saikrishna321/AppiumTestDistribution#86]
[debug] [Instruments] [INST] 2016-07-19 08:07:45 +0000 Debug: evaluation finished
[debug] [UIAuto] Socket data received (27 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":true}
[debug] [iOS] Setting initial orientation to PORTRAIT
[debug] [UIAuto] Sending command to instruments: au.setScreenOrientation('PORTRAIT')
[debug] [Instruments] [INST] 2016-07-19 08:07:45 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-07-19 08:07:45 +0000 Debug: Running system command #1: /usr/local/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /Users/srikanta_Dirolabs/Documents/workspace/AppiumTestDistribution-master/target/tmp_55178/instruments_sock 2,{"status"...
[debug] [Instruments] [INST] 2016-07-19 08:07:46 +0000 Debug: Got new command 1 from instruments: au.setScreenOrientation('PORTRAIT')
[debug] [Instruments] [INST] 2016-07-19 08:07:46 +0000 Debug: evaluating au.setScreenOrientation('PORTRAIT')
[debug] [Instruments] [INST] 2016-07-19 08:07:46 +0000 Debug: target.setDeviceOrientation("1")
[debug] [Instruments] [INST] 2016-07-19 08:07:47 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-07-19 08:07:47 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-07-19 08:07:47 +0000 Debug: Running system command #2: /usr/local/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /Users/srikanta_Dirolabs/Documents/workspace/AppiumTestDistribution-master/target/tmp_55178/instruments_sock 2,{"status"...
[debug] [UIAuto] Socket data received (33 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":"PORTRAIT"}
[debug] [iOS] Waiting for app source to contain elements
[debug] [UIAuto] Sending command to instruments: au.mainApp().getTreeForXML()
[debug] [Instruments] [INST] 2016-07-19 08:07:48 +0000 Debug: Got new command 2 from instruments: au.mainApp().getTreeForXML()
[debug] [Instruments] [INST] 2016-07-19 08:07:48 +0000 Debug: evaluating au.mainApp().getTreeForXML()
[debug] [Instruments] [INST] 2016-07-19 08:07:49 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-07-19 08:07:49 +0000 Debug: responding with:ue,"visible":true,"hint":null,"path":"/0/0","x":0,"y":0,"width":320,"height":568},">":[{"UIANavigationBar":{"@":{"name":"9443","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0","x":0,"y":20,"width":320,"height":44},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/0","x":0,"y":0,"width":320,"height":64},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/0/0","x":0,"y":64,"width":320,"height":0.5},">":[]}}]}},{"UIAButton":{"@":{"name":"Back","label":"Back","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/1","x":8,"y":31.5,"width":21,"height":21},">":[]}},{"UIAButton":{"@":{"name":"9443","label":"9443","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0/2","x":139.5,"y":42,"width":41,"height":0},">":[]}},{"UIAButton":{"@":{"name":"Add","label":"Add","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0/3","x":275.5,"y":26,"width":40,"height":30},">":[]}}]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/1","x":0,"y":64,"width":320,"height":44},">":[]}},{"UIASegmentedControl":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/2","x":8,"y":71,"width":304,"height":29},">":[{"UIAButton":{"@":{"name":"Title","label":"Title","value":"","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/2/0","x":8,"y":71,"width":151,"height":29},">":[]}},{"UIAButton":{"@":{"name":"Title","label":"Title","value":"","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/2/1","x":160,"y":71,"width":152,"height":29},">":[]}}]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/3","x":0,"y":64,"width":320,"height":44},">":[]}},{"UIASearchBar":{"@":{"name":"Search","label":"Search","value":"Search","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/4","x":8,"y":72,"width":240,"height":28},">":[]}},{"UIAButton":{"@":{"name":"Cancel","label":"Cancel","value":null,"dom":null,"enabled":false,"valid":true,"visible":true,"hint":null,"path":"/0/0/5","x":259,"y":70,"width":53,"height":30},">":[]}},{"UIATableView":{"@":{"name":null,"label":null,"value":"moved to row 1 of 1","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6","x":0,"y":107,"width":320,"height":460},">":[{"UIATableGroup":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/6/0","x":0,"y":107,"width":320,"height":0.01000213623046875},">":[]}},{"UIATableCell":{"@":{"name":"My Contacts","label":null,"value":"","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/1","x":0,"y":107.01000213623047,"width":320,"height":88.00000762939453},">":[{"UIAStaticText":{"@":{"name":"My Contacts","label":"My Contacts","value":"My Contacts","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/1/0","x":68,"y":125.00999450683594,"width":164,"height":19},">":[]}},{"UIAStaticText":{"@":{"name":"Private, not shared","label":"Private, not shared","value":"Private, not shared","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/1/1","x":86,"y":144.00999450683594,"width":177,"height":18},">":[]}},{"UIAStaticText":{"@":{"name":"Rev No. - 1","label":"Rev No. - 1","value":"Rev No. - 1","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/1/2","x":71,"y":162.00999450683594,"width":194,"height":16},">":[]}},{"UIAStaticText":{"@":{"name":"919","label":"919","value":"919","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/1/3","x":263,"y":141.00999450683594,"width":42,"height":20},">":[]}},{"UIAButton":{"@":{"name":"caller 50x50","label":"caller 50x50","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/1/4","x":12,"y":119.00999450683594,"width":45,"height":45},">":[]}}]}},{"UIATableGroup":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/6/2","x":0,"y":195.010009765625,"width":320,"height":0.0099945068359375},">":[]}},{"UIATableGroup":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/6/3","x":0,"y":195.02000427246094,"width":320,"height":14},">":[]}},{"UIATableGroup":{"@":{"name":"Other Phonebooks View hidden phonebooks","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/4","x":0,"y":209.02000427246094,"width":320,"height":50.00099182128906},">":[{"UIAButton":{"@":{"name":"Other Phonebooks View hidden phonebooks","label":"Other Phonebooks View hidden phonebooks","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/4/0","x":0,"y":209.02000427246094,"width":320,"height":70.00001525878906},">":[]}}]}},{"UIATableGroup":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/6/5","x":0,"y":259.02099609375,"width":320,"height":14},">":[]}},{"UIATableGroup":{"@":{"name":"New Phonebook Create and share","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/6","x":0,"y":273.02099609375,"width":320,"height":150},">":[{"UIAButton":{"@":{"name":"New Phonebook Create and share","label":"New Phonebook Create and share","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/6/6/0","x":12.800003051757812,"y":300.02099609375,"width":294.4000244140625,"height":60},">":[]}}]}}]}},{"UIAToolbar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/7","x":0,"y":568,"width":320,"height":44},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/7/0","x":0,"y":567.5,"width":320,"height":0.5},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/7/1","x":0,"y":568,"width":320,"height":44},">":[]}}]}},{"UIATabBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/8","x":0,"y":519,"width":320,"height":49},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/8/0","x":0,"y":518.5,"width":320,"height":0.5},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/8/1","x":0,"y":519,"width":320,"height":49},">":[]}},{"UIAButton":{"@":{"name":"Speed Dial","label":"Speed Dial","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/8/2","x":2,"y":520,"width":60,"height":48},">":[]}},{"UIAButton":{"@":{"name":"Calls","label":"Calls","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/8/3","x":66,"y":520,"width":60,"height":48},">":[]}},{"UIAButton":{"@":{"name":"Phonebooks","label":"Phonebooks","value":1,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/8/4","x":130,"y":520,"width":60,"height":48},">":[]}},{"UIAButton":{"@":{"name":"Keypad","label":"Keypad","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/8/5","x":194,"y":520,"width":60,"height":48},">":[]}},{"UIAButton":{"@":{"name":"More","label":"More","value":null,"dom":null,"enabled":
[debug] [Instruments] [INST] true,"valid":true,"visible":true,"hint":null,"path":"/0/0/8/6","x":258,"y":520,"width":60,"height":48},">":[]}}]}}]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/1","x":0,"y":0,"width":320,"height":568},">":[]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/2","x":0,"y":0,"width":320,"height":568},">":[{"UIAStatusBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/2/0","x":0,"y":0,"width":320,"height":20},">":[{"UIAElement":{"@":{"name":"No SIM","label":"No SIM","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/0","x":6,"y":0,"width":41,"height":20},">":[]}},{"UIAElement":{"@":{"name":"3 of 3 Wi-Fi bars","label":"3 of 3 Wi-Fi bars","value":"SSID","dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/1","x":52,"y":0,"width":13,"height":20},">":[]}},{"UIAElement":{"@":{"name":"1:37 PM","label":"1:37 PM","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/2","x":139,"y":0,"width":47,"height":20},">":[]}},{"UIAElement":{"@":{"name":"38% battery power, Charging","label":"38% battery power, Charging","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/3","x":282,"y":0,"width":33,"height":20},">":[]}}]}}]}}]}}}
       2016-07-19 08:07:49 +0000 Debug: Running system command #3: /usr/local/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /Users/srikanta_Dirolabs/Documents/workspace/AppiumTestDistribution-master/target/tmp_55178/instruments_sock 2,{"status"...
[debug] [UIAuto] Socket data received (8192 bytes)
[debug] [UIAuto] Socket data received (2378 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"Diro","label":"Diro","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":320,"height":568},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":tr
[Appium] New IosDriver session created successfully, session 85df04da-8792-4519-a47f-a788fbf02807 added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,...
[HTTP] <-- POST /wd/hub/session 200 33738 ms - 749 
skipping test
[HTTP] --> DELETE /wd/hub/session/85df04da-8792-4519-a47f-a788fbf02807 {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["85df04da-8792-4519-a47f-a...
[debug] [iOS] Deleting ios session
[debug] [UIAuto] Destroying instruments client socket.
[debug] [UIAuto] Closing socket server.
[debug] [UIAuto] Instruments socket server was closed
[debug] [Instruments] Starting shutdown.
[debug] [Instruments] Sending sigterm to instruments
[debug] [Instruments] [INST] 2016-07-19 08:07:50 +0000 Stopped: Script was stopped by the user
[debug] [Instruments] [INST STDERR] 2016-07-19 13:37:50.472 instruments[28260:426991] Attempting to change event horizon while disengage
[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 15.833512s; Output : /Users/srikanta_Dirolabs/Documents/workspace/AppiumTestDistribution-master/target/tmp_55178/appium-instruments/instrumentscli0.trace)
[debug] [Instruments] Instruments exited with code 0
[debug] [iOSLog] Stopping iOS log capture
[debug] [iOS] Running ios real device reset flow
[Appium] Removing session 85df04da-8792-4519-a47f-a788fbf02807 from our master session list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/85df04da-8792-4519-a47f-a788fbf02807 200 1914 ms - 76 
Setting iOS Desired Capabilities:
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/RajShekhar_DiroLabs/Desktop/Appium/Diro.ipa","platformVersion":"9.0","bundleId":"com.DiroBeta1.0.Diro","udid":"c5e5a7246cdcf756c8604df1558391cb1eb6c2c0","platformName":"iOS","deviceName":"iPhone","autoAcceptAlerts":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/RajShekhar_...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/RajShekhar_DiroLabs/Desktop/Appium/Diro.ipa'
[Appium]   platformVersion: '9.0'
[Appium]   bundleId: 'com.DiroBeta1.0.Diro'
[Appium]   udid: 'c5e5a7246cdcf756c8604df1558391cb1eb6c2c0'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone'
[Appium]   autoAcceptAlerts: true
[BaseDriver] Session created with session id: 3b7dd479-dc15-45f6-9261-5c582ec92c77
[debug] [iOS] Not auto-detecting udid.
[BaseDriver] Using local app '/Users/RajShekhar_DiroLabs/Desktop/Appium/Diro.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/ys/m78mnsws5ds1g73hdw694k3w0000gn/T/2016619-28247-1uya8oe/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/ys/m78mnsws5ds1g73hdw694k3w0000gn/T/2016619-28247-1uya8oe/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/ys/m78mnsws5ds1g73hdw694k3w0000gn/T/2016619-28247-1uya8oe/Payload/Diro.app'
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /Users/srikanta_Dirolabs/Documents/workspace/AppiumTestDistribution-master/target/tmp_55178/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[debug] [iOS] Parsed app 'Localizable.strings'
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/RajShekhar_DiroLabs/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/Users/srikanta_Dirolabs/Documents/workspace/AppiumTestDistribution-master/target/tmp_55178/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":true,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...bug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
[debug] [UIAuto] Dynamic bootstrap path: /Users/RajShekhar_DiroLabs/Library/Application Support/appium/bootstrap/bootstrap-5839e561c6576ef7.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/RajShekhar_DiroLabs/Library/Application Support/appium/bootstrap/bootstrap-5839e561c6576ef7.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] Creating iDevice object with udid c5e5a7246cdcf756c8604df1558391cb1eb6c2c0
[debug] [iOS] App is installed.
[debug] [iOS] fullReset not requested. No need to install.
[debug] [iOS] Starting UIAutoClient, and launching Instruments.
[debug] [UIAuto] Instruments socket server started at /Users/srikanta_Dirolabs/Documents/workspace/AppiumTestDistribution-master/target/tmp_55178/instruments_sock
Error: listen EADDRINUSE /Users/srikanta_Dirolabs/Documents/workspace/AppiumTestDistribution-master/target/tmp_55178/instruments_sock
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at UIAutoClient.start$ (lib/uiauto-client.js:145:23)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
FAILED CONFIGURATION: @BeforeMethod startApp(public void com.test.site.Signup_Diro.IOS_Signup() throws java.lang.Exception)
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'srikantas-Mac-mini-3.local', ip: '10.2.10.44', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.2', java.version: '1.8.0_40'
Driver info: driver.version: IOSDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)

**Comment by saikrishna321** [comment]
@Pushpank this should be raised at the appium server end..
