### ISSUE TITLE
TestNG Tests Run Count after Retry is showing incorrect test count

### ISSUE THREAD

**Issue by rajguptaolx** [saikrishna321/AppiumTestDistribution#92]
@saikrishna321 @SrinivasanTarget 
After retry in testng, when we see the extentreport, it shows the incorrect count.
For example, I have 1 test which got failed and Max retry count is 1. So failed testcase will be executed 1 more time.
Now after execution, Extent Report shows Total tests as 2 out of which 1 got failed and 1 in skip, but my total testcases is only 1

**Comment by saikrishna321** [comment]
@rajguptaolx this issue is still open on extentreport repo 
https://github.com/anshooarora/extentreports-java/issues/106
