### ISSUE TITLE
failed configuration

### ISSUE THREAD

**Issue by geoHeil** [saikrishna321/AppiumTestDistribution#93]
Hi, I try to follow along for the example from https://github.com/saikrishna321/PageObjectPatternAppium but for Appium Version 1.5.3 this is the exeption after setting the following configuration:

```
ANDROID_APP_PATH=....../appiumExample/build/wordpress.apk
APP_PACKAGE=org.wordpress.android
APP_ACTIVITY=org.wordpress.android.ui.WPLaunchActivity
RUNNER=distribute
APPIUM_JS_PATH=/Users/myUser/.nvm/versions/node/v4.4.7/lib/node_modules/appium/lib/server/main.js
BROWSER_TYPE=chrome
APP_TYPE=NA
FRAMEWORK=testng
IOS_APP_PATH=........./appiumExample/build/ios.app
```

```

@BeforeClass beforeClass
io.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance exception has occured: The invalid appium node /Users/myUser/.nvm/versions/node/v4.4.7/lib/node_modules/appium/lib/server/main.js has been defined
```

**Comment by saikrishna321** [comment]
@geoHeil pls make sure you have ANDROID_APP_PATH & IOS_APP_PATH absolute.

APPIUM_JS_PATH should point to the below 
## For appium 1.5.X users (If appium installed using npm)
APPIUM_JS_PATH=/usr/local/lib/node_modules/appium/build/lib/main.js

**Comment by geoHeil** [comment]
Indeed appium doctor tells me that everything is fine. I use nvm so my path
is a little bit different.
Sai Krishna <notifications@github.com> schrieb am Mi., 10. Aug. 2016 um
06:35:

**Comment by saikrishna321** [comment]
@geoHeil 

can u run this /Users/myUser/.nvm/versions/node/v4.4.7/lib/node_modules/appium/lib/server/main.js and see if appium server starts ?

**Comment by geoHeil** [comment]
From appium version 1.5 onwards the server folder is non existing. The main js resided directly in the library folder ![](http://i.imgur.com/NsAlQDC.jpg)

**Comment by saikrishna321** [comment]
Can u run the entire path ? Not just the main.js

**Comment by geoHeil** [comment]
I am not sure how to do that. 

Should I run the gulp file? If yes which path?

**Comment by saikrishna321** [comment]
Can u hit this command n see if Appium server starts 

 /Users/myUser/.nvm/versions/node/v4.4.7/lib/node_modules/appium/lib/server/main.js

To me this looks incoreecr, as it should be /nkde_modules/appium/build/lib/main.js

**Comment by geoHeil** [comment]
Indeed this command including the /server is not correct. 

But the one without it should work as shown in the picture. But as you can see there, it seems to throw an error. 

I didn't get that error when experimenting with appium 1.4x but didn't get it to work either.

**Comment by saikrishna321** [comment]
@geoHeil try to uninstall appium and install it with npm install -g appium and then give it a try

**Comment by geoHeil** [comment]
@saikrishna321 I uninstalled and re-installed appium.
This is the result:
![2__bash_und_1__bash](https://cloud.githubusercontent.com/assets/1694964/17578872/f2adc4ec-5f8e-11e6-84d0-66d2a168140a.jpg)
so executing the main.js still fails

**Comment by saikrishna321** [comment]
@geoHeil you should have the main.js under the path /usr/local/lib/node_modules/appium/build/lib/main.js if you have installed over npm install -g appium 

@SrinivasanTarget any help here

**Comment by geoHeil** [comment]
@saikrishna321 so you suggest to use "default node" and not `nvm` installed node? because in the latter case appium or any package is installed in ~/.nvm/version/node/_node_version/node_modules folder

**Comment by SrinivasanTarget** [comment]
Hey @geoHeil 

You have to run the main.js through node in terminal

i.e ``` node /usr/local/lib/node_modules/appium/build/lib/main.js```

**Comment by geoHeil** [comment]
Thanks. This was a misunderstanding on my side. Executing a `node main.js` unfortunately brings up the same error. I use node v4.4.7

```
/Users/geoHeil/.nvm/versions/node/v4.4.7/lib/node_modules/appium/lib/main.js:4
import { init as logsinkInit } from './logsink';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by SrinivasanTarget** [comment]
@geoHeil How did you executed? ping the entire command that you ran? or the gist of it or the screenshot of it.

**Comment by saikrishna321** [comment]
@geoHeil just run the entire path 

node /usr/local/lib/node_modules/appium/build/lib/main.js

**Comment by geoHeil** [comment]
running the whole absolute path like 
`node /Users/geoHeil/.nvm/versions/node/v4.4.7/lib/node_modules/appium/lib/main.js`
still fails with the same error:
```
/Users/geoHeil/.nvm/versions/node/v4.4.7/lib/node_modules/appium/lib/main.js:4
import { init as logsinkInit } from './logsink';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by SrinivasanTarget** [comment]
Ok I dont get whats wrong here. So uninstall everything and install appium via this command: ```npm install -g appium```

**Comment by geoHeil** [comment]
I tried it on a different computer. Seems to work there. 
Strange.

**Comment by parul001** [comment]
same problem is with my appium , main.js gives the above error when i try to build a appium local service. when i run path of main.js i.e.somewhat like this :C:/Users/parulb/AppData/Local/Programs/appium-desktop/resources/app/node_modules/appium/lib/main.js on console  its gives a dialog box with Microsoft  jScript compilation error . dn know what to do . Plzz help

**Comment by parul001** [comment]
hi,
with reference to above comment below are my  version deatils for appium n all :
+1: Appium :1.7
2. Nodejs version:9.5
3 : window 7
4 java client 5.0.4
