### ISSUE TITLE
whats wrong? DISTRIBUTE mode happen?

### ISSUE THREAD

**Issue by johnChnia** [saikrishna321/AppiumTestDistribution#94]
2016-08-12 04:28:40:008 - error: [MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command 'D:\Android\sdk\platform-tools\adb.exe -P 5037 -s 192.168.85.102:5555 pull G:\data\local\tmp\screenshot.png C:\Users\john\AppData\Local\Temp\appium116712-10644-1ovgriu.png' exited with code 1{"stdout":"","stderr":"remote object 'G:\data\local\tmp\screenshot.png' does not exist\r\n","code":1}
    at ADB.execFunc$ (lib/tools/system-calls.js:189:13)
    at tryCatch (D:\nodejs\node_modules.npminstall\babel-runtime\5.8.24\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](D:nodejsnode_modules.npminstallbabel-runtime5.8.24babel-runtimeregeneratorruntime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw](D:nodejsnode_modules.npminstallbabel-runtime5.8.24babel-runtimeregeneratorruntime.js:100:21)
    at GeneratorFunctionPrototype.invoke (D:\nodejs\node_modules.npminstall\babel-runtime\5.8.24\babel-runtime\regenerator\runtime.js:136:37)
    at run (D:\nodejs\node_modules.npminstall\core-js\1.2.7\core-js\library\modules\es6.promise.js:108:47)
    at D:\nodejs\node_modules.npminstall\core-js\1.2.7\core-js\library\modules\es6.promise.js:119:28
    at flush (D:\nodejs\node_modules.npminstall\core-js\1.2.7\core-js\library\modules\$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by johnChnia** [comment]
i connected two android simulator， only one can run nomal, the other one start the app, then report the above error

code of  HomePageTest2:

@Description("This Test validates swipe scenarios")
public class HomePageTest2
    extends UserBaseTest {

    @Test
    @Author(name = "John") public void testMethodOne_2() throws Exception {
        System.out.println(
            "ThreadName1: " + Thread.currentThread().getName() + Thread.currentThread()
                .getStackTrace()[1].getClassName());
        Thread.sleep(3000);
        for (int i = 0; i < 10; i++) {
        	getDriver().findElement(By.id("com.example.calculator:id/button2")).click();
            getDriver().findElement(By.id("com.example.calculator:id/jia")).click();
            getDriver().findElement(By.id("com.example.calculator:id/button4")).click();
		}
        
    }
}

code of HomePageTest3:

  @Test
   public void testMethodOne_3()
        throws InterruptedException, IOException {

        System.out.println(
            "ThreadName2: " + Thread.currentThread().getName() + Thread.currentThread()
                .getStackTrace()[1].getClassName());
        Thread.sleep(3000);
        captureScreenShot("TestMethod1");
        System.out.println(
                "ThreadName: " + Thread.currentThread().getName() + Thread.currentThread()
                    .getStackTrace()[1].getClassName());
            Thread.sleep(3000);
            for (int i = 0; i < 10; i++) {
            	getDriver().findElement(By.id("com.example.calculator:id/button5")).click();
                getDriver().findElement(By.id("com.example.calculator:id/jia")).click();
                getDriver().findElement(By.id("com.example.calculator:id/button9")).click();
    		}
            
        }
        //getDriver().close();
    }


config.properties:

#APP_PATH=/Users/saikrisv/Downloads/***.ipa
APP_PACKAGE=com.example.calculator
APP_ACTIVITY=com.example.calculator.MainActivity
RUNNER=distribute
APPIUM_JS_PATH=D://nodejs//node_modules//.npminstall//appium//1.5.3//appium//build//lib//main.js
BROWSER_TYPE=chrome
APP_TYPE=NA
BUNDLE_ID=com.tesco.grocery
IOS_APP_PATH=/Users/srinivasansekar/Downloads/Grocery-iOS-LIVE-debug-293.ipa
ANDROID_APP_PATH=G://workspace_Friday//calculator.apk
FRAMEWORK=testng
MONGODB_SERVER=ADDRESS_OF_THE_SERVER
MONGODB_PORT=PORT_NUMBER
#CI_BASE_URI=http://Your_Jenkins_URL/path_to_your_project_till_root



please tell me what happend?  

Thanks a lot.

**Comment by saikrishna321** [comment]
@johnChnia can you pls point to the appium version your running ?

hit this command in your commandline 
D://nodejs//node_modules//.npminstall//appium//1.5.3//appium//build//lib//main.js and post the stack

**Comment by johnChnia** [comment]
@saikrishna321  when  i hit this command in commandline, then, report a error:

![image](https://cloud.githubusercontent.com/assets/12187260/17656785/6dc00b40-62f0-11e6-95b7-0967c69dc1a0.png)

**Comment by johnChnia** [comment]
@saikrishna321  but i can start appium
![image](https://cloud.githubusercontent.com/assets/12187260/17656809/af3b0a2a-62f0-11e6-8abb-6b9107eeb497.png)

**Comment by saikrishna321** [comment]
You have the incorrect path to main.js 


Can u tell me how u installed Appium ?

**Comment by johnChnia** [comment]
i installed Appium like blow:

1、npm install -g cnpm --registry=https://registry.npm.taobao.org

2、cnpm install -g appium


because i am in china, so i use this command "npm install -g appium" is not work well, so i use taobao mirror

**Comment by saikrishna321** [comment]
@johnChnia you need to give the right appium server path, i'm not sure in windows where it resides..

**Comment by saikrishna321** [comment]
@priyankshah217 @SrinivasanTarget

**Comment by priyankshah217** [comment]
@johnChnia , are you launching appium using gui?

**Comment by SrinivasanTarget** [comment]
@johnChnia  you can find the path of node modules in windows using ```echo $(npm root -g)```

Then actual path would be:  ``` node path_found_using_above_command/appium/build/lib/main.js```.

**Comment by johnChnia** [comment]
@saikrishna321  

![image](https://cloud.githubusercontent.com/assets/12187260/17722251/596c71e6-6463-11e6-8127-7c94e57e2283.png)

and  i use this command "echo $(npm root -g)", the output like blow:

![image](https://cloud.githubusercontent.com/assets/12187260/17722261/73edd604-6463-11e6-865b-d7f70067f21b.png)

**Comment by saikrishna321** [comment]
Give the full path of the main.js which is shown in first screenshot in the above comment .... that will work
