### ISSUE TITLE
[Enhancement] config.properties: let ANDROID_APP_PATH or IOS_APP_PATH are supported download URL

### ISSUE THREAD

**Issue by ansonliao** [saikrishna321/AppiumTestDistribution#96]
@saikrishna321 
From Appium official document, app's capability in path is support download URL, but actually seems that download URL is out of support.

I have a implemented to support download link for `AppiumTestDistribution` in `config.properties`, and the download code in Java, please check below:

``` java
public static synchronized void copyFileFromURL(String url, String destDirectory) {
        int TIME_OUT = 5*1000*60;   // 5 mins

        try {
            FileUtils.copyURLToFile(new URL(url), new File(destDirectory), TIME_OUT, TIME_OUT);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

public static void main(String[] args) {
        CommonUtility.copyFileFromURL(
                // get download URL from config.properties
                "http://example.com/download/example.apk",
                "/Users/ansonliao/Desktop/AppiumTestDistribution/build/example.apk");
    }
```

so next step we can use automatically parse IPA information to get `BUNDLE_ID` of IPA, and automatically parse `package name`, `launch activity` of APK, and then set the capabilities of appium server:

if [Download  URL of APP in `config.properties`] 
    --->
      Download App
else
    ---->
        Use local App
and then -->
Parse App to get `bundle ID` or `package name`, `launch activity`
--> 
Set capabilities of appium

please advise.

**Comment by saikrishna321** [comment]
@ansonliao but not every user would have the apk hosted ?

**Comment by ansonliao** [comment]
@saikrishna321 
yes, not every user would have the apk/ipa hosted, so maybe need to add a step to check whether the `APP_PATH` value read from `config.properties` whether is a valid URL, or it is local machine path.

**Comment by saikrishna321** [comment]
This is supported in remote-service branch
