### ISSUE TITLE
How to change report folder and keep all previous reports?  

### ISSUE THREAD

**Issue by shaynl** [saikrishna321/AppiumTestDistribution#97]
Hi Sai,
How I can change ExtentReports report default location and keep all reports.
I want to use Google drive to store all output report so I can access them from anywhere.
Is it also possible to send the report by email in the end?
Thanks.

**Comment by saikrishna321** [comment]
http://extentreports.relevantcodes.com/extentx/ the framework supports ExtentX which helps u store reports remotely.

Check the WiKi under Running TestNg test and config.properties section 

Email able reports will be available in extent reports v3

**Comment by shaynl** [comment]
thanks Sai. I installed the extentX and I can see all my reports there but without any screenshots or logs. also all the filters from the standalone extent report are gone.
In my other framework (without your tool) I implement extent reports so it save reports with dynamic name (with timestamp) to a google drive folder like this:
instance = new ExtentReports(reportFile, true, NetworkMode.OFFLINE);
How to do the same with your tool?

**Comment by saikrishna321** [comment]
@shaynl i'm aware that screenshots and logs are getting attached on ExtentX, which needs to be fixed on extent report end.
 > instance = new ExtentReports(reportFile, true, NetworkMode.OFFLINE); 

how is this line sending your reports to google driver ?

**Comment by shaynl** [comment]
in my code: 

reportFile = resultDirectory + fileName + ".html";

resultDirectory = System.getProperty("user.home") + "/GoogleDrive/Automation/reports/" + System.getProperty("user.name");

so it save to the local GoogleDrive folder and from there it automatically sync to the drive on the web. Now I can also generate link to the report and send it by email with the unique folder ID:

reportLink = "https://www.googledrive.com/host/<folderID>/" + System.getProperty("user.name") + fileName + ".html";

Not that this is just a workaround till ExtentX will show screenshots and logs. I think ExtentX is much better way to store reports.

**Comment by saikrishna321** [comment]
@shaynl when u have your reports syncing from google driver folder, where does your screenshots and logs locate? In the same google drive folder ?

**Comment by shaynl** [comment]
Yes. I generate them in a function to the same folder under "screenshots":
String imagePath = "/screenshots/screenshot_" + dateTimeGenerator() + Thread.currentThread().getId() + ".jpg";
            File scrFile = driver.getScreenshotAs(OutputType.FILE);
            FileUtils.copyFile(scrFile, new File(reportsPath + imagePath));
            return "." + imagePath;

**Comment by saikrishna321** [comment]
when u have extentX support do you still see a point to use google driver ?

**Comment by shaynl** [comment]
extentX seems to be better solution... this is just till extentX will have screenshots and log.
If it's to complicated i'll wait for the next release.

**Comment by saikrishna321** [comment]
ah . i dont think so ..  let me see a way for this ...

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/issues/51

**Comment by shaynl** [comment]
Thanks Sai. It's also be good to have an option to change the default report name from ExtentReport.html to something else. I'm using a dynamic name depending on what i'm tasting. It's easier to track the reports that way.

**Comment by saikrishna321** [comment]
@shaynl so how do you name the reports dynamically, would help understand before looking into this

**Comment by shaynl** [comment]
fileName = appVersion + "_" + suiteName + "_" + dateTimeGenerator();
appVersion is a string i'm updating manually in the code when new app build is out (can I read this from the apk/ipa file?). 
suiteName i'm taking from TestNG XML file like this: testContext.getCurrentXmlTest().getSuite().getName();
(This can be: Sanity, Regression, Full Cycle etc... )
dateTimeGenerator - generate the current date and time:
public static String dateTimeGenerator()
    {
        Format formatter = new SimpleDateFormat("YYYYMMdd_HHmmssSSS");
        Date date = new Date(System.currentTimeMillis());
        return formatter.format(date);
    }

If you think about better way to show this info let me know.

**Comment by shaynl** [comment]
@saikrishna321 In the meantime, can I do something to keep all previous reports with screenshots and logs locally?

**Comment by saikrishna321** [comment]
@shaynl if you want to keep all reports and logs locally, then you need to move the folders to a separate location locally ?

**Comment by shaynl** [comment]
@saikrishna321 So for now I created a function that copy the target folder to Google Drive and rename it dynamically based on current date and time. I call it at AfterSuite:

`public void saveReportFolder() throws IOException {
        File srcDir = new File(System.getProperty("user.home")+"/Automation/target");
        File destDir = new File(System.getProperty("user.home")
                + "/GoogleDrive/reports/"+ System.getProperty("user.name")+"/"+dateTimeGenerator());
        FileUtils.copyDirectory(srcDir, destDir);
    }` 

`@AfterSuite() public void endCycle() throws IOException {
        saveReportFolder();
    }`

**Comment by shaynl** [comment]
@saikrishna321 
 I just noticed that when copying the target folder to different location, images not show in the reports. I see that you are using the project path for the image location. it should replaced by "./"
so instead of:
>file:////Users/shayn/Automation3/target/screenshot/android/4ee465a6/com.appium.tests.ProdTests/T014_Game_Play_Games/2016-09-13T19:37:59SMN910V_Verizon_T014_Game_Play_Games_failed.png

it should be:
> ./screenshot/android/4ee465a6/com.appium.tests.ProdTests/T014_Game_Play_Games/2016-09-13T19:37:59SMN910V_Verizon_T014_Game_Play_Games_failed.png

**Comment by saikrishna321** [comment]
@shaynl its relative now ..
